#!/usr/bin/env python3
"""Generate the N5 disposable PREDICTION_SUPPORT broad-phase proof pin."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "Tools/sigma/authority/SigmaMerkabaAuthorityManifest.json"
OUTPUT = ROOT / "Runtime/SigmaPrism/Generated/SigmaGeneratedQuerySupport.cs"


def render() -> str:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    query = next(
        item for item in manifest["queryFamilies"]
        if item["id"] == "PREDICTION_SUPPORT"
    )
    summary = manifest["querySupportSummary"]
    expected = {
        "entryArity": "FULL_FIELD_PLUS_SENSOR_QUERY",
        "localContribution": "SENSOR_FORWARD_WITNESS",
        "reduction": ["DIRECT_ORDER", "FIRST_HIT", "OCCLUSION"],
    }
    for key, value in expected.items():
        if query[key] != value:
            raise RuntimeError(f"PREDICTION_SUPPORT {key} changed")
    if summary["falseNegatives"] != 0 or summary["missingOrStale"] != \
            "FAIL_CLOSED_INCLUDE_OR_REHYDRATE":
        raise RuntimeError("query-support fail-closed authority changed")

    program = manifest["programFingerprint"]
    reductions = ",".join(query["reduction"])
    descriptor = (
        f"{query['id']}|{query['entryArity']}|"
        f"{query['localContribution']}|{reductions}|"
        "EXACT_GEOMETRY_READOUT_Q48_AABB|"
        "FINITE_CONTACT_FOOTPRINT_OUTWARD|"
        f"MISSING_STALE_CORRUPT_INCLUDE|PROGRAM={program}"
    )
    fingerprint = hashlib.sha256(descriptor.encode("ascii")).hexdigest()
    return f'''// <auto-generated by Tools/sigma/generate_sigma_query_support.py>
// Derived N5 execution metadata only. It has no canonical mutation authority.

namespace Genesis.RoomScan.SigmaPrism
{{
    internal static class SigmaGeneratedQuerySupport
    {{
        internal const string QueryId = "{query['id']}";
        internal const string EntryArity = "{query['entryArity']}";
        internal const string LocalContribution =
            "{query['localContribution']}";
        internal const string Reductions = "{reductions}";
        internal const string ProgramFingerprint = "{program}";
        internal const string PlanDescriptor =
            "{descriptor}";
        internal const string PlanFingerprint = "{fingerprint}";
        internal const bool MissingStaleCorruptMustInclude = true;
        internal const int FalseNegativeAllowance = 0;
    }}
}}
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            raise SystemExit("SigmaGeneratedQuerySupport.cs is stale")
        return 0
    OUTPUT.write_text(expected, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
