#ifndef SIGMA_PERFORMANCE_ABI_INCLUDED
#define SIGMA_PERFORMANCE_ABI_INCLUDED

#include "Generated/SigmaGeneratedLayout.hlsl"

// GPU-resident Section 44 diagnostic readout. These counters are disposable
// execution telemetry and never participate in canonical Psi mutation.
#define SIGMA_PERF_ACTIVE_CARRIER_SAMPLES 0u
#define SIGMA_PERF_ACTIVE_TRANSITIONS 1u
#define SIGMA_PERF_TRANSITION_CACHE_HIT 2u
#define SIGMA_PERF_TRANSITION_CACHE_MISS 3u
#define SIGMA_PERF_XOR_PERMUTATION_OPS 4u
#define SIGMA_PERF_SIGNED_ADD_SUB_OPS 5u
#define SIGMA_PERF_MASK_SELECT_OPS 6u
#define SIGMA_PERF_Q48_WIDE_MUL_OPS 7u
#define SIGMA_PERF_Q48_DIV_OPS 8u
#define SIGMA_PERF_INTERVAL_MULDIV_OPS 9u
#define SIGMA_PERF_ANNIHILATOR_WITNESS_EVALS 10u
#define SIGMA_PERF_GENERIC_DENSE_S16_PRODUCTS 11u
#define SIGMA_PERF_OPERATOR_PLAN_INVOCATIONS 12u
#define SIGMA_PERF_SOURCE_CELLS_BUILT 13u
#define SIGMA_PERF_SOURCE_CELLS_MET 14u
#define SIGMA_PERF_EMPTY_MEETS 15u
#define SIGMA_PERF_BYTES_READ 16u
#define SIGMA_PERF_BYTES_WRITTEN 17u
#define SIGMA_PERF_COUNTER_COUNT 18u
#define SIGMA_PERF_TOPOLOGY_HISTORY_COUNT 8u

#endif
