// <auto-generated by Tools/sigma/generate_sigma_operators.py>
// Canonical baseline: CPQ4-2026-08-24-S16-v7. Do not edit by hand.
#ifndef SIGMA_FRAME_ABI_INCLUDED
#define SIGMA_FRAME_ABI_INCLUDED

#include "SigmaCarrierAbi.hlsl"

#define SIGMA_NATIVE_SENSOR_SIDE_COUNT 2u
#define SIGMA_NATIVE_LEAF_COUNT 4u
#define SIGMA_FRAME_LANE_COUNT 16u
#define SIGMA_FRAME_INVALID 0xffffffffu
#define SIGMA_NATIVE_SENSOR_SIDE_LEFT 0u
#define SIGMA_NATIVE_SENSOR_SIDE_RIGHT 1u
#define SIGMA_NATIVE_LEAF_KIND_ORDER 0u
#define SIGMA_NATIVE_LEAF_KIND_OPTICAL0 1u
#define SIGMA_NATIVE_LEAF_KIND_OPTICAL1 2u
#define SIGMA_NATIVE_LEAF_KIND_OPTICAL2 3u
#define SIGMA_NATIVE_FIRST_HIT_ROLE_NO_CLAIM 0u
#define SIGMA_NATIVE_FIRST_HIT_ROLE_PRE_HIT_EXCLUSION 1u
#define SIGMA_NATIVE_FIRST_HIT_ROLE_FIRST_HIT_MOULD 2u
#define SIGMA_NATIVE_FRAME_DISPOSITION_FREE 0u
#define SIGMA_NATIVE_FRAME_DISPOSITION_GPU_OWNED 1u
#define SIGMA_NATIVE_FRAME_DISPOSITION_NO_CHANGE 2u
#define SIGMA_NATIVE_FRAME_DISPOSITION_RESOLVED 3u
#define SIGMA_NATIVE_FRAME_DISPOSITION_UNRESOLVED 4u
#define SIGMA_NATIVE_FRAME_DISPOSITION_PUBLISHED 5u
#define SIGMA_NATIVE_FRAME_DISPOSITION_FAULTED 6u
#define SIGMA_NATIVE_COLD_REASON_NONE 0u
#define SIGMA_NATIVE_COLD_REASON_CONTRACTOR_OVERFLOW 1u
#define SIGMA_NATIVE_COLD_REASON_REPRESENTATION_REFINEMENT 2u
#define SIGMA_NATIVE_COLD_REASON_PAGE_FAULT 3u
#define SIGMA_NATIVE_COLD_REASON_GAUGE_NORMALIZATION 4u
#define SIGMA_NATIVE_REVISION_STATE_FREE 0u
#define SIGMA_NATIVE_REVISION_STATE_BUILDING 1u
#define SIGMA_NATIVE_REVISION_STATE_CLOSED 2u
#define SIGMA_NATIVE_REVISION_STATE_PUBLISHED 3u
#define SIGMA_NATIVE_OBSERVATION_COHERENT 0x00000001u
#define SIGMA_NATIVE_OBSERVATION_LEFT_FIRST_HIT 0x00000002u
#define SIGMA_NATIVE_OBSERVATION_RIGHT_FIRST_HIT 0x00000004u
#define SIGMA_NATIVE_OBSERVATION_LEFT_EVIDENCE 0x00000008u
#define SIGMA_NATIVE_OBSERVATION_RIGHT_EVIDENCE 0x00000010u
#define SIGMA_NATIVE_OBSERVATION_OPTICAL_CLAIM 0x00000020u
#define SIGMA_NATIVE_OBSERVATION_PRIOR_SUPPORT 0x00000040u
#define SIGMA_NATIVE_OBSERVATION_FAULT 0x80000000u
#define SIGMA_NATIVE_DELTA_RESOLVED 0x00000001u
#define SIGMA_NATIVE_DELTA_COMMON 0x00000002u
#define SIGMA_NATIVE_DELTA_STATE_CHANGED 0x00000004u
#define SIGMA_NATIVE_DELTA_GAUGE_CHANGED 0x00000008u
#define SIGMA_NATIVE_DELTA_EVIDENCE_RETAINED 0x00000010u
#define SIGMA_NATIVE_DELTA_FAULT 0x80000000u

static const uint SIGMA_FRAME_ABI_FINGERPRINT[8] = { 0x886541c8u, 0x96d7e227u, 0x888fd9e3u, 0x71ae879au, 0x188a9976u, 0xd2d726bdu, 0x76ae5fd3u, 0xcd524222u };

struct SigmaNativeFrameGpu
{
    uint4 Identity;
    uint4 Disposition;
    uint4 Evidence;
    uint4 Publication;
};
struct SigmaNativeObservationGpu
{
    uint4 Identity;
    uint4 Footprint;
    uint4 Evidence;
    uint4 Query;
};
struct SigmaNativeReverseWorkGpu
{
    uint4 Identity;
    uint4 Support;
    uint4 Relation;
    uint4 Provenance;
};
struct SigmaNativeStateDeltaGpu
{
    uint4 Coordinate;
    uint4 Generation;
    uint4 Changed;
    uint4 Witness;
    uint4 Receipts;
    uint4 State01;
    uint4 State23;
    uint4 State45;
    uint4 State67;
    uint4 State89;
    uint4 State1011;
    uint4 State1213;
    uint4 State1415;
};
struct SigmaNativeGaugeDeltaGpu
{
    uint4 Coordinate;
    uint4 Prior;
    uint4 Next;
    uint4 Witness;
};
struct SigmaUnresolvedConstraintGpu
{
    uint4 Observation;
    uint4 Relation;
    uint4 Evidence;
    uint4 Provenance;
};
struct SigmaNativeFieldRevisionGpu
{
    uint4 Identity;
    uint4 Changed;
    uint4 Evidence;
    uint4 Publication;
};

#endif
