// <auto-generated by Tools/sigma/generate_sigma_operators.py>
// Canonical baseline: CPQ4-2026-08-22-S16-v6. Do not edit by hand.
#ifndef SIGMA_STREAMING_ABI_INCLUDED
#define SIGMA_STREAMING_ABI_INCLUDED

#include "SigmaCarrierAbi.hlsl"

#define SIGMA_STREAM_TRANSACTION_CAPACITY 8u
#define SIGMA_STREAM_BUNDLE_CAPACITY 64u
#define SIGMA_STREAM_MAX_PAGES 4u
#define SIGMA_STREAM_SOURCE_HANDLE_WINDOW 8u
#define SIGMA_STREAM_PROOF_CANDIDATE_WINDOW 12u
#define SIGMA_STREAM_PROOF_SOURCE_CLASS_COUNT 4u
#define SIGMA_STREAM_PROOF_BLOCKS_PER_PAGE 64u
#define SIGMA_STREAM_MICROTILES_PER_BLOCK 4u
#define SIGMA_STREAM_CALIBRATION_Q48_PER_BUNDLE 88u
#define SIGMA_STREAM_OPCODE_COUNT 13u
#define SIGMA_STREAM_TOKEN_QUANTUM 512u
#define SIGMA_STREAM_INVALID 0xffffffffu

#define SIGMA_STREAM_BUNDLE_FREE 0u
#define SIGMA_STREAM_BUNDLE_EXTRACTING 1u
#define SIGMA_STREAM_BUNDLE_READY 2u
#define SIGMA_STREAM_BUNDLE_PROBATION 3u
#define SIGMA_STREAM_BUNDLE_ADMISSION_PENDING 4u
#define SIGMA_STREAM_BUNDLE_ACTIVE 5u
#define SIGMA_STREAM_BUNDLE_ABSORBED 6u
#define SIGMA_STREAM_BUNDLE_DORMANT 7u

#define SIGMA_STREAM_TRANSACTION_FREE 0u
#define SIGMA_STREAM_TRANSACTION_WAITING_DEPENDENCY 1u
#define SIGMA_STREAM_TRANSACTION_EVALUATING 2u
#define SIGMA_STREAM_TRANSACTION_PROOF_PENDING 3u
#define SIGMA_STREAM_TRANSACTION_TRANSITION_PENDING 4u
#define SIGMA_STREAM_TRANSACTION_REVALIDATE_PENDING 5u
#define SIGMA_STREAM_TRANSACTION_PUBLISHABLE 6u
#define SIGMA_STREAM_TRANSACTION_PUBLISHED 7u
#define SIGMA_STREAM_TRANSACTION_DORMANT 8u
#define SIGMA_STREAM_TRANSACTION_FAILED 9u

#define SIGMA_STREAM_MANIFEST_FREE 0u
#define SIGMA_STREAM_MANIFEST_PREPARING 1u
#define SIGMA_STREAM_MANIFEST_PUBLISHED 2u
#define SIGMA_STREAM_MANIFEST_RETIRED 3u

#define SIGMA_STREAM_OUTCOME_NO_EVIDENCE 0u
#define SIGMA_STREAM_OUTCOME_EXISTING_UPDATE 1u
#define SIGMA_STREAM_OUTCOME_NULL_PROMOTION 2u
#define SIGMA_STREAM_OUTCOME_EMPTY_EXACT 3u
#define SIGMA_STREAM_OUTCOME_TRANSITION_UNRESOLVED 4u

#define SIGMA_STREAM_SOURCE_SEGMENT_FREE 0u
#define SIGMA_STREAM_SOURCE_SEGMENT_OPEN 1u
#define SIGMA_STREAM_SOURCE_SEGMENT_SEALED 2u
#define SIGMA_STREAM_SOURCE_SEGMENT_SPILLED 3u

#define SIGMA_STREAM_PROOF_IDLE 0u
#define SIGMA_STREAM_PROOF_JOURNAL 1u
#define SIGMA_STREAM_PROOF_SORT_RUNS 2u
#define SIGMA_STREAM_PROOF_MERGE_RUNS 3u
#define SIGMA_STREAM_PROOF_COALESCE 4u
#define SIGMA_STREAM_PROOF_PREFIX 5u
#define SIGMA_STREAM_PROOF_REDUNDANCY 6u
#define SIGMA_STREAM_PROOF_EMIT_CERTIFICATES 7u
#define SIGMA_STREAM_PROOF_EMIT_RAW 8u
#define SIGMA_STREAM_PROOF_CLOSED 9u

// Transient execution ownership. These bits never become canonical state.
#define SIGMA_STREAM_PHASE_PREPARED (1u << 0u)
#define SIGMA_STREAM_PHASE_RGB_LEFT (1u << 1u)
#define SIGMA_STREAM_PHASE_RGB_RIGHT (1u << 2u)
#define SIGMA_STREAM_PHASE_MET (1u << 3u)
#define SIGMA_STREAM_PHASE_FINAL (1u << 4u)
#define SIGMA_STREAM_EXECUTION_ISSUED (1u << 5u)
#define SIGMA_STREAM_PHASE_ALL (SIGMA_STREAM_PHASE_PREPARED |     SIGMA_STREAM_PHASE_RGB_LEFT | SIGMA_STREAM_PHASE_RGB_RIGHT |     SIGMA_STREAM_PHASE_MET | SIGMA_STREAM_PHASE_FINAL |     SIGMA_STREAM_EXECUTION_ISSUED)
#define SIGMA_STREAM_EXECUTION_OUTCOME_SHIFT 16u
#define SIGMA_STREAM_EXECUTION_OUTCOME_MASK (0x1fu <<     SIGMA_STREAM_EXECUTION_OUTCOME_SHIFT)
#define SIGMA_STREAM_EXECUTION_FAULT (1u << 31u)

uint SigmaStreamOutcomeBit(uint outcome)
{
    return outcome <= SIGMA_STREAM_OUTCOME_TRANSITION_UNRESOLVED
        ? 1u << (SIGMA_STREAM_EXECUTION_OUTCOME_SHIFT + outcome) : 0u;
}

#define SIGMA_STREAM_BUDGET_NONE 0u
#define SIGMA_STREAM_BUDGET_INGRESS_ADMISSION 1u
#define SIGMA_STREAM_BUDGET_CANONICAL_PROGRESS 2u
#define SIGMA_STREAM_BUDGET_PROOF_TRANSITION_CLOSURE 3u
#define SIGMA_STREAM_BUDGET_DERIVED_READOUT 4u

#define SIGMA_STREAM_OPCODE_NONE 0u
#define SIGMA_STREAM_OPCODE_ADMIT 1u
#define SIGMA_STREAM_OPCODE_EXTRACT_BUNDLE 2u
#define SIGMA_STREAM_OPCODE_EVALUATE_MICROTILE 3u
#define SIGMA_STREAM_OPCODE_REDUCE_SOURCE_BLOCK 4u
#define SIGMA_STREAM_OPCODE_FINALIZE_PROOF_BLOCK 5u
#define SIGMA_STREAM_OPCODE_TRANSITION_ANNIHILATOR 6u
#define SIGMA_STREAM_OPCODE_TRANSITION_ASSOCIATOR 7u
#define SIGMA_STREAM_OPCODE_REVALIDATE 8u
#define SIGMA_STREAM_OPCODE_PUBLISH_MANIFEST 9u
#define SIGMA_STREAM_OPCODE_DERIVED_TOPOLOGY 10u
#define SIGMA_STREAM_OPCODE_DERIVED_READOUT 11u
#define SIGMA_STREAM_OPCODE_DORMANT_RECHECK 12u

struct SigmaStreamPageReferenceGpu
{
    uint4 coordinate;
    uint4 state;
};

struct SigmaTransactionGpu
{
    uint4 identity;
    uint4 ticket;
    uint4 dependencyTicket;
    uint4 source;
    uint4 publication;
    SigmaStreamPageReferenceGpu page0;
    SigmaStreamPageReferenceGpu page1;
    SigmaStreamPageReferenceGpu page2;
    SigmaStreamPageReferenceGpu page3;
    uint4 affectedMaskLo;
    uint4 affectedMaskHi;
    uint4 completedMaskLo;
    uint4 completedMaskHi;
    uint4 progress;
    uint4 execution;
    uint4 scratch;
    uint4 transition;
    uint4 dependency0;
    uint4 dependency1;
};

struct SigmaSealedSourceBundleGpu
{
    uint4 identity;
    uint4 provenance;
    uint4 keys;
    uint4 raw;
    uint4 calibration;
    uint4 probation;
    uint4 dependency;
};

struct SigmaProbationGpu
{
    uint4 identity;
    uint4 bundleHandles;
    uint4 support;
    uint4 dependency;
};

struct SigmaSourceHandleSegmentGpu
{
    uint4 identity;
    uint4 link;
    uint4 handle01;
    uint4 handle23;
    uint4 handle45;
    uint4 handle67;
};

struct SigmaProofClosureGpu
{
    uint4 identity;
    uint4 sourceCursor;
    uint4 journal;
    uint4 ordering;
    uint4 coalesce;
    uint4 redundancy;
    uint4 result;
    uint4 reserved;
};

struct SigmaProofCandidateGpu
{
    uint4 identity;
    uint4 provenance;
    uint4 mask;
    uint4 source;
};

struct SigmaProofPrefixGpu
{
    uint4 coordinateMask;
    uint4 independence;
    uint4 gate;
};

struct SigmaAssociationSampleGpu
{
    uint4 leftDepthPage;
    uint4 leftStateUv;
    uint4 leftGeneration;
    uint4 rightDepthPage;
    uint4 rightStateUv;
    uint4 rightGeneration;
};

struct SigmaPublicationManifestGpu
{
    uint4 identity;
    uint4 closure;
    uint4 pages;
    uint4 reserved;
};

struct SigmaPageVisibilityGpu
{
    uint4 bornRetired;
    uint4 pins;
};

struct SigmaStreamWorkItemGpu
{
    uint4 identity;
    uint4 cursor;
};

struct SigmaStreamDiagnosticGpu
{
    uint4 admission;
    uint4 transactions;
    uint4 proof;
    uint4 transition;
    uint4 publication;
    uint4 lifetime;
    uint4 memory;
    uint4 reserved;
};

static const uint SIGMA_STREAM_KERNEL_TOKEN_COST[SIGMA_STREAM_OPCODE_COUNT] = { 0u, 5u, 10u, 88u, 21u, 26u, 46u, 7u, 578u, 4u, 46u, 18u, 23u };
static const uint SIGMA_STREAM_KERNEL_BUDGET_CLASS[SIGMA_STREAM_OPCODE_COUNT] = { 0u, 1u, 1u, 2u, 3u, 3u, 3u, 3u, 3u, 3u, 4u, 4u, 1u };
static const uint SIGMA_STREAM_KERNEL_THREAD_COUNT[SIGMA_STREAM_OPCODE_COUNT] = { 1u, 64u, 64u, 256u, 64u, 64u, 256u, 64u, 256u, 64u, 256u, 64u, 64u };
static const uint SIGMA_STREAM_KERNEL_BYTES_READ[SIGMA_STREAM_OPCODE_COUNT] = { 0u, 8192u, 24576u, 40960u, 50176u, 32768u, 4096u, 1024u, 3145728u, 2048u, 4096u, 16384u, 32768u };
static const uint SIGMA_STREAM_KERNEL_BYTES_WRITTEN[SIGMA_STREAM_OPCODE_COUNT] = { 0u, 1024u, 12288u, 16384u, 12288u, 16384u, 128u, 128u, 1048576u, 2048u, 1024u, 8192u, 16384u };
static const uint SIGMA_STREAM_KERNEL_SCRATCH_BYTES[SIGMA_STREAM_OPCODE_COUNT] = { 0u, 1024u, 2048u, 24576u, 4096u, 16384u, 4096u, 2048u, 256u, 512u, 4096u, 2048u, 128u };
static const uint SIGMA_STREAM_KERNEL_BARRIER_COUNT[SIGMA_STREAM_OPCODE_COUNT] = { 0u, 8u, 4u, 158u, 16u, 4u, 9u, 8u, 13u, 4u, 9u, 4u, 0u };
static const uint SIGMA_STREAM_KERNEL_WITNESS_COUNT[SIGMA_STREAM_OPCODE_COUNT] = { 0u, 0u, 0u, 0u, 0u, 0u, 168u, 0u, 0u, 0u, 168u, 0u, 0u };
static const uint SIGMA_STREAM_KERNEL_MAX_RECORDS[SIGMA_STREAM_OPCODE_COUNT] = { 0u, 64u, 64u, 16u, 64u, 12u, 1u, 1u, 64u, 4u, 1u, 64u, 64u };

#endif
