#ifndef SIGMA_TOPOLOGY_ABI_INCLUDED
#define SIGMA_TOPOLOGY_ABI_INCLUDED

#include "SigmaCarrierAbi.hlsl"

#define SIGMA_TRANSITIONS_PER_PAGE (SIGMA_PAGE_SAMPLE_COUNT * 2u)

#define SIGMA_TOPOLOGY_REGULAR 0u
#define SIGMA_TOPOLOGY_SINGULAR 1u
#define SIGMA_TOPOLOGY_UNRESOLVED 2u
#define SIGMA_TOPOLOGY_UNSUPPORTED 3u

#define SIGMA_TOPOLOGY_CLASS_MASK 3u
#define SIGMA_TOPOLOGY_NEAR_ANNIHILATOR (1u << 2u)
#define SIGMA_TOPOLOGY_EXACT_ANNIHILATOR (1u << 3u)
#define SIGMA_TOPOLOGY_CONTACT_NULL (1u << 4u)
#define SIGMA_TOPOLOGY_ASSOCIATOR (1u << 5u)
#define SIGMA_TOPOLOGY_INVALID (1u << 6u)
#define SIGMA_TOPOLOGY_DISCONTINUITY_EVIDENCE (1u << 7u)
#define SIGMA_TOPOLOGY_ANNIHILATOR_SHIFT 8u
#define SIGMA_TOPOLOGY_ANNIHILATOR_MASK (0xffu << SIGMA_TOPOLOGY_ANNIHILATOR_SHIFT)
#define SIGMA_TOPOLOGY_LEFT_CONTACT (1u << 16u)
#define SIGMA_TOPOLOGY_RIGHT_CONTACT (1u << 17u)

#define SIGMA_TOPOLOGY_TRIANGLE_0_CUT (1u << 0u)
#define SIGMA_TOPOLOGY_TRIANGLE_1_CUT (1u << 1u)
#define SIGMA_TOPOLOGY_CELL_SINGULAR (1u << 2u)
#define SIGMA_TOPOLOGY_CELL_UNRESOLVED (1u << 3u)
#define SIGMA_TOPOLOGY_ALL_TRIANGLES_CUT \
    (SIGMA_TOPOLOGY_TRIANGLE_0_CUT | SIGMA_TOPOLOGY_TRIANGLE_1_CUT | \
     SIGMA_TOPOLOGY_CELL_UNRESOLVED)

#define SIGMA_ASSOCIATOR_VALID (1u << 0u)
#define SIGMA_ASSOCIATOR_STRONG (1u << 1u)

#define SIGMA_TOPOLOGY_EVIDENCE_NONE 0u
#define SIGMA_TOPOLOGY_EVIDENCE_PROPOSALS 1u
#define SIGMA_TOPOLOGY_EVIDENCE_FULL_STEREO 2u

uint SigmaTopologyClass(uint packed)
{
    return packed & SIGMA_TOPOLOGY_CLASS_MASK;
}

uint SigmaTopologyAnnihilatorId(uint packed)
{
    return (packed & SIGMA_TOPOLOGY_ANNIHILATOR_MASK) >>
        SIGMA_TOPOLOGY_ANNIHILATOR_SHIFT;
}

uint SigmaTopologyPack(uint classification, uint annihilatorId, uint flags)
{
    return (classification & SIGMA_TOPOLOGY_CLASS_MASK) |
        ((annihilatorId & 0xffu) << SIGMA_TOPOLOGY_ANNIHILATOR_SHIFT) |
        flags;
}

#endif
