// Render kernel table: push layouts (twins of Native~/shaders/render/*.comp), bindings and embedded SPIR-V
// (<stem>_spirv.inc / k<Stem>Spirv, generated by Tools~/native/build_native.sh).
#pragma once
#include <stdint.h>
#include "render_hzb_scatter_spirv.inc"
#include "render_hzb_combine_spirv.inc"
#include "render_hzb_mips_spirv.inc"
#include "render_cull_pages_spirv.inc"
#include "render_cull_nodes_spirv.inc"
#include "render_cull_emit_spirv.inc"
#include "render_cull_compact_spirv.inc"

namespace fs {
namespace render {

enum : uint32_t { RB_FRAME = 0, RB_SLOTS = 1, RB_SURFELS = 2, RB_NODES = 3, RB_ERRORS = 4, RB_WORK = 5, RB_DRAW = 6, RB_HZB = 7,
                  RB_ARGS = 3, RB_STATS = 4, RB_AGGSRC = 2, RB_DEPTH_PREV = 2, RB_DEPTH_ENV = 3 };
struct PushFrame  { uint32_t frameSlot; };
struct PushPages  { uint32_t frameSlot, slotCount; };
struct PushCull   { uint32_t frameSlot, aggBase, aggCapacity, opaqueCapacity; };

enum RenderKernel : uint32_t { R_HZB_SCATTER = 0, R_HZB_COMBINE, R_HZB_MIPS, R_CULL_PAGES, R_CULL_NODES, R_CULL_EMIT, R_CULL_COMPACT, R_COUNT };
struct KernelSpec { const char* name; const uint32_t* spirv; size_t words; uint32_t pushBytes; uint32_t bindings[8]; uint32_t bindingCount; uint32_t samplerBindings; };
#define FS_KS(sym) sym, sizeof(sym) / 4
static const KernelSpec kRenderKernels[R_COUNT] = {
    {"render_hzb_scatter", FS_KS(kRenderHzbScatterSpirv), sizeof(PushFrame), {RB_FRAME, RB_HZB, RB_DEPTH_PREV, RB_DEPTH_ENV}, 4, 2},
    {"render_hzb_combine", FS_KS(kRenderHzbCombineSpirv), 0,                 {RB_HZB}, 1, 0},
    {"render_hzb_mips",    FS_KS(kRenderHzbMipsSpirv),    0,                 {RB_HZB}, 1, 0},
    {"render_cull_pages",  FS_KS(kRenderCullPagesSpirv),  sizeof(PushPages), {RB_FRAME, RB_SLOTS, RB_WORK}, 3, 0},
    {"render_cull_nodes",  FS_KS(kRenderCullNodesSpirv),  sizeof(PushCull),  {RB_FRAME, RB_SLOTS, RB_NODES, RB_ERRORS, RB_WORK, RB_DRAW, RB_HZB}, 7, 0},
    {"render_cull_emit",   FS_KS(kRenderCullEmitSpirv),   sizeof(PushCull),  {RB_FRAME, RB_SLOTS, RB_SURFELS, RB_WORK, RB_DRAW}, 5, 0},
    {"render_cull_compact",FS_KS(kRenderCullCompactSpirv),sizeof(PushCull),  {RB_FRAME, RB_AGGSRC, RB_ARGS, RB_STATS, RB_WORK, RB_DRAW}, 6, 0},
};
#undef FS_KS

} // namespace render
} // namespace fs
