// GENERATED by MerkabaSphereFlowerCodegen. DO NOT EDIT.
#pragma once
#include <cstddef>
#include <cstdint>

namespace genesis::sphere_flower_abi
{
constexpr uint32_t kSchemaVersion = 3u;
constexpr uint32_t kR1SeedFlag = 0x00000002u;
#pragma pack(push, 4)
struct KernelStateAbi {
    int32_t occupancyEvidence;
    uint32_t packedColor;
    uint32_t colorConfidence;
    uint32_t flags;
};
struct DualBlockMeta {
    uint32_t stateAndGeneration;
    uint32_t payloadIndex;
};
struct DualBlockChildren { uint32_t words[32]; };
struct DualChunkPayload {
    uint32_t nonFullMaskLo;
    uint32_t nonFullMaskHi;
    uint32_t mixedMaskLo;
    uint32_t mixedMaskHi;
    uint32_t leafRefBase;
    uint32_t generation;
    uint32_t reserved0;
    uint32_t reserved1;
};
struct DualLeaf { uint32_t words[16]; };
struct FlowerOwnerEpoch {
    uint32_t kernelLocal;
    uint32_t epoch;
};
struct FlowerDetailRecord {
    uint32_t key;
    int32_t lower;
    int32_t upper;
    uint32_t parentEpoch;
};
struct FlowerSkinMetricRun {
    uint32_t flowerKey;
    uint32_t groupBase;
    uint32_t splitBitsLo;
    uint32_t splitBitsHi;
    uint32_t parentEpoch;
    uint32_t reserved;
};
struct FlowerVInterval {
    int32_t lower;
    int32_t upper;
};
struct FlowerVGroup {
    FlowerVInterval child[7];
};
struct ThreadRun {
    uint32_t flowerKey;
    uint32_t programRef;
    uint32_t groupBase;
    uint32_t splitBitsLo;
    uint32_t splitBitsHi;
    uint32_t parentEpoch;
};
struct ThreadColorInterval {
    uint32_t lowerLinearRgba[2];
    uint32_t upperLinearRgba[2];
};
struct ThreadColorGroup {
    ThreadColorInterval child[7];
};
struct ThreadProgramRecord {
    uint32_t flags;
    uint32_t reserved0;
    uint32_t reserved1;
    uint32_t reserved2;
    uint32_t opticalLower[2];
    uint32_t opticalUpper[2];
    uint32_t captureViewLower[2];
    uint32_t captureViewUpper[2];
};
struct FlowerSymbolKey {
    int32_t junction[3];
    uint32_t tag;
};
struct FlowerSymbolRecord {
    uint32_t ownerAndCarrier;
    uint32_t rootsAndWedges;
    uint32_t detailRef;
    uint32_t threadRef;
};
struct ObservationRecord {
    uint32_t tileAndKernel;
    uint32_t sourcePixel;
    uint32_t symbolTag;
    uint32_t precisionKey;
};
struct RecordHeader {
    uint32_t magic;
    uint16_t version;
    uint16_t kind;
    uint64_t commitGeneration;
    uint32_t addressBytes;
    uint32_t payloadBytes;
    uint32_t crc32;
};
struct TombstoneRecord {
    uint32_t targetKind;
    uint32_t localKey;
};
#pragma pack(pop)

static_assert(sizeof(KernelStateAbi) == 16u);
static_assert(sizeof(DualBlockMeta) == 8u);
static_assert(sizeof(DualBlockChildren) == 128u);
static_assert(sizeof(DualChunkPayload) == 32u);
static_assert(sizeof(DualLeaf) == 64u);
static_assert(sizeof(FlowerOwnerEpoch) == 8u);
static_assert(sizeof(FlowerDetailRecord) == 16u);
static_assert(sizeof(FlowerSkinMetricRun) == 24u);
static_assert(sizeof(FlowerVInterval) == 8u);
static_assert(sizeof(FlowerVGroup) == 56u);
static_assert(sizeof(ThreadRun) == 24u);
static_assert(sizeof(ThreadColorInterval) == 16u);
static_assert(sizeof(ThreadColorGroup) == 112u);
static_assert(sizeof(ThreadProgramRecord) == 48u);
static_assert(sizeof(FlowerSymbolKey) == 16u);
static_assert(sizeof(FlowerSymbolRecord) == 16u);
static_assert(sizeof(ObservationRecord) == 16u);
static_assert(sizeof(RecordHeader) == 28u);
static_assert(sizeof(TombstoneRecord) == 8u);
static_assert(offsetof(RecordHeader, commitGeneration) == 8u);
static_assert(offsetof(RecordHeader, crc32) == 24u);
}
