using System;
using System.Globalization;
using System.IO;
using System.Text;
using Unity.Mathematics;
using UnityEditor;
using UnityEngine;

namespace Genesis.RoomScan.Editor
{
    /// <summary>
    /// Emits the GPU half of the exact CPU Sphere-Flower oracle. All arrays are
    /// enumerated from MerkabaSphereFlowerAuthority; no topology is maintained
    /// independently in this generator.
    /// </summary>
    public static class MerkabaSphereFlowerCodegen
    {
        public const string GeneratedAssetPath =
            "Packages/com.genesis.roomscan/Runtime/Shaders/MerkabaSphereFlower.generated.hlsl";
        public const string GeneratedCsAssetPath =
            "Packages/com.genesis.roomscan/Runtime/Merkaba/MerkabaSphereFlower.generated.cs";
        public const string GeneratedDataAbiAssetPath =
            "Packages/com.genesis.roomscan/Runtime/Shaders/MerkabaSphereFlowerDataAbi.generated.hlsl";
        public const string GeneratedNativeDataAbiAssetPath =
            "Packages/com.genesis.roomscan/Runtime/Telemetry/Native/MerkabaSphereFlowerDataAbi.h";

        [MenuItem("Quest Infinite Scan/Merkaba/Regenerate Sphere-Flower HLSL")]
        public static void Regenerate()
        {
            WriteIfChanged(GeneratedAssetPath, BuildGeneratedHlsl());
            WriteIfChanged(GeneratedCsAssetPath, BuildGeneratedCs());
            WriteIfChanged(GeneratedDataAbiAssetPath, BuildGeneratedDataAbiHlsl());
            WriteIfChanged(GeneratedNativeDataAbiAssetPath,
                BuildGeneratedNativeDataAbi());
            Debug.Log("[SphereFlower] Generated exact CPU/HLSL tables.");
        }

        public static void GenerateForBatch() => Regenerate();

        public static void CheckForBatch()
        {
            CheckExact(GeneratedAssetPath, BuildGeneratedHlsl());
            CheckExact(GeneratedCsAssetPath, BuildGeneratedCs());
            CheckExact(GeneratedDataAbiAssetPath, BuildGeneratedDataAbiHlsl());
            CheckExact(GeneratedNativeDataAbiAssetPath,
                BuildGeneratedNativeDataAbi());
        }

        private static void WriteIfChanged(string assetPath, string expected)
        {
            string path = Path.GetFullPath(assetPath);
            if (File.Exists(path) && string.Equals(File.ReadAllText(path),
                    expected, StringComparison.Ordinal)) return;
            File.WriteAllText(path, expected);
            AssetDatabase.ImportAsset(assetPath,
                ImportAssetOptions.ForceSynchronousImport);
        }

        private static void CheckExact(string assetPath, string expected)
        {
            string path = Path.GetFullPath(assetPath);
            if (!File.Exists(path))
                throw new FileNotFoundException(
                    "Generated Sphere-Flower table is missing.", path);
            if (!string.Equals(File.ReadAllText(path), expected,
                    StringComparison.Ordinal))
                throw new InvalidDataException(
                    $"Generated Sphere-Flower table is stale: {assetPath}");
        }

        internal static string BuildGeneratedHlsl()
        {
            var output = new StringBuilder(48 * 1024);
            output.AppendLine("// GENERATED by MerkabaSphereFlowerCodegen. DO NOT EDIT.");
            output.AppendLine("// Exact finite tables from MerkabaSphereFlowerAuthority.");
            output.AppendLine("#ifndef GENESIS_MERKABA_SPHERE_FLOWER_INCLUDED");
            output.AppendLine("#define GENESIS_MERKABA_SPHERE_FLOWER_INCLUDED");
            Define(output, "M8_FLOWER_LATTICE_STEP",
                Number(MerkabaSphereFlowerAuthority.LatticeStep));
            Define(output, "M8_FLOWER_LEVEL_COUNT",
                MerkabaSphereFlowerAuthority.LevelCount + "u");
            Define(output, "M8_FLOWER_GEOMETRY_LEVEL_COUNT",
                MerkabaSphereFlowerAuthority.GeometryLevelCount + "u");
            Define(output, "M8_FLOWER_DIRECTION_COUNT",
                MerkabaSphereFlowerAuthority.DirectedRelationCount + "u");
            Define(output, "M8_FLOWER_LINE_CLASS_COUNT",
                MerkabaSphereFlowerAuthority.LineClassCount + "u");
            Define(output, "M8_FLOWER_NODE_CLASS_COUNT",
                MerkabaSphereFlowerAuthority.NodeClassCount + "u");
            Define(output, "M8_FLOWER_STRAND_CLASS_COUNT",
                MerkabaSphereFlowerAuthority.StrandClassCount + "u");
            Define(output, "M8_FLOWER_PETAL_CLASS_COUNT",
                MerkabaSphereFlowerAuthority.PetalClassCount + "u");
            Define(output, "M8_FLOWER_SKIN_SITE_COUNT",
                MerkabaSphereFlowerAuthority.SkinSiteCount + "u");
            Define(output, "M8_FLOWER_SKIN_CHAMBER_COUNT",
                MerkabaSphereFlowerAuthority.SkinChamberCount + "u");
            Define(output, "M8_FLOWER_SKIN_THREAD_COUNT",
                MerkabaSphereFlowerAuthority.SkinThreadPositionCount + "u");
            Define(output, "M8_FLOWER_SKIN_TERMINAL_COUNT",
                MerkabaSphereFlowerAuthority.SkinL5Count + "u");
            Define(output, "M8_FLOWER_SKIN_SPLIT_BIT_COUNT",
                MerkabaSphereFlowerAuthority.SkinSplitBitCount + "u");
            Define(output, "M8_FLOWER_SECTOR_BOUNDARY_COUNT",
                MerkabaSphereFlowerAuthority.SectorBoundaries.Length + "u");
            Define(output, "M8_FLOWER_TABLE_HASH",
                "0x" + MerkabaSphereFlowerAuthority.ComputeFrozenTableHash()
                    .ToString("x8", CultureInfo.InvariantCulture) + "u");
            Define(output, "M8_FLOWER_ROOT_IMPOSSIBLE", "0u");
            Define(output, "M8_FLOWER_ROOT_CERTAIN_TANGENT", "1u");
            Define(output, "M8_FLOWER_ROOT_CERTAIN_SECANT", "2u");
            Define(output, "M8_FLOWER_ROOT_COPLANAR", "3u");
            Define(output, "M8_FLOWER_ROOT_AMBIGUOUS", "4u");
            Define(output, "M8_FLOWER_GAMMA6_UPPER", Number(
                MerkabaSphereFlowerAuthority.FloatInterval.Enclose(
                    6.0 / (16777216.0 - 6.0)).Upper));
            Define(output, "M8_FLOWER_GAMMA7_UPPER", Number(
                MerkabaSphereFlowerAuthority.FloatInterval.Enclose(
                    7.0 / (16777216.0 - 7.0)).Upper));
            Define(output, "M8_FLOWER_SKIN_UNIFORM", "0u");
            Define(output, "M8_FLOWER_SKIN_SPLIT", "1u");
            Define(output, "M8_FLOWER_SKIN_AMBIGUOUS", "2u");
            output.AppendLine();

            AppendLines(output);
            AppendDirections(output);
            AppendNodes(output);
            AppendStrands(output);
            AppendPetals(output);
            AppendChildren(output);
            AppendSkin(output);
            AppendSectors(output);
            AppendTetraFrames(output);
            AppendFunctions(output);
            output.AppendLine("#endif");
            return output.ToString();
        }

        internal static string BuildGeneratedCs()
        {
            var o = new StringBuilder(48 * 1024);
            o.AppendLine("// GENERATED by MerkabaSphereFlowerCodegen. DO NOT EDIT.");
            o.AppendLine("using Unity.Mathematics;");
            o.AppendLine();
            o.AppendLine("namespace Genesis.RoomScan");
            o.AppendLine("{");
            o.AppendLine("    public static partial class MerkabaSphereFlowerAuthority");
            o.AppendLine("    {");
            o.Append("        internal const uint FrozenTableHash = 0x")
                .Append(MerkabaSphereFlowerAuthority.ComputeFrozenTableHash()
                    .ToString("x8", CultureInfo.InvariantCulture))
                .AppendLine("u;");
            o.AppendLine();
            o.AppendLine("        private static void LoadGeneratedTables(");
            o.AppendLine("            out LineRule[] lines, out DirectionRule[] directions,");
            o.AppendLine("            out NodeRule[] nodes, out StrandRule[] strands,");
            o.AppendLine("            out PetalRule[] petals, out SectorBoundary[] sectors,");
            o.AppendLine("            out TetraFrameRule[] tetraFrames)");
            o.AppendLine("        {");
            AppendGeneratedCsLines(o);
            AppendGeneratedCsDirections(o);
            AppendGeneratedCsNodes(o);
            AppendGeneratedCsStrands(o);
            AppendGeneratedCsPetals(o);
            AppendGeneratedCsSectors(o);
            AppendGeneratedCsTetra(o);
            o.AppendLine("        }");
            AppendGeneratedCsSkin(o);
            o.AppendLine("    }");
            o.AppendLine("}");
            return o.ToString();
        }

        internal static string BuildGeneratedDataAbiHlsl()
        {
            var o = new StringBuilder(16 * 1024);
            o.AppendLine("// GENERATED by MerkabaSphereFlowerCodegen. DO NOT EDIT.");
            o.AppendLine("// Packed REV-C subordinate data ABI; no resources are declared here.");
            o.AppendLine("#ifndef GENESIS_MERKABA_SPHERE_FLOWER_DATA_ABI_INCLUDED");
            o.AppendLine("#define GENESIS_MERKABA_SPHERE_FLOWER_DATA_ABI_INCLUDED");
            Define(o, "M8_FLOWER_DATA_ABI_VERSION",
                MerkabaSphereFlowerDataAbi.SchemaVersion + "u");
            Define(o, "M8_FLOWER_OBSERVATION_RECORD_CAPACITY",
                MerkabaObservationRecord.Capacity + "u");
            Define(o, "M8_FLOWER_OBSERVATION_SOURCE_CAPACITY",
                MerkabaObservationRecord.MaximumSourcePixels + "u");
            Define(o, "M8_FLOWER_R1_SEED_FLAG", "0x" +
                MerkabaSphereFlowerDataAbi.R1SeedFlag.ToString("x8",
                    CultureInfo.InvariantCulture) + "u");
            Define(o, "M8_FLOWER_DETAIL_LEVEL_SHIFT",
                MerkabaFlowerDetailKey.GeometryLevelShift + "u");
            Define(o, "M8_FLOWER_DETAIL_CHILD_PATH_SHIFT",
                MerkabaFlowerDetailKey.GeometryChildPathShift + "u");
            Define(o, "M8_FLOWER_DETAIL_PETAL_SHIFT",
                MerkabaFlowerDetailKey.PetalClassShift + "u");
            Define(o, "M8_FLOWER_DETAIL_CHANNEL_SHIFT",
                MerkabaFlowerDetailKey.ChannelShift + "u");
            Define(o, "M8_FLOWER_DETAIL_KIND_SHIFT",
                MerkabaFlowerDetailKey.KindShift + "u");
            Define(o, "M8_FLOWER_DETAIL_ROOT_SHIFT",
                MerkabaFlowerDetailKey.RootSignShift + "u");
            Define(o, "M8_FLOWER_DETAIL_SECTOR_SHIFT",
                MerkabaFlowerDetailKey.SectorShift + "u");
            Define(o, "M8_FLOWER_L2_KEY_PETAL_SHIFT",
                MerkabaFlowerL2Key.PetalClassShift + "u");
            Define(o, "M8_FLOWER_L2_KEY_ROOT_SHIFT",
                MerkabaFlowerL2Key.RootSignShift + "u");
            Define(o, "M8_FLOWER_L2_KEY_SECTOR_SHIFT",
                MerkabaFlowerL2Key.SectorShift + "u");
            Define(o, "M8_FLOWER_SKIN_SPLIT_HIGH_MASK", "0x" +
                MerkabaFlowerSkinSplitBits.HighValidMask.ToString("x8",
                    CultureInfo.InvariantCulture) + "u");
            Define(o, "M8_FLOWER_SYMBOL_LINE_SHIFT",
                MerkabaFlowerSymbolTag.LineClassShift + "u");
            Define(o, "M8_FLOWER_SYMBOL_ROOT_SHIFT",
                MerkabaFlowerSymbolTag.RootSignShift + "u");
            Define(o, "M8_FLOWER_SYMBOL_SECTOR_SHIFT",
                MerkabaFlowerSymbolTag.SectorShift + "u");
            Define(o, "M8_FLOWER_SYMBOL_ENDPOINT_SHIFT",
                MerkabaFlowerSymbolTag.EndpointOrientationShift + "u");
            Define(o, "M8_FLOWER_SYMBOL_SHELL_SHIFT",
                MerkabaFlowerSymbolTag.ShellValidityShift + "u");
            Define(o, "M8_FLOWER_SYMBOL_STATUS_SHIFT",
                MerkabaFlowerSymbolTag.StatusShift + "u");
            Define(o, "M8_FLOWER_SYMBOL_SCRATCH_SHIFT",
                MerkabaFlowerSymbolTag.ScratchShift + "u");
            o.AppendLine();
            o.AppendLine("struct M8DualBlockMeta { uint StateAndGeneration; uint PayloadIndex; };");
            AppendHlslWordStruct(o, "M8DualBlockChildren", 32);
            o.AppendLine("struct M8DualChunkPayload { uint NonFullMaskLo; uint NonFullMaskHi; uint MixedMaskLo; uint MixedMaskHi; uint LeafRefBase; uint Generation; uint Reserved0; uint Reserved1; };");
            AppendHlslWordStruct(o, "M8DualLeaf", 16);
            o.AppendLine("struct M8FlowerOwnerEpoch { uint KernelLocal; uint Epoch; };");
            o.AppendLine("struct M8FlowerDetailRecord { uint Key; int Lower; int Upper; uint ParentEpoch; };");
            o.AppendLine("struct M8FlowerSkinMetricRun { uint FlowerKey; uint GroupBase; uint SplitBitsLo; uint SplitBitsHi; uint ParentEpoch; uint Reserved; };");
            o.AppendLine("struct M8FlowerVInterval { int Lower; int Upper; };");
            o.AppendLine("struct M8FlowerVGroup { M8FlowerVInterval Child[7]; };");
            o.AppendLine("struct M8ThreadRun { uint FlowerKey; uint ProgramRef; uint GroupBase; uint SplitBitsLo; uint SplitBitsHi; uint ParentEpoch; };");
            o.AppendLine("struct M8ThreadColorInterval { uint2 LowerLinearRgba; uint2 UpperLinearRgba; };");
            o.AppendLine("struct M8ThreadColorGroup { M8ThreadColorInterval Child[7]; };");
            o.AppendLine("struct M8ThreadProgramRecord { uint Flags; uint Reserved0; uint Reserved1; uint Reserved2; uint2 OpticalLower; uint2 OpticalUpper; uint2 CaptureViewLower; uint2 CaptureViewUpper; };");
            o.AppendLine("struct M8FlowerSymbolKey { int3 Junction; uint Tag; };");
            o.AppendLine("struct M8ObservationRecord { uint TileAndKernel; uint SourcePixel; uint SymbolTag; uint PrecisionKey; };");
            o.AppendLine();
            o.AppendLine(@"uint M8FlowerPackDetailKey(uint level, uint childPath,
    uint petalClass, uint channel, uint kind, bool rootSign, uint sector)
{
    return level | (childPath << M8_FLOWER_DETAIL_CHILD_PATH_SHIFT) |
        (petalClass << M8_FLOWER_DETAIL_PETAL_SHIFT) |
        (channel << M8_FLOWER_DETAIL_CHANNEL_SHIFT) |
        (kind << M8_FLOWER_DETAIL_KIND_SHIFT) |
        (rootSign ? (1u << M8_FLOWER_DETAIL_ROOT_SHIFT) : 0u) |
        (sector << M8_FLOWER_DETAIL_SECTOR_SHIFT);
}

uint M8FlowerPackL2Key(uint geometryChildPath, uint petalClass,
    bool rootSign, uint sector)
{
    return geometryChildPath |
        (petalClass << M8_FLOWER_L2_KEY_PETAL_SHIFT) |
        (rootSign ? (1u << M8_FLOWER_L2_KEY_ROOT_SHIFT) : 0u) |
        (sector << M8_FLOWER_L2_KEY_SECTOR_SHIFT);
}

uint M8FlowerPackSymbolTag(uint level, uint lineClass, bool rootSign,
    uint sector, bool endpointOrientation, uint shellValidity,
    uint status, uint scratch)
{
    return level | (lineClass << M8_FLOWER_SYMBOL_LINE_SHIFT) |
        (rootSign ? (1u << M8_FLOWER_SYMBOL_ROOT_SHIFT) : 0u) |
        (sector << M8_FLOWER_SYMBOL_SECTOR_SHIFT) |
        (endpointOrientation ? (1u << M8_FLOWER_SYMBOL_ENDPOINT_SHIFT) : 0u) |
        (shellValidity << M8_FLOWER_SYMBOL_SHELL_SHIFT) |
        (status << M8_FLOWER_SYMBOL_STATUS_SHIFT) |
        (scratch << M8_FLOWER_SYMBOL_SCRATCH_SHIFT);
}");
            o.AppendLine("#endif");
            return o.ToString();
        }

        internal static string BuildGeneratedNativeDataAbi()
        {
            var o = new StringBuilder(16 * 1024);
            o.AppendLine("// GENERATED by MerkabaSphereFlowerCodegen. DO NOT EDIT.");
            o.AppendLine("#pragma once");
            o.AppendLine("#include <cstddef>");
            o.AppendLine("#include <cstdint>");
            o.AppendLine();
            o.AppendLine("namespace genesis::sphere_flower_abi");
            o.AppendLine("{");
            o.AppendLine("constexpr uint32_t kSchemaVersion = " +
                MerkabaSphereFlowerDataAbi.SchemaVersion + "u;");
            o.AppendLine("constexpr uint32_t kR1SeedFlag = 0x" +
                MerkabaSphereFlowerDataAbi.R1SeedFlag.ToString("x8",
                    CultureInfo.InvariantCulture) + "u;");
            o.AppendLine("#pragma pack(push, 4)");
            AppendNativeStruct(o, "KernelStateAbi", new[]
                { "int32_t occupancyEvidence", "uint32_t packedColor",
                  "uint32_t colorConfidence", "uint32_t flags" });
            AppendNativeStruct(o, "DualBlockMeta", new[]
                { "uint32_t stateAndGeneration", "uint32_t payloadIndex" });
            AppendNativeArrayStruct(o, "DualBlockChildren", 32);
            AppendNativeStruct(o, "DualChunkPayload", new[]
                { "uint32_t nonFullMaskLo", "uint32_t nonFullMaskHi",
                  "uint32_t mixedMaskLo", "uint32_t mixedMaskHi",
                  "uint32_t leafRefBase", "uint32_t generation",
                  "uint32_t reserved0", "uint32_t reserved1" });
            AppendNativeArrayStruct(o, "DualLeaf", 16);
            AppendNativeStruct(o, "FlowerOwnerEpoch", new[]
                { "uint32_t kernelLocal", "uint32_t epoch" });
            AppendNativeStruct(o, "FlowerDetailRecord", new[]
                { "uint32_t key", "int32_t lower", "int32_t upper",
                  "uint32_t parentEpoch" });
            AppendNativeStruct(o, "FlowerSkinMetricRun", new[]
                { "uint32_t flowerKey", "uint32_t groupBase",
                  "uint32_t splitBitsLo", "uint32_t splitBitsHi",
                  "uint32_t parentEpoch", "uint32_t reserved" });
            AppendNativeStruct(o, "FlowerVInterval", new[]
                { "int32_t lower", "int32_t upper" });
            AppendNativeStruct(o, "FlowerVGroup", new[]
                { "FlowerVInterval child[7]" });
            AppendNativeStruct(o, "ThreadRun", new[]
                { "uint32_t flowerKey", "uint32_t programRef",
                  "uint32_t groupBase", "uint32_t splitBitsLo",
                  "uint32_t splitBitsHi", "uint32_t parentEpoch" });
            AppendNativeStruct(o, "ThreadColorInterval", new[]
                { "uint32_t lowerLinearRgba[2]",
                  "uint32_t upperLinearRgba[2]" });
            AppendNativeStruct(o, "ThreadColorGroup", new[]
                { "ThreadColorInterval child[7]" });
            AppendNativeStruct(o, "ThreadProgramRecord", new[]
                { "uint32_t flags", "uint32_t reserved0",
                  "uint32_t reserved1", "uint32_t reserved2",
                  "uint32_t opticalLower[2]", "uint32_t opticalUpper[2]",
                  "uint32_t captureViewLower[2]",
                  "uint32_t captureViewUpper[2]" });
            AppendNativeStruct(o, "FlowerSymbolKey", new[]
                { "int32_t junction[3]", "uint32_t tag" });
            AppendNativeStruct(o, "ObservationRecord", new[]
                { "uint32_t tileAndKernel", "uint32_t sourcePixel",
                  "uint32_t symbolTag", "uint32_t precisionKey" });
            AppendNativeStruct(o, "RecordHeader", new[]
                { "uint32_t magic", "uint16_t version", "uint16_t kind",
                  "uint64_t commitGeneration", "uint32_t addressBytes",
                  "uint32_t payloadBytes", "uint32_t crc32" });
            AppendNativeStruct(o, "TombstoneRecord", new[]
                { "uint32_t targetKind", "uint32_t localKey" });
            o.AppendLine("#pragma pack(pop)");
            o.AppendLine();
            AppendNativeSizeAssert(o, "KernelStateAbi",
                MerkabaSphereFlowerDataAbi.KernelStateStride);
            AppendNativeSizeAssert(o, "DualBlockMeta",
                MerkabaDualBlockMeta.ByteSize);
            AppendNativeSizeAssert(o, "DualBlockChildren",
                MerkabaDualBlockChildren.ByteSize);
            AppendNativeSizeAssert(o, "DualChunkPayload",
                MerkabaDualChunkPayload.ByteSize);
            AppendNativeSizeAssert(o, "DualLeaf", MerkabaDualLeaf.ByteSize);
            AppendNativeSizeAssert(o, "FlowerOwnerEpoch",
                MerkabaFlowerOwnerEpoch.ByteSize);
            AppendNativeSizeAssert(o, "FlowerDetailRecord",
                MerkabaFlowerDetailRecord.ByteSize);
            AppendNativeSizeAssert(o, "FlowerSkinMetricRun",
                MerkabaFlowerSkinMetricRun.ByteSize);
            AppendNativeSizeAssert(o, "FlowerVInterval",
                MerkabaFlowerVInterval.ByteSize);
            AppendNativeSizeAssert(o, "FlowerVGroup",
                MerkabaFlowerVGroup.ByteSize);
            AppendNativeSizeAssert(o, "ThreadRun", MerkabaThreadRun.ByteSize);
            AppendNativeSizeAssert(o, "ThreadColorInterval",
                MerkabaThreadColorInterval.ByteSize);
            AppendNativeSizeAssert(o, "ThreadColorGroup",
                MerkabaThreadColorGroup.ByteSize);
            AppendNativeSizeAssert(o, "ThreadProgramRecord",
                MerkabaThreadProgramRecord.ByteSize);
            AppendNativeSizeAssert(o, "FlowerSymbolKey",
                MerkabaFlowerSymbolKey.ByteSize);
            AppendNativeSizeAssert(o, "ObservationRecord",
                MerkabaObservationRecord.ByteSize);
            AppendNativeSizeAssert(o, "RecordHeader",
                MerkabaRecordHeader.ByteSize);
            AppendNativeSizeAssert(o, "TombstoneRecord",
                MerkabaTombstoneRecord.ByteSize);
            o.AppendLine("static_assert(offsetof(RecordHeader, commitGeneration) == 8u);");
            o.AppendLine("static_assert(offsetof(RecordHeader, crc32) == 24u);");
            o.AppendLine("}");
            return o.ToString();
        }

        private static void AppendGeneratedCsLines(StringBuilder o)
        {
            o.AppendLine("            lines = new LineRule[]");
            o.AppendLine("            {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.Lines.Length; i++)
            {
                var x = MerkabaSphereFlowerAuthority.Lines[i];
                o.Append("                new LineRule(").Append(CsInt3(x.Direction))
                    .Append(", (Shell)").Append((int)x.Shell).Append(", ")
                    .Append(CsFloat3(x.UnitDirection)).Append(", ")
                    .Append(CsFloat3(x.E1)).Append(", ")
                    .Append(CsFloat3(x.E2)).Append(", ")
                    .Append(x.SectorOffset).Append(", ")
                    .Append(x.SectorCount).Append(')');
                Comma(o, i, MerkabaSphereFlowerAuthority.Lines.Length);
            }
            o.AppendLine("            };");
        }

        private static void AppendGeneratedCsDirections(StringBuilder o)
        {
            o.AppendLine("            directions = new DirectionRule[]");
            o.AppendLine("            {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.Directions.Length; i++)
            {
                var x = MerkabaSphereFlowerAuthority.Directions[i];
                o.Append("                new DirectionRule(")
                    .Append(CsInt3(x.Direction)).Append(", ")
                    .Append(x.LineClass).Append(", ")
                    .Append(x.Orientation).Append(", (Shell)")
                    .Append((int)x.Shell).Append(')');
                Comma(o, i, MerkabaSphereFlowerAuthority.Directions.Length);
            }
            o.AppendLine("            };");
        }

        private static void AppendGeneratedCsNodes(StringBuilder o)
        {
            o.AppendLine("            nodes = new NodeRule[]");
            o.AppendLine("            {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.Directions.Length; i++)
            {
                o.Append("                new NodeRule(directions[").Append(i)
                    .Append("])");
                Comma(o, i, MerkabaSphereFlowerAuthority.Directions.Length);
            }
            o.AppendLine("            };");
        }

        private static void AppendGeneratedCsStrands(StringBuilder o)
        {
            o.AppendLine("            strands = new StrandRule[]");
            o.AppendLine("            {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.Strands.Length; i++)
            {
                var x = MerkabaSphereFlowerAuthority.Strands[i];
                o.Append("                new StrandRule(").Append(x.Node0)
                    .Append(", ").Append(x.Node1).Append(", ")
                    .Append(x.IncidenceKind).Append(", ").Append(x.Petal0)
                    .Append(", ").Append(x.Petal1).Append(')');
                Comma(o, i, MerkabaSphereFlowerAuthority.Strands.Length);
            }
            o.AppendLine("            };");
        }

        private static void AppendGeneratedCsPetals(StringBuilder o)
        {
            o.AppendLine("            petals = new PetalRule[]");
            o.AppendLine("            {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.Petals.Length; i++)
            {
                var x = MerkabaSphereFlowerAuthority.Petals[i];
                o.Append("                new PetalRule(").Append(x.FaceNode)
                    .Append(", ").Append(x.EdgeNode).Append(", ")
                    .Append(x.CornerNode).Append(", ").Append(x.Strand0)
                    .Append(", ").Append(x.Strand1).Append(", ")
                    .Append(x.Strand2).Append(", ").Append(x.Orientation)
                    .Append(", ").Append(x.StrandSign0)
                    .Append(", ").Append(x.StrandSign1)
                    .Append(", ").Append(x.StrandSign2)
                    .Append(')');
                Comma(o, i, MerkabaSphereFlowerAuthority.Petals.Length);
            }
            o.AppendLine("            };");
        }

        private static void AppendGeneratedCsSectors(StringBuilder o)
        {
            o.AppendLine("            sectors = new SectorBoundary[]");
            o.AppendLine("            {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.SectorBoundaries.Length; i++)
            {
                var x = MerkabaSphereFlowerAuthority.SectorBoundaries[i];
                o.Append("                new SectorBoundary(")
                    .Append(CsFloat2(x.Unit)).Append(", new Interval2(")
                    .Append(CsInterval(x.Enclosure.X)).Append(", ")
                    .Append(CsInterval(x.Enclosure.Y)).Append("))");
                Comma(o, i, MerkabaSphereFlowerAuthority.SectorBoundaries.Length);
            }
            o.AppendLine("            };");
        }

        private static void AppendGeneratedCsTetra(StringBuilder o)
        {
            o.AppendLine("            tetraFrames = new TetraFrameRule[]");
            o.AppendLine("            {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.TetraFrames.Length; i++)
            {
                var x = MerkabaSphereFlowerAuthority.TetraFrames[i];
                o.Append("                new TetraFrameRule(")
                    .Append(CsInt4(x.LineClasses)).Append(", ")
                    .Append(CsInt4(x.Eta)).Append(", ")
                    .Append(x.Chirality).Append(')');
                Comma(o, i, MerkabaSphereFlowerAuthority.TetraFrames.Length);
            }
            o.AppendLine("            };");
        }

        private static void AppendGeneratedCsSkin(StringBuilder o)
        {
            o.AppendLine();
            o.AppendLine("        private static void LoadGeneratedSkinTables(");
            o.AppendLine("            out SkinChamberRule[] chambers,");
            o.AppendLine("            out ushort[] canonicalToThread,");
            o.AppendLine("            out ushort[] threadToCanonical,");
            o.AppendLine("            out ushort[] canonicalL5ToThread,");
            o.AppendLine("            out byte[] l3ChildRank, out byte[] l3State,");
            o.AppendLine("            out byte[] l4ParentThread,");
            o.AppendLine("            out byte[] l4ChildRank, out byte[] l4State,");
            o.AppendLine("            out byte[] l5ChildRank)");
            o.AppendLine("        {");
            o.AppendLine("            chambers = new SkinChamberRule[]");
            o.AppendLine("            {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.SkinChambers.Length;
                 i++)
            {
                var x = MerkabaSphereFlowerAuthority.SkinChambers[i];
                o.Append("                new SkinChamberRule(")
                    .Append(x.High).Append(", ").Append(x.Middle).Append(", ")
                    .Append(x.Low).Append(", ").Append(x.ChildSite).Append(", ")
                    .Append(x.ChildWedge).Append(", ")
                    .Append(x.NextStitchState).Append(", ")
                    .Append(x.Orientation).Append(')');
                Comma(o, i, MerkabaSphereFlowerAuthority.SkinChambers.Length);
            }
            o.AppendLine("            };");
            AppendGeneratedCsArray(o, "canonicalToThread", "ushort",
                MerkabaSphereFlowerAuthority.SkinCanonicalToThread);
            AppendGeneratedCsArray(o, "threadToCanonical", "ushort",
                MerkabaSphereFlowerAuthority.SkinThreadToCanonical);
            AppendGeneratedCsArray(o, "canonicalL5ToThread", "ushort",
                MerkabaSphereFlowerAuthority.SkinCanonicalL5ToThread);
            AppendGeneratedCsArray(o, "l3ChildRank", "byte",
                MerkabaSphereFlowerAuthority.SkinL3ChildRank);
            AppendGeneratedCsArray(o, "l3State", "byte",
                MerkabaSphereFlowerAuthority.SkinL3State);
            AppendGeneratedCsArray(o, "l4ParentThread", "byte",
                MerkabaSphereFlowerAuthority.SkinL4ParentThread);
            AppendGeneratedCsArray(o, "l4ChildRank", "byte",
                MerkabaSphereFlowerAuthority.SkinL4ChildRank);
            AppendGeneratedCsArray(o, "l4State", "byte",
                MerkabaSphereFlowerAuthority.SkinL4State);
            AppendGeneratedCsArray(o, "l5ChildRank", "byte",
                MerkabaSphereFlowerAuthority.SkinL5ChildRank);
            o.AppendLine("        }");
        }

        private static void AppendGeneratedCsArray<T>(StringBuilder o,
            string name, string elementType, ReadOnlySpan<T> values)
            where T : struct
        {
            o.Append("            ").Append(name).Append(" = new ")
                .Append(elementType).AppendLine("[]");
            o.AppendLine("            {");
            for (int i = 0; i < values.Length; i++)
            {
                o.Append("                ").Append(values[i]);
                Comma(o, i, values.Length);
            }
            o.AppendLine("            };");
        }

        private static void AppendLines(StringBuilder output)
        {
            output.AppendLine("static const int3 M8FlowerLineDirection[13] = {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.Lines.Length; i++)
            {
                var line = MerkabaSphereFlowerAuthority.Lines[i];
                output.Append("    ").Append(Int3(line.Direction));
                Comma(output, i, MerkabaSphereFlowerAuthority.Lines.Length);
            }
            output.AppendLine("};");
            output.AppendLine("static const float3 M8FlowerLineUnit[13] = {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.Lines.Length; i++)
            {
                output.Append("    ").Append(Float3(
                    MerkabaSphereFlowerAuthority.Lines[i].UnitDirection));
                Comma(output, i, MerkabaSphereFlowerAuthority.Lines.Length);
            }
            output.AppendLine("};");
            output.AppendLine("static const float3 M8FlowerLineE1[13] = {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.Lines.Length; i++)
            {
                output.Append("    ").Append(Float3(
                    MerkabaSphereFlowerAuthority.Lines[i].E1));
                Comma(output, i, MerkabaSphereFlowerAuthority.Lines.Length);
            }
            output.AppendLine("};");
            output.AppendLine("static const float3 M8FlowerLineE2[13] = {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.Lines.Length; i++)
            {
                output.Append("    ").Append(Float3(
                    MerkabaSphereFlowerAuthority.Lines[i].E2));
                Comma(output, i, MerkabaSphereFlowerAuthority.Lines.Length);
            }
            output.AppendLine("};");
            output.AppendLine("static const uint3 M8FlowerLineMeta[13] = {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.Lines.Length; i++)
            {
                var line = MerkabaSphereFlowerAuthority.Lines[i];
                output.Append("    uint3(").Append((uint)line.Shell).Append("u, ")
                    .Append(line.SectorOffset).Append("u, ")
                    .Append(line.SectorCount).Append("u)");
                Comma(output, i, MerkabaSphereFlowerAuthority.Lines.Length);
            }
            output.AppendLine("};");
        }

        private static void AppendDirections(StringBuilder output)
        {
            output.AppendLine("static const int4 M8FlowerDirection[26] = {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.Directions.Length; i++)
            {
                var value = MerkabaSphereFlowerAuthority.Directions[i];
                output.Append("    int4(").Append(value.Direction.x).Append(", ")
                    .Append(value.Direction.y).Append(", ")
                    .Append(value.Direction.z).Append(", ")
                    .Append(value.LineClass).Append(")");
                Comma(output, i, MerkabaSphereFlowerAuthority.Directions.Length);
            }
            output.AppendLine("};");
            output.AppendLine("static const int2 M8FlowerDirectionMeta[26] = {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.Directions.Length; i++)
            {
                var value = MerkabaSphereFlowerAuthority.Directions[i];
                output.Append("    int2(").Append(value.Orientation).Append(", ")
                    .Append((int)value.Shell).Append(")");
                Comma(output, i, MerkabaSphereFlowerAuthority.Directions.Length);
            }
            output.AppendLine("};");
        }

        private static void AppendNodes(StringBuilder output)
        {
            output.AppendLine("static const int4 M8FlowerNode[26] = {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.Nodes.Length; i++)
            {
                var value = MerkabaSphereFlowerAuthority.Nodes[i];
                output.Append("    int4(").Append(value.Direction.x).Append(", ")
                    .Append(value.Direction.y).Append(", ")
                    .Append(value.Direction.z).Append(", ")
                    .Append(value.LineClass).Append(")");
                Comma(output, i, MerkabaSphereFlowerAuthority.Nodes.Length);
            }
            output.AppendLine("};");
        }

        private static void AppendStrands(StringBuilder output)
        {
            output.AppendLine("static const uint4 M8FlowerStrand[72] = {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.Strands.Length; i++)
            {
                var value = MerkabaSphereFlowerAuthority.Strands[i];
                uint petals = (uint)(value.Petal0 | (value.Petal1 << 8));
                output.Append("    uint4(").Append(value.Node0).Append("u, ")
                    .Append(value.Node1).Append("u, ")
                    .Append(value.IncidenceKind).Append("u, ")
                    .Append(petals).Append("u)");
                Comma(output, i, MerkabaSphereFlowerAuthority.Strands.Length);
            }
            output.AppendLine("};");
        }

        private static void AppendPetals(StringBuilder output)
        {
            output.AppendLine("static const uint4 M8FlowerPetalNodes[48] = {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.Petals.Length; i++)
            {
                var p = MerkabaSphereFlowerAuthority.Petals[i];
                output.Append("    uint4(").Append(p.FaceNode).Append("u, ")
                    .Append(p.EdgeNode).Append("u, ")
                    .Append(p.CornerNode).Append("u, ")
                    .Append(p.Orientation > 0 ? "1u" : "0u").Append(")");
                Comma(output, i, MerkabaSphereFlowerAuthority.Petals.Length);
            }
            output.AppendLine("};");
            output.AppendLine("static const uint3 M8FlowerPetalStrands[48] = {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.Petals.Length; i++)
            {
                var p = MerkabaSphereFlowerAuthority.Petals[i];
                output.Append("    uint3(").Append(p.Strand0).Append("u, ")
                    .Append(p.Strand1).Append("u, ")
                    .Append(p.Strand2).Append("u)");
                Comma(output, i, MerkabaSphereFlowerAuthority.Petals.Length);
            }
            output.AppendLine("};");
            output.AppendLine("static const int3 M8FlowerPetalStrandSign[48] = {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.Petals.Length; i++)
            {
                var p = MerkabaSphereFlowerAuthority.Petals[i];
                output.Append("    int3(").Append(p.StrandSign0).Append(", ")
                    .Append(p.StrandSign1).Append(", ")
                    .Append(p.StrandSign2).Append(")");
                Comma(output, i, MerkabaSphereFlowerAuthority.Petals.Length);
            }
            output.AppendLine("};");
        }

        private static void AppendChildren(StringBuilder output)
        {
            output.AppendLine("static const uint3 M8FlowerChildPetal[4] = {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.ChildPetals.Length; i++)
            {
                var c = MerkabaSphereFlowerAuthority.ChildPetals[i];
                output.Append("    uint3(").Append(c.Vertex0).Append("u, ")
                    .Append(c.Vertex1).Append("u, ")
                    .Append(c.Vertex2).Append("u)");
                Comma(output, i, MerkabaSphereFlowerAuthority.ChildPetals.Length);
            }
            output.AppendLine("};");
        }

        private static void AppendSkin(StringBuilder output)
        {
            output.AppendLine("static const int4 M8FlowerSkinChamber[36] = {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.SkinChambers.Length;
                 i++)
            {
                var value = MerkabaSphereFlowerAuthority.SkinChambers[i];
                uint packed = (uint)(value.ChildSite |
                    (value.ChildWedge << 8) |
                    (value.NextStitchState << 16) |
                    ((value.Orientation > 0 ? 1 : 0) << 24));
                output.Append("    int4(").Append(value.High).Append(", ")
                    .Append(value.Middle).Append(", ").Append(value.Low)
                    .Append(", ").Append(packed).Append(')');
                Comma(output, i,
                    MerkabaSphereFlowerAuthority.SkinChambers.Length);
            }
            output.AppendLine("};");
            AppendUshortTable(output, "M8FlowerSkinCanonicalToThread",
                MerkabaSphereFlowerAuthority.SkinCanonicalToThread);
            AppendUshortTable(output, "M8FlowerSkinThreadToCanonical",
                MerkabaSphereFlowerAuthority.SkinThreadToCanonical);
            AppendUshortTable(output, "M8FlowerSkinCanonicalL5ToThread",
                MerkabaSphereFlowerAuthority.SkinCanonicalL5ToThread);
            AppendByteTable(output, "M8FlowerSkinL3ChildRank",
                MerkabaSphereFlowerAuthority.SkinL3ChildRank);
            AppendByteTable(output, "M8FlowerSkinL3State",
                MerkabaSphereFlowerAuthority.SkinL3State);
            AppendByteTable(output, "M8FlowerSkinL4ParentThread",
                MerkabaSphereFlowerAuthority.SkinL4ParentThread);
            AppendByteTable(output, "M8FlowerSkinL4ChildRank",
                MerkabaSphereFlowerAuthority.SkinL4ChildRank);
            AppendByteTable(output, "M8FlowerSkinL4State",
                MerkabaSphereFlowerAuthority.SkinL4State);
            AppendByteTable(output, "M8FlowerSkinL5ChildRank",
                MerkabaSphereFlowerAuthority.SkinL5ChildRank);
        }

        private static void AppendUshortTable(StringBuilder output,
            string name, ReadOnlySpan<ushort> values)
        {
            output.Append("static const uint ").Append(name).Append('[')
                .Append(values.Length).AppendLine("] = {");
            for (int i = 0; i < values.Length; i++)
            {
                output.Append("    ").Append(values[i]).Append('u');
                Comma(output, i, values.Length);
            }
            output.AppendLine("};");
        }

        private static void AppendByteTable(StringBuilder output,
            string name, ReadOnlySpan<byte> values)
        {
            output.Append("static const uint ").Append(name).Append('[')
                .Append(values.Length).AppendLine("] = {");
            for (int i = 0; i < values.Length; i++)
            {
                output.Append("    ").Append(values[i]).Append('u');
                Comma(output, i, values.Length);
            }
            output.AppendLine("};");
        }

        private static void AppendSectors(StringBuilder output)
        {
            int count = MerkabaSphereFlowerAuthority.SectorBoundaries.Length;
            output.Append("static const float4 M8FlowerSectorBounds[")
                .Append(count).AppendLine("] = {");
            for (int i = 0; i < count; i++)
            {
                var b = MerkabaSphereFlowerAuthority.SectorBoundaries[i];
                output.Append("    float4(")
                    .Append(Number(b.Enclosure.X.Lower)).Append(", ")
                    .Append(Number(b.Enclosure.X.Upper)).Append(", ")
                    .Append(Number(b.Enclosure.Y.Lower)).Append(", ")
                    .Append(Number(b.Enclosure.Y.Upper)).Append(")");
                Comma(output, i, count);
            }
            output.AppendLine("};");
            output.Append("static const float2 M8FlowerSectorUnit[")
                .Append(count).AppendLine("] = {");
            for (int i = 0; i < count; i++)
            {
                output.Append("    ").Append(Float2(
                    MerkabaSphereFlowerAuthority.SectorBoundaries[i].Unit));
                Comma(output, i, count);
            }
            output.AppendLine("};");
        }

        private static void AppendTetraFrames(StringBuilder output)
        {
            output.AppendLine("static const int4 M8FlowerTetraLine[8] = {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.TetraFrames.Length; i++)
            {
                output.Append("    ").Append(Int4(
                    MerkabaSphereFlowerAuthority.TetraFrames[i].LineClasses));
                Comma(output, i, MerkabaSphereFlowerAuthority.TetraFrames.Length);
            }
            output.AppendLine("};");
            output.AppendLine("static const int4 M8FlowerTetraEta[8] = {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.TetraFrames.Length; i++)
            {
                output.Append("    ").Append(Int4(
                    MerkabaSphereFlowerAuthority.TetraFrames[i].Eta));
                Comma(output, i, MerkabaSphereFlowerAuthority.TetraFrames.Length);
            }
            output.AppendLine("};");
            output.AppendLine("static const int M8FlowerTetraChirality[8] = {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.TetraFrames.Length; i++)
            {
                output.Append("    ")
                    .Append(MerkabaSphereFlowerAuthority.TetraFrames[i].Chirality);
                Comma(output, i, MerkabaSphereFlowerAuthority.TetraFrames.Length);
            }
            output.AppendLine("};");
            output.AppendLine("static const float3 M8FlowerTetraAxis[4] = {");
            output.AppendLine("    float3(0.5773502691896258, 0.5773502691896258, 0.5773502691896258),");
            output.AppendLine("    float3(0.5773502691896258, -0.5773502691896258, -0.5773502691896258),");
            output.AppendLine("    float3(-0.5773502691896258, 0.5773502691896258, -0.5773502691896258),");
            output.AppendLine("    float3(-0.5773502691896258, -0.5773502691896258, 0.5773502691896258)");
            output.AppendLine("};");
        }

        private static void AppendFunctions(StringBuilder o)
        {
            o.AppendLine(@"
struct M8FlowerInterval { float lo; float hi; };
struct M8FlowerInterval2 { M8FlowerInterval x; M8FlowerInterval y; };
struct M8FlowerInterval3 { M8FlowerInterval x; M8FlowerInterval y; M8FlowerInterval z; };

float M8FlowerNext(float v)
{
    uint b = asuint(v);
    if ((b & 0x7fffffffu) == 0u) return asfloat(1u);
    if (b == 0x7f800000u) return v;
    return asfloat((b & 0x80000000u) == 0u ? b + 1u : b - 1u);
}

float M8FlowerPrevious(float v)
{
    uint b = asuint(v);
    if ((b & 0x7fffffffu) == 0u) return asfloat(0x80000001u);
    if (b == 0xff800000u) return v;
    return asfloat((b & 0x80000000u) == 0u ? b - 1u : b + 1u);
}

M8FlowerInterval M8FlowerI(float lo, float hi)
{
    M8FlowerInterval r; r.lo = lo; r.hi = hi; return r;
}

M8FlowerInterval M8FlowerIAdd(M8FlowerInterval a, M8FlowerInterval b)
{
    precise float lo = a.lo+b.lo;
    precise float hi = a.hi+b.hi;
    return M8FlowerI(M8FlowerPrevious(lo),M8FlowerNext(hi));
}

M8FlowerInterval M8FlowerISub(M8FlowerInterval a, M8FlowerInterval b)
{
    precise float lo = a.lo-b.hi;
    precise float hi = a.hi-b.lo;
    return M8FlowerI(M8FlowerPrevious(lo),M8FlowerNext(hi));
}

M8FlowerInterval M8FlowerIMul(M8FlowerInterval a, M8FlowerInterval b)
{
    precise float4 p = float4(a.lo * b.lo, a.lo * b.hi,
        a.hi * b.lo, a.hi * b.hi);
    return M8FlowerI(M8FlowerPrevious(min(min(p.x,p.y),min(p.z,p.w))),
        M8FlowerNext(max(max(p.x,p.y),max(p.z,p.w))));
}

M8FlowerInterval M8FlowerISquare(M8FlowerInterval a)
{
    if (a.lo <= 0.0 && a.hi >= 0.0)
        return M8FlowerI(0.0,
            M8FlowerNext(max(a.lo*a.lo,a.hi*a.hi)));
    return M8FlowerIMul(a,a);
}

struct M8FlowerDyadicSquare
{
    uint2 coefficient;
    int exponent;
    uint nonzero;
};

uint2 M8FlowerMultiply24(uint a, uint b)
{
    uint a0 = a & 0xffffu;
    uint a1 = a >> 16;
    uint b0 = b & 0xffffu;
    uint b1 = b >> 16;
    uint p0 = a0*b0;
    uint p1 = a0*b1+a1*b0;
    uint lo = p0+(p1 << 16);
    uint carry = lo < p0 ? 1u : 0u;
    uint hi = (p1 >> 16)+a1*b1+carry;
    return uint2(lo,hi);
}

M8FlowerDyadicSquare M8FlowerSquareDyadic(float value)
{
    M8FlowerDyadicSquare result;
    uint bits = asuint(abs(value));
    uint exponentBits = (bits >> 23) & 0xffu;
    uint mantissa = bits & 0x7fffffu;
    result.nonzero = 0u;
    result.coefficient = 0u.xx;
    result.exponent = 0;
    if (exponentBits == 0xffu)
    {
        result.nonzero = 2u;
        return result;
    }
    if (exponentBits == 0u && mantissa == 0u)
        return result;
    int exponent = exponentBits == 0u ? -149 : (int)exponentBits-127-23;
    if (exponentBits != 0u) mantissa |= 0x800000u;
    int trailing = firstbitlow(mantissa);
    mantissa >>= trailing;
    exponent += trailing;
    result.coefficient = M8FlowerMultiply24(mantissa,mantissa);
    result.exponent = exponent*2;
    result.nonzero = 1u;
    return result;
}

uint M8FlowerBitLength(uint2 value)
{
    return value.y != 0u ? 33u+(uint)firstbithigh(value.y) :
        (value.x != 0u ? 1u+(uint)firstbithigh(value.x) : 0u);
}

bool M8FlowerEqual64(uint2 a, uint2 b)
{
    return all(a == b);
}

uint2 M8FlowerAdd64(uint2 a, uint2 b)
{
    uint lo = a.x+b.x;
    return uint2(lo,a.y+b.y+(lo < a.x ? 1u : 0u));
}

uint2 M8FlowerShiftLeft64(uint2 value, uint shift)
{
    if (shift == 0u) return value;
    if (shift < 32u)
        return uint2(value.x << shift,
            (value.y << shift) | (value.x >> (32u-shift)));
    if (shift < 64u) return uint2(0u,value.x << (shift-32u));
    return 0u.xx;
}

uint2 M8FlowerShiftRightOne64(uint2 value)
{
    return uint2((value.x >> 1) | (value.y << 31),value.y >> 1);
}

bool M8FlowerExactSquaredEquality(float a, float b, float c)
{
    M8FlowerDyadicSquare sa = M8FlowerSquareDyadic(a);
    M8FlowerDyadicSquare sb = M8FlowerSquareDyadic(b);
    M8FlowerDyadicSquare sc = M8FlowerSquareDyadic(c);
    if (sa.nonzero == 2u || sb.nonzero == 2u || sc.nonzero == 2u)
        return false;
    if (sb.nonzero == 0u && sc.nonzero == 0u)
        return sa.nonzero == 0u;
    if (sa.nonzero == 0u) return false;
    if (sb.nonzero == 0u)
        return sa.exponent == sc.exponent &&
            M8FlowerEqual64(sa.coefficient,sc.coefficient);
    if (sc.nonzero == 0u)
        return sa.exponent == sb.exponent &&
            M8FlowerEqual64(sa.coefficient,sb.coefficient);

    if (sb.exponent == sc.exponent)
    {
        uint2 sum = M8FlowerAdd64(sb.coefficient,sc.coefficient);
        return sa.exponent == sb.exponent+1 &&
            M8FlowerEqual64(sa.coefficient,M8FlowerShiftRightOne64(sum));
    }

    M8FlowerDyadicSquare low;
    M8FlowerDyadicSquare high;
    if (sb.exponent < sc.exponent)
    {
        low = sb;
        high = sc;
    }
    else
    {
        low = sc;
        high = sb;
    }
    int difference = high.exponent-low.exponent;
    if (sa.exponent != low.exponent || difference >= 64)
        return false;
    uint highBits = M8FlowerBitLength(high.coefficient);
    uint leftBits = M8FlowerBitLength(sa.coefficient);
    if (highBits+(uint)difference > leftBits)
        return false;
    uint2 sum = M8FlowerAdd64(low.coefficient,
        M8FlowerShiftLeft64(high.coefficient,(uint)difference));
    return M8FlowerEqual64(sa.coefficient,sum);
}

uint M8FlowerClassifyRoot(M8FlowerInterval3 abc)
{
    if (abc.x.lo == abc.x.hi && abc.y.lo == abc.y.hi &&
        abc.z.lo == abc.z.hi &&
        M8FlowerExactSquaredEquality(abc.x.lo,abc.y.lo,abc.z.lo))
        return abc.y.lo == 0.0 && abc.z.lo == 0.0 ?
            M8_FLOWER_ROOT_COPLANAR : M8_FLOWER_ROOT_CERTAIN_TANGENT;
    M8FlowerInterval q = M8FlowerIAdd(M8FlowerISquare(abc.y),
        M8FlowerISquare(abc.z));
    M8FlowerInterval aa = M8FlowerISquare(abc.x);
    if (q.lo == 0.0 && q.hi == 0.0)
    {
        if (abc.x.lo == abc.x.hi)
            return abc.x.lo == 0.0 ? M8_FLOWER_ROOT_COPLANAR :
                M8_FLOWER_ROOT_IMPOSSIBLE;
        return abc.x.lo <= 0.0 && abc.x.hi >= 0.0 ?
            M8_FLOWER_ROOT_AMBIGUOUS : M8_FLOWER_ROOT_IMPOSSIBLE;
    }
    if (aa.hi < q.lo) return M8_FLOWER_ROOT_CERTAIN_SECANT;
    if (aa.lo > q.hi) return M8_FLOWER_ROOT_IMPOSSIBLE;
    if (aa.lo == aa.hi && q.lo == q.hi && aa.lo == q.lo && q.lo > 0.0)
        return M8_FLOWER_ROOT_CERTAIN_TANGENT;
    return M8_FLOWER_ROOT_AMBIGUOUS;
}

// Exact dyadic comparisons certify the bounds around native sqrt/division.
// An implementation's approximate instruction can only cause AMBIGUOUS;
// its result is never accepted merely because it is within a chosen epsilon.
M8FlowerDyadicSquare M8FlowerProductDyadic(float left, float right)
{
    M8FlowerDyadicSquare result;
    uint2 bits = uint2(asuint(left), asuint(right)) & 0x7fffffffu;
    uint2 e = (bits >> 23u) & 0xffu;
    uint2 m = bits & 0x7fffffu;
    m |= uint2(e.x != 0u ? 0x800000u : 0u,
        e.y != 0u ? 0x800000u : 0u);
    result.coefficient = M8FlowerMultiply24(m.x, m.y);
    result.exponent = (e.x == 0u ? -149 : (int)e.x - 150) +
        (e.y == 0u ? -149 : (int)e.y - 150);
    result.nonzero = any(e == 255u) ? 2u :
        (all(m != 0u) ? 1u : 0u);
    if (result.nonzero == 0u) result.coefficient = 0u.xx;
    return result;
}

int M8FlowerCompareDyadic(M8FlowerDyadicSquare a, M8FlowerDyadicSquare b)
{
    uint na = M8FlowerBitLength(a.coefficient);
    uint nb = M8FlowerBitLength(b.coefficient);
    if (na == 0u || nb == 0u) return na == nb ? 0 : (na == 0u ? -1 : 1);
    int topA = a.exponent + (int)na;
    int topB = b.exponent + (int)nb;
    if (topA != topB) return topA < topB ? -1 : 1;
    uint2 ca = M8FlowerShiftLeft64(a.coefficient, na < nb ? nb - na : 0u);
    uint2 cb = M8FlowerShiftLeft64(b.coefficient, nb < na ? na - nb : 0u);
    if (ca.y != cb.y) return ca.y < cb.y ? -1 : 1;
    return ca.x == cb.x ? 0 : (ca.x < cb.x ? -1 : 1);
}

int M8FlowerCompareSignedProduct(float left, float positiveRight, float value)
{
    M8FlowerDyadicSquare a = M8FlowerProductDyadic(left, positiveRight);
    M8FlowerDyadicSquare b = M8FlowerProductDyadic(value, 1.0);
    bool negativeA = a.nonzero != 0u && (asuint(left) >> 31u) != 0u;
    bool negativeB = b.nonzero != 0u && (asuint(value) >> 31u) != 0u;
    if (negativeA != negativeB) return negativeA ? -1 : 1;
    int magnitude = M8FlowerCompareDyadic(a, b);
    return negativeA ? -magnitude : magnitude;
}

bool M8FlowerDivideEnclosed(float numerator, float denominator,
    out M8FlowerInterval result)
{
    result = M8FlowerI(0.0, 0.0);
    if (!isfinite(numerator) || !isfinite(denominator) || !(denominator > 0.0))
        return false;
    precise float quotient = numerator / denominator;
    float lo = M8FlowerPrevious(quotient);
    float hi = M8FlowerNext(quotient);
    if (!isfinite(lo) || !isfinite(hi)) return false;
    if (M8FlowerCompareSignedProduct(lo, denominator, numerator) > 0 ||
        M8FlowerCompareSignedProduct(hi, denominator, numerator) < 0)
        return false;
    result = M8FlowerI(lo, hi);
    return true;
}

bool M8FlowerIDivPositive(M8FlowerInterval numerator,
    M8FlowerInterval denominator, out M8FlowerInterval result)
{
    result = M8FlowerI(0.0, 0.0);
    if (!(denominator.lo > 0.0) || denominator.lo > denominator.hi ||
        numerator.lo > numerator.hi) return false;
    M8FlowerInterval lower = M8FlowerI(0.0, 0.0);
    M8FlowerInterval upper = lower;
    bool lowerValid = M8FlowerDivideEnclosed(numerator.lo,
        numerator.lo < 0.0 ? denominator.lo : denominator.hi, lower);
    bool upperValid = M8FlowerDivideEnclosed(numerator.hi,
        numerator.hi < 0.0 ? denominator.hi : denominator.lo, upper);
    if (!lowerValid || !upperValid) return false;
    result = M8FlowerI(lower.lo, upper.hi);
    return true;
}

bool M8FlowerISqrt(M8FlowerInterval value, out M8FlowerInterval result)
{
    result = M8FlowerI(0.0, 0.0);
    if (!(value.lo >= 0.0) || value.lo > value.hi || !isfinite(value.hi))
        return false;
    precise float lower = sqrt(value.lo);
    precise float upper = sqrt(value.hi);
    float lo = max(0.0, M8FlowerPrevious(lower));
    float hi = M8FlowerNext(upper);
    if (!isfinite(hi) ||
        M8FlowerCompareDyadic(M8FlowerSquareDyadic(lo),
            M8FlowerProductDyadic(value.lo, 1.0)) > 0 ||
        M8FlowerCompareDyadic(M8FlowerSquareDyadic(hi),
            M8FlowerProductDyadic(value.hi, 1.0)) < 0) return false;
    result = M8FlowerI(lo, hi);
    return true;
}

float M8FlowerAbsoluteProductSumUpper(float3 a, float3 b)
{
    precise float3 product = a * b;
    float3 upper = float3(M8FlowerNext(abs(product.x)),
        M8FlowerNext(abs(product.y)), M8FlowerNext(abs(product.z)));
    precise float xy = upper.x + upper.y;
    precise float xyz = M8FlowerNext(xy) + upper.z;
    return M8FlowerNext(xyz);
}

M8FlowerInterval M8FlowerCenterRadius(float center, float radius)
{
    precise float lo = center - radius;
    precise float hi = center + radius;
    return M8FlowerI(M8FlowerPrevious(lo), M8FlowerNext(hi));
}

// Section 5: the caller supplies the frozen calibrated + quantization
// uncertainty, never an observation score or a manually selected epsilon.
// relative is the loop-center displacement from this endpoint's M8 owner.
bool M8FlowerPlaneIntervals(float3 normal, float offset, float3 relative,
    float radius, uint lineClass, float normalUncertainty, float offsetUncertainty,
    out M8FlowerInterval3 abc)
{
    abc.x = M8FlowerI(0.0, 0.0); abc.y = abc.x; abc.z = abc.x;
    if (lineClass >= M8_FLOWER_LINE_CLASS_COUNT ||
        !all(isfinite(normal)) || !all(isfinite(relative)) ||
        !all(isfinite(float4(offset, radius, normalUncertainty, offsetUncertainty))) ||
        radius <= 0.0 || normalUncertainty < 0.0 || offsetUncertainty < 0.0)
        return false;
    float3 e1 = M8FlowerLineE1[lineClass];
    float3 e2 = M8FlowerLineE2[lineClass];
    precise float3 ar = normal * relative;
    precise float axy = ar.x + ar.y;
    precise float a = (axy + ar.z) - offset;
    precise float3 br = normal * e1;
    precise float bxy = br.x + br.y;
    precise float b = radius * (bxy + br.z);
    precise float3 cr = normal * e2;
    precise float cxy = cr.x + cr.y;
    precise float c = radius * (cxy + cr.z);

    M8FlowerInterval lengthSquared = M8FlowerIAdd(M8FlowerIAdd(
        M8FlowerISquare(M8FlowerI(relative.x, relative.x)),
        M8FlowerISquare(M8FlowerI(relative.y, relative.y))),
        M8FlowerISquare(M8FlowerI(relative.z, relative.z)));
    M8FlowerInterval length = M8FlowerI(0.0, 0.0);
    if (!M8FlowerISqrt(lengthSquared, length)) return false;
    precise float sa = M8FlowerAbsoluteProductSumUpper(normal, relative) + abs(offset);
    precise float sb = radius * M8FlowerAbsoluteProductSumUpper(normal, e1);
    precise float sc = radius * M8FlowerAbsoluteProductSumUpper(normal, e2);
    precise float eaMetric = normalUncertainty * length.hi;
    precise float eaOffset = M8FlowerNext(eaMetric) + offsetUncertainty;
    precise float eaRound = M8_FLOWER_GAMMA6_UPPER * M8FlowerNext(sa);
    precise float ea = M8FlowerNext(eaOffset) + M8FlowerNext(eaRound);
    precise float radialMetric = radius * normalUncertainty;
    precise float ebRound = M8_FLOWER_GAMMA7_UPPER * M8FlowerNext(sb);
    precise float ecRound = M8_FLOWER_GAMMA7_UPPER * M8FlowerNext(sc);
    precise float eb = M8FlowerNext(radialMetric) + M8FlowerNext(ebRound);
    precise float ec = M8FlowerNext(radialMetric) + M8FlowerNext(ecRound);
    abc.x = M8FlowerCenterRadius(a, M8FlowerNext(ea));
    abc.y = M8FlowerCenterRadius(b, M8FlowerNext(eb));
    abc.z = M8FlowerCenterRadius(c, M8FlowerNext(ec));
    return all(isfinite(float3(abc.x.lo, abc.y.lo, abc.z.lo))) &&
        all(isfinite(float3(abc.x.hi, abc.y.hi, abc.z.hi)));
}

uint M8FlowerRootInterval(M8FlowerInterval3 abc, bool plusRoot,
    out M8FlowerInterval2 root)
{
    root.x = M8FlowerI(0.0, 0.0);
    root.y = root.x;
    if (!all(isfinite(float3(abc.x.lo, abc.y.lo, abc.z.lo))) ||
        !all(isfinite(float3(abc.x.hi, abc.y.hi, abc.z.hi))) ||
        abc.x.lo > abc.x.hi || abc.y.lo > abc.y.hi || abc.z.lo > abc.z.hi)
        return M8_FLOWER_ROOT_AMBIGUOUS;
    uint classification = M8FlowerClassifyRoot(abc);
    if (classification != M8_FLOWER_ROOT_CERTAIN_SECANT &&
        classification != M8_FLOWER_ROOT_CERTAIN_TANGENT) return classification;
    M8FlowerInterval q = M8FlowerIAdd(M8FlowerISquare(abc.y),
        M8FlowerISquare(abc.z));
    M8FlowerInterval minusA = M8FlowerI(-abc.x.hi, -abc.x.lo);
    M8FlowerInterval x = M8FlowerIMul(minusA, abc.y);
    M8FlowerInterval y = M8FlowerIMul(minusA, abc.z);
    // Exact singleton tangency was established by dyadic equality, so no
    // uncertain subtraction around delta=0 is used to invent a second root.
    if (classification == M8_FLOWER_ROOT_CERTAIN_SECANT)
    {
        M8FlowerInterval delta = M8FlowerISub(q, M8FlowerISquare(abc.x));
        M8FlowerInterval turn = M8FlowerI(0.0, 0.0);
        if (!M8FlowerISqrt(delta, turn)) return M8_FLOWER_ROOT_AMBIGUOUS;
        if (!plusRoot) turn = M8FlowerI(-turn.hi, -turn.lo);
        x = M8FlowerIAdd(x, M8FlowerIMul(turn, M8FlowerI(-abc.z.hi, -abc.z.lo)));
        y = M8FlowerIAdd(y, M8FlowerIMul(turn, abc.y));
    }
    bool xValid = M8FlowerIDivPositive(x, q, root.x);
    bool yValid = M8FlowerIDivPositive(y, q, root.y);
    if (!xValid || !yValid) return M8_FLOWER_ROOT_AMBIGUOUS;
    return classification;
}

M8FlowerInterval M8FlowerICross(M8FlowerInterval2 a, M8FlowerInterval2 b)
{
    return M8FlowerISub(M8FlowerIMul(a.x, b.y), M8FlowerIMul(a.y, b.x));
}

bool M8FlowerRootSector(uint lineClass, M8FlowerInterval2 root, out uint sector)
{
    sector = 0xffffffffu;
    if (lineClass >= M8_FLOWER_LINE_CLASS_COUNT) return false;
    uint3 meta = M8FlowerLineMeta[lineClass];
    for (uint candidate = 0u; candidate < meta.z; candidate++)
    {
        float4 a = M8FlowerSectorBounds[meta.y + candidate];
        uint next = candidate + 1u == meta.z ? 0u : candidate + 1u;
        float4 b = M8FlowerSectorBounds[meta.y + next];
        M8FlowerInterval2 start, end;
        start.x = M8FlowerI(a.x, a.y); start.y = M8FlowerI(a.z, a.w);
        end.x = M8FlowerI(b.x, b.y); end.y = M8FlowerI(b.z, b.w);
        if (M8FlowerICross(start, root).lo > 0.0 &&
            M8FlowerICross(root, end).lo > 0.0)
        {
            if (sector != 0xffffffffu) { sector = 0xffffffffu; return false; }
            sector = candidate;
        }
    }
    return sector != 0xffffffffu;
}

int3 M8FlowerOverlapDelta(uint ordinal)
{
    return int3(ordinal & 1u, (ordinal >> 1u) & 1u, (ordinal >> 2u) & 1u);
}

uint M8FlowerOverlapBoundaryMask(int3 firstOwner, uint shift)
{
    uint mask = (1u << shift) - 1u;
    bool3 crosses = (asuint(firstOwner) & mask) == mask;
    return (crosses.x ? 1u : 0u) | (crosses.y ? 2u : 0u) |
        (crosses.z ? 4u : 0u);
}

int3 M8FlowerJunction(int3 kernel, int3 direction)
{
    return kernel * 2 + direction;
}

uint M8FlowerJunctionParity(int3 junction)
{
    uint3 u = asuint(junction);
    return (u.x & 1u) + (u.y & 1u) + (u.z & 1u);
}

bool M8FlowerEndpointPair(int3 junction, uint lineClass,
    out int3 first, out int3 second)
{
    int3 direction = M8FlowerLineDirection[lineClass];
    int3 doubled = junction-direction;
    if (any((asuint(doubled) & 1u) != 0u))
    {
        first = 0;
        second = 0;
        return false;
    }
    first = doubled >> 1;
    second = first+direction;
    return true;
}

float M8FlowerLevelStep(uint level)
{
    return M8_FLOWER_LATTICE_STEP / float(1u << level);
}

bool M8FlowerRoot(float3 abc, bool plusRoot, out float2 root)
{
    precise float q = abc.y*abc.y+abc.z*abc.z;
    precise float delta = q-abc.x*abc.x;
    if (!(q > 0.0) || delta < 0.0) { root = 0.0.xx; return false; }
    precise float d = sqrt(delta);
    precise float s = plusRoot ? 1.0 : -1.0;
    root = float2((-abc.x*abc.y + s*d*-abc.z)/q,
        (-abc.x*abc.z + s*d*abc.y)/q);
    return true;
}

bool M8FlowerTau(float2 from, float2 to, out float turn)
{
    precise float denominator = 1.0+dot(from,to);
    if (denominator == 0.0) { turn = 0.0; return false; }
    turn = (from.x*to.y-from.y*to.x)/denominator;
    return true;
}

float2 M8FlowerRotate(float2 root, float turn)
{
    precise float rr = turn*turn;
    precise float inverse = 1.0/(1.0+rr);
    precise float c = (1.0-rr)*inverse;
    precise float s = 2.0*turn*inverse;
    return float2(c*root.x-s*root.y,s*root.x+c*root.y);
}

float4 M8FlowerTetraForward(float4 q)
{
    precise float scalar = 0.25*(q.x+q.y+q.z+q.w);
    precise float3 tetraVector = 0.75*(q.x*M8FlowerTetraAxis[0]+
        q.y*M8FlowerTetraAxis[1]+q.z*M8FlowerTetraAxis[2]+
        q.w*M8FlowerTetraAxis[3]);
    return float4(scalar,tetraVector);
}

float4 M8FlowerTetraInverse(float scalar, float3 tetraVector)
{
    return float4(scalar+dot(M8FlowerTetraAxis[0],tetraVector),
        scalar+dot(M8FlowerTetraAxis[1],tetraVector),
        scalar+dot(M8FlowerTetraAxis[2],tetraVector),
        scalar+dot(M8FlowerTetraAxis[3],tetraVector));
}

uint3 M8FlowerSkinWedgeSites(uint wedge)
{
    return uint3(0u,wedge+1u,wedge==5u ? 1u : wedge+2u);
}

bool M8FlowerSkinBefore(float leftValue, uint leftSite,
    float rightValue, uint rightSite)
{
    return leftValue>rightValue ||
        (leftValue==rightValue && leftSite<rightSite);
}

void M8FlowerSkinSortPair(inout uint left, inout uint right,
    float3 values, uint3 sites)
{
    if (M8FlowerSkinBefore(values[left],sites[left],
            values[right],sites[right])) return;
    uint swap=left; left=right; right=swap;
}

uint M8FlowerSkinOrder(float3 barycentric, uint wedge)
{
    uint3 sites=M8FlowerSkinWedgeSites(wedge);
    uint high=0u,middle=1u,low=2u;
    M8FlowerSkinSortPair(high,middle,barycentric,sites);
    M8FlowerSkinSortPair(middle,low,barycentric,sites);
    M8FlowerSkinSortPair(high,middle,barycentric,sites);
    if (high==0u) return middle==1u ? 0u : 1u;
    if (high==1u) return middle==0u ? 2u : 3u;
    return middle==0u ? 4u : 5u;
}

uint4 M8FlowerSkinDescend(float3 barycentric, uint wedge,
    out float3 childBarycentric)
{
    int4 rule=M8FlowerSkinChamber[wedge*6u+
        M8FlowerSkinOrder(barycentric,wedge)];
    precise float x0=barycentric[rule.x];
    precise float x1=barycentric[rule.y];
    precise float x2=barycentric[rule.z];
    childBarycentric=float3(x0-x1,2.0*(x1-x2),3.0*x2);
    uint packed=asuint(rule.w);
    return uint4(packed&0xffu,(packed>>8)&0xffu,
        (packed>>16)&0xffu,(packed>>24)&1u);
}

uint M8FlowerRank7(uint mask, uint bit)
{
    uint below=bit==0u ? 0u : (1u<<bit)-1u;
    return countbits(mask&below&0x7fu);
}

uint M8FlowerRank49(uint2 mask, uint bit)
{
    mask.y&=0x1ffffu;
    if (bit<=32u)
    {
        uint below=bit==0u ? 0u :
            (bit==32u ? 0xffffffffu : (1u<<bit)-1u);
        return countbits(mask.x&below);
    }
    uint highBit=bit-32u;
    uint highBelow=highBit==0u ? 0u : (1u<<highBit)-1u;
    return countbits(mask.x)+countbits(mask.y&highBelow);
}

void M8FlowerUnpackSkinSplitBits(uint packedLo, uint packedHi,
    out uint splitL2, out uint splitL3, out uint2 splitL4)
{
    splitL2=packedLo&1u;
    splitL3=(packedLo>>1)&0x7fu;
    splitL4.x=(packedLo>>8)|((packedHi&0xffu)<<24);
    splitL4.y=(packedHi>>8)&0x1ffffu;
}

bool M8FlowerSkinCompactChildAddress(uint groupBase, uint packedLo,
    uint packedHi, uint level, uint c3, uint c4, uint c5,
    out uint groupIndex, out uint childStitchRank)
{
    uint splitL2,splitL3;
    uint2 splitL4;
    M8FlowerUnpackSkinSplitBits(packedLo,packedHi,splitL2,splitL3,splitL4);
    uint j3=M8FlowerSkinL3ChildRank[c3];
    groupIndex=0xffffffffu;
    childStitchRank=0xffffffffu;
    if (splitL2==0u) return false;
    if (level==3u)
    {
        groupIndex=groupBase;
        childStitchRank=j3;
        return true;
    }
    if ((splitL3&(1u<<j3))==0u) return false;
    uint p4=7u*c3+c4;
    uint r4=M8FlowerSkinL4ChildRank[p4];
    if (level==4u)
    {
        groupIndex=groupBase+1u+M8FlowerRank7(splitL3,j3);
        childStitchRank=r4;
        return true;
    }
    uint j4=M8FlowerSkinL4ParentThread[p4];
    uint l4Word=j4<32u ? splitL4.x : splitL4.y;
    uint l4Shift=j4<32u ? j4 : j4-32u;
    if (level!=5u || (l4Word&(1u<<l4Shift))==0u) return false;
    groupIndex=groupBase+1u+countbits(splitL3)+
        M8FlowerRank49(splitL4,j4);
    childStitchRank=M8FlowerSkinL5ChildRank[49u*c3+7u*c4+c5];
    return true;
}

bool M8FlowerSkinSplitClosure(uint splitL2, uint splitL3, uint2 splitL4)
{
    if ((splitL3&~0x7fu)!=0u || (splitL4.y&~0x1ffffu)!=0u)
        return false;
    if (splitL2==0u)
        return splitL3==0u && all(splitL4==0u.xx);
    [unroll]
    for (uint parent=0u;parent<7u;parent++)
    {
        if ((splitL3&(1u<<parent))!=0u) continue;
        [unroll]
        for (uint child=0u;child<7u;child++)
        {
            uint bit=7u*parent+child;
            uint value=bit<32u ? splitL4.x : splitL4.y;
            uint shift=bit<32u ? bit : bit-32u;
            if ((value&(1u<<shift))!=0u) return false;
        }
    }
    return true;
}

uint M8FlowerCompactSkinValueCount(uint splitL2, uint splitL3,
    uint2 splitL4)
{
    if (!M8FlowerSkinSplitClosure(splitL2,splitL3,splitL4))
        return 0xffffffffu;
    if (splitL2==0u) return 1u;
    return 8u+7u*countbits(splitL3&0x7fu)+
        7u*(countbits(splitL4.x)+countbits(splitL4.y&0x1ffffu));
}

bool M8FlowerIntervalsDisjoint(float2 left, float2 right)
{
    return left.y<right.x || right.y<left.x;
}

uint M8FlowerClassifyScalarSkinSplit(float2 child[7], uint certainMask)
{
    if ((certainMask&0x7fu)!=0x7fu) return M8_FLOWER_SKIN_AMBIGUOUS;
    [unroll]
    for (uint i=0u;i<7u;i++)
    {
        [unroll]
        for (uint j=i+1u;j<7u;j++)
            if (M8FlowerIntervalsDisjoint(child[i],child[j]))
                return M8_FLOWER_SKIN_SPLIT;
    }
    return M8_FLOWER_SKIN_UNIFORM;
}

uint M8FlowerClassifyRgbSkinSplit(float2 childRgb[21], uint certainMask)
{
    if ((certainMask&0x7fu)!=0x7fu) return M8_FLOWER_SKIN_AMBIGUOUS;
    [unroll]
    for (uint i=0u;i<7u;i++)
    {
        [unroll]
        for (uint j=i+1u;j<7u;j++)
        {
            [unroll]
            for (uint channel=0u;channel<3u;channel++)
                if (M8FlowerIntervalsDisjoint(childRgb[3u*i+channel],
                        childRgb[3u*j+channel]))
                    return M8_FLOWER_SKIN_SPLIT;
        }
    }
    return M8_FLOWER_SKIN_UNIFORM;
}

float M8FlowerSkinBubble(float3 barycentric)
{
    precise float p=barycentric.x*barycentric.y*barycentric.z;
    return 729.0*p*p;
}

float3 M8FlowerSkinBubbleGradient(float3 b)
{
    return 1458.0*float3(
        b.x*b.y*b.y*b.z*b.z,
        b.y*b.x*b.x*b.z*b.z,
        b.z*b.x*b.x*b.y*b.y);
}

float M8FlowerNestedV(float3 child3, float3 child4, float3 child5,
    float3 amplitude)
{
    return amplitude.x*M8FlowerSkinBubble(child3)+
        amplitude.y*M8FlowerSkinBubble(child4)+
        amplitude.z*M8FlowerSkinBubble(child5);
}
");
        }

        private static void Define(StringBuilder output, string name,
            string value) => output.Append("#define ").Append(name).Append(' ')
            .AppendLine(value);

        private static void AppendHlslWordStruct(StringBuilder output,
            string name, int wordCount)
        {
            output.Append("struct ").Append(name).Append(" { ");
            for (int i = 0; i < wordCount; i++)
                output.Append("uint Word").Append(i.ToString("00",
                    CultureInfo.InvariantCulture)).Append("; ");
            output.AppendLine("};");
        }

        private static void AppendNativeStruct(StringBuilder output,
            string name, string[] fields)
        {
            output.Append("struct ").Append(name).AppendLine(" {");
            foreach (string field in fields)
                output.Append("    ").Append(field).AppendLine(";");
            output.AppendLine("};");
        }

        private static void AppendNativeArrayStruct(StringBuilder output,
            string name, int wordCount)
        {
            output.Append("struct ").Append(name).Append(" { uint32_t words[")
                .Append(wordCount).AppendLine("]; };");
        }

        private static void AppendNativeSizeAssert(StringBuilder output,
            string name, int size)
        {
            output.Append("static_assert(sizeof(").Append(name).Append(") == ")
                .Append(size).AppendLine("u);");
        }

        private static void Comma(StringBuilder output, int index, int count) =>
            output.AppendLine(index + 1 == count ? string.Empty : ",");

        private static string Int3(int3 value) =>
            $"int3({value.x}, {value.y}, {value.z})";

        private static string Int4(int4 value) =>
            $"int4({value.x}, {value.y}, {value.z}, {value.w})";

        private static string Float2(float2 value) =>
            $"float2({Number(value.x)}, {Number(value.y)})";

        private static string Float3(float3 value) =>
            $"float3({Number(value.x)}, {Number(value.y)}, {Number(value.z)})";

        private static string CsInt3(int3 value) =>
            $"new int3({value.x}, {value.y}, {value.z})";

        private static string CsInt4(int4 value) =>
            $"new int4({value.x}, {value.y}, {value.z}, {value.w})";

        private static string CsFloat2(float2 value) =>
            $"new float2({CsNumber(value.x)}, {CsNumber(value.y)})";

        private static string CsFloat3(float3 value) =>
            $"new float3({CsNumber(value.x)}, {CsNumber(value.y)}, " +
            $"{CsNumber(value.z)})";

        private static string CsInterval(
            MerkabaSphereFlowerAuthority.FloatInterval value) =>
            $"new FloatInterval({CsNumber(value.Lower)}, " +
            $"{CsNumber(value.Upper)})";

        private static string CsNumber(float value) =>
            Number(value) + "f";

        private static string Number(float value) =>
            value.ToString("R", CultureInfo.InvariantCulture);
    }
}
