using System;
using System.Globalization;
using System.IO;
using System.Text;
using Unity.Mathematics;
using UnityEditor;
using UnityEngine;

namespace Genesis.RoomScan.Editor
{
    /// <summary>
    /// Emits the GPU half of the exact CPU Sphere-Flower oracle. All arrays are
    /// enumerated from MerkabaSphereFlowerAuthority; no topology is maintained
    /// independently in this generator.
    /// </summary>
    public static class MerkabaSphereFlowerCodegen
    {
        public const string GeneratedAssetPath =
            "Packages/com.genesis.roomscan/Runtime/Shaders/MerkabaSphereFlower.generated.hlsl";
        public const string GeneratedCsAssetPath =
            "Packages/com.genesis.roomscan/Runtime/Merkaba/MerkabaSphereFlower.generated.cs";

        [MenuItem("Quest Infinite Scan/Merkaba/Regenerate Sphere-Flower HLSL")]
        public static void Regenerate()
        {
            WriteIfChanged(GeneratedAssetPath, BuildGeneratedHlsl());
            WriteIfChanged(GeneratedCsAssetPath, BuildGeneratedCs());
            Debug.Log("[SphereFlower] Generated exact CPU/HLSL tables.");
        }

        public static void GenerateForBatch() => Regenerate();

        public static void CheckForBatch()
        {
            CheckExact(GeneratedAssetPath, BuildGeneratedHlsl());
            CheckExact(GeneratedCsAssetPath, BuildGeneratedCs());
        }

        private static void WriteIfChanged(string assetPath, string expected)
        {
            string path = Path.GetFullPath(assetPath);
            if (File.Exists(path) && string.Equals(File.ReadAllText(path),
                    expected, StringComparison.Ordinal)) return;
            File.WriteAllText(path, expected);
            AssetDatabase.ImportAsset(assetPath,
                ImportAssetOptions.ForceSynchronousImport);
        }

        private static void CheckExact(string assetPath, string expected)
        {
            string path = Path.GetFullPath(assetPath);
            if (!File.Exists(path))
                throw new FileNotFoundException(
                    "Generated Sphere-Flower table is missing.", path);
            if (!string.Equals(File.ReadAllText(path), expected,
                    StringComparison.Ordinal))
                throw new InvalidDataException(
                    $"Generated Sphere-Flower table is stale: {assetPath}");
        }

        internal static string BuildGeneratedHlsl()
        {
            var output = new StringBuilder(48 * 1024);
            output.AppendLine("// GENERATED by MerkabaSphereFlowerCodegen. DO NOT EDIT.");
            output.AppendLine("// Exact finite tables from MerkabaSphereFlowerAuthority.");
            output.AppendLine("#ifndef GENESIS_MERKABA_SPHERE_FLOWER_INCLUDED");
            output.AppendLine("#define GENESIS_MERKABA_SPHERE_FLOWER_INCLUDED");
            Define(output, "M8_FLOWER_LATTICE_STEP",
                Number(MerkabaSphereFlowerAuthority.LatticeStep));
            Define(output, "M8_FLOWER_LEVEL_COUNT",
                MerkabaSphereFlowerAuthority.LevelCount + "u");
            Define(output, "M8_FLOWER_DIRECTION_COUNT",
                MerkabaSphereFlowerAuthority.DirectedRelationCount + "u");
            Define(output, "M8_FLOWER_LINE_CLASS_COUNT",
                MerkabaSphereFlowerAuthority.LineClassCount + "u");
            Define(output, "M8_FLOWER_NODE_CLASS_COUNT",
                MerkabaSphereFlowerAuthority.NodeClassCount + "u");
            Define(output, "M8_FLOWER_STRAND_CLASS_COUNT",
                MerkabaSphereFlowerAuthority.StrandClassCount + "u");
            Define(output, "M8_FLOWER_PETAL_CLASS_COUNT",
                MerkabaSphereFlowerAuthority.PetalClassCount + "u");
            Define(output, "M8_FLOWER_SECTOR_BOUNDARY_COUNT",
                MerkabaSphereFlowerAuthority.SectorBoundaries.Length + "u");
            Define(output, "M8_FLOWER_TABLE_HASH",
                "0x" + MerkabaSphereFlowerAuthority.ComputeFrozenTableHash()
                    .ToString("x8", CultureInfo.InvariantCulture) + "u");
            Define(output, "M8_FLOWER_ROOT_IMPOSSIBLE", "0u");
            Define(output, "M8_FLOWER_ROOT_CERTAIN_TANGENT", "1u");
            Define(output, "M8_FLOWER_ROOT_CERTAIN_SECANT", "2u");
            Define(output, "M8_FLOWER_ROOT_COPLANAR", "3u");
            Define(output, "M8_FLOWER_ROOT_AMBIGUOUS", "4u");
            output.AppendLine();

            AppendLines(output);
            AppendDirections(output);
            AppendNodes(output);
            AppendStrands(output);
            AppendPetals(output);
            AppendChildren(output);
            AppendSectors(output);
            AppendTetraFrames(output);
            AppendFunctions(output);
            output.AppendLine("#endif");
            return output.ToString();
        }

        internal static string BuildGeneratedCs()
        {
            var o = new StringBuilder(48 * 1024);
            o.AppendLine("// GENERATED by MerkabaSphereFlowerCodegen. DO NOT EDIT.");
            o.AppendLine("using Unity.Mathematics;");
            o.AppendLine();
            o.AppendLine("namespace Genesis.RoomScan");
            o.AppendLine("{");
            o.AppendLine("    public static partial class MerkabaSphereFlowerAuthority");
            o.AppendLine("    {");
            o.Append("        internal const uint FrozenTableHash = 0x")
                .Append(MerkabaSphereFlowerAuthority.ComputeFrozenTableHash()
                    .ToString("x8", CultureInfo.InvariantCulture))
                .AppendLine("u;");
            o.AppendLine();
            o.AppendLine("        private static void LoadGeneratedTables(");
            o.AppendLine("            out LineRule[] lines, out DirectionRule[] directions,");
            o.AppendLine("            out NodeRule[] nodes, out StrandRule[] strands,");
            o.AppendLine("            out PetalRule[] petals, out SectorBoundary[] sectors,");
            o.AppendLine("            out TetraFrameRule[] tetraFrames)");
            o.AppendLine("        {");
            AppendGeneratedCsLines(o);
            AppendGeneratedCsDirections(o);
            AppendGeneratedCsNodes(o);
            AppendGeneratedCsStrands(o);
            AppendGeneratedCsPetals(o);
            AppendGeneratedCsSectors(o);
            AppendGeneratedCsTetra(o);
            o.AppendLine("        }");
            o.AppendLine("    }");
            o.AppendLine("}");
            return o.ToString();
        }

        private static void AppendGeneratedCsLines(StringBuilder o)
        {
            o.AppendLine("            lines = new LineRule[]");
            o.AppendLine("            {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.Lines.Length; i++)
            {
                var x = MerkabaSphereFlowerAuthority.Lines[i];
                o.Append("                new LineRule(").Append(CsInt3(x.Direction))
                    .Append(", (Shell)").Append((int)x.Shell).Append(", ")
                    .Append(CsFloat3(x.UnitDirection)).Append(", ")
                    .Append(CsFloat3(x.E1)).Append(", ")
                    .Append(CsFloat3(x.E2)).Append(", ")
                    .Append(x.SectorOffset).Append(", ")
                    .Append(x.SectorCount).Append(')');
                Comma(o, i, MerkabaSphereFlowerAuthority.Lines.Length);
            }
            o.AppendLine("            };");
        }

        private static void AppendGeneratedCsDirections(StringBuilder o)
        {
            o.AppendLine("            directions = new DirectionRule[]");
            o.AppendLine("            {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.Directions.Length; i++)
            {
                var x = MerkabaSphereFlowerAuthority.Directions[i];
                o.Append("                new DirectionRule(")
                    .Append(CsInt3(x.Direction)).Append(", ")
                    .Append(x.LineClass).Append(", ")
                    .Append(x.Orientation).Append(", (Shell)")
                    .Append((int)x.Shell).Append(')');
                Comma(o, i, MerkabaSphereFlowerAuthority.Directions.Length);
            }
            o.AppendLine("            };");
        }

        private static void AppendGeneratedCsNodes(StringBuilder o)
        {
            o.AppendLine("            nodes = new NodeRule[]");
            o.AppendLine("            {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.Directions.Length; i++)
            {
                o.Append("                new NodeRule(directions[").Append(i)
                    .Append("])");
                Comma(o, i, MerkabaSphereFlowerAuthority.Directions.Length);
            }
            o.AppendLine("            };");
        }

        private static void AppendGeneratedCsStrands(StringBuilder o)
        {
            o.AppendLine("            strands = new StrandRule[]");
            o.AppendLine("            {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.Strands.Length; i++)
            {
                var x = MerkabaSphereFlowerAuthority.Strands[i];
                o.Append("                new StrandRule(").Append(x.Node0)
                    .Append(", ").Append(x.Node1).Append(", ")
                    .Append(x.IncidenceKind).Append(", ").Append(x.Petal0)
                    .Append(", ").Append(x.Petal1).Append(')');
                Comma(o, i, MerkabaSphereFlowerAuthority.Strands.Length);
            }
            o.AppendLine("            };");
        }

        private static void AppendGeneratedCsPetals(StringBuilder o)
        {
            o.AppendLine("            petals = new PetalRule[]");
            o.AppendLine("            {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.Petals.Length; i++)
            {
                var x = MerkabaSphereFlowerAuthority.Petals[i];
                o.Append("                new PetalRule(").Append(x.FaceNode)
                    .Append(", ").Append(x.EdgeNode).Append(", ")
                    .Append(x.CornerNode).Append(", ").Append(x.Strand0)
                    .Append(", ").Append(x.Strand1).Append(", ")
                    .Append(x.Strand2).Append(", ").Append(x.Orientation)
                    .Append(", ").Append(x.StrandSign0)
                    .Append(", ").Append(x.StrandSign1)
                    .Append(", ").Append(x.StrandSign2)
                    .Append(')');
                Comma(o, i, MerkabaSphereFlowerAuthority.Petals.Length);
            }
            o.AppendLine("            };");
        }

        private static void AppendGeneratedCsSectors(StringBuilder o)
        {
            o.AppendLine("            sectors = new SectorBoundary[]");
            o.AppendLine("            {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.SectorBoundaries.Length; i++)
            {
                var x = MerkabaSphereFlowerAuthority.SectorBoundaries[i];
                o.Append("                new SectorBoundary(")
                    .Append(CsFloat2(x.Unit)).Append(", new Interval2(")
                    .Append(CsInterval(x.Enclosure.X)).Append(", ")
                    .Append(CsInterval(x.Enclosure.Y)).Append("))");
                Comma(o, i, MerkabaSphereFlowerAuthority.SectorBoundaries.Length);
            }
            o.AppendLine("            };");
        }

        private static void AppendGeneratedCsTetra(StringBuilder o)
        {
            o.AppendLine("            tetraFrames = new TetraFrameRule[]");
            o.AppendLine("            {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.TetraFrames.Length; i++)
            {
                var x = MerkabaSphereFlowerAuthority.TetraFrames[i];
                o.Append("                new TetraFrameRule(")
                    .Append(CsInt4(x.LineClasses)).Append(", ")
                    .Append(CsInt4(x.Eta)).Append(", ")
                    .Append(x.Chirality).Append(')');
                Comma(o, i, MerkabaSphereFlowerAuthority.TetraFrames.Length);
            }
            o.AppendLine("            };");
        }

        private static void AppendLines(StringBuilder output)
        {
            output.AppendLine("static const int3 M8FlowerLineDirection[13] = {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.Lines.Length; i++)
            {
                var line = MerkabaSphereFlowerAuthority.Lines[i];
                output.Append("    ").Append(Int3(line.Direction));
                Comma(output, i, MerkabaSphereFlowerAuthority.Lines.Length);
            }
            output.AppendLine("};");
            output.AppendLine("static const float3 M8FlowerLineUnit[13] = {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.Lines.Length; i++)
            {
                output.Append("    ").Append(Float3(
                    MerkabaSphereFlowerAuthority.Lines[i].UnitDirection));
                Comma(output, i, MerkabaSphereFlowerAuthority.Lines.Length);
            }
            output.AppendLine("};");
            output.AppendLine("static const float3 M8FlowerLineE1[13] = {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.Lines.Length; i++)
            {
                output.Append("    ").Append(Float3(
                    MerkabaSphereFlowerAuthority.Lines[i].E1));
                Comma(output, i, MerkabaSphereFlowerAuthority.Lines.Length);
            }
            output.AppendLine("};");
            output.AppendLine("static const float3 M8FlowerLineE2[13] = {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.Lines.Length; i++)
            {
                output.Append("    ").Append(Float3(
                    MerkabaSphereFlowerAuthority.Lines[i].E2));
                Comma(output, i, MerkabaSphereFlowerAuthority.Lines.Length);
            }
            output.AppendLine("};");
            output.AppendLine("static const uint3 M8FlowerLineMeta[13] = {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.Lines.Length; i++)
            {
                var line = MerkabaSphereFlowerAuthority.Lines[i];
                output.Append("    uint3(").Append((uint)line.Shell).Append("u, ")
                    .Append(line.SectorOffset).Append("u, ")
                    .Append(line.SectorCount).Append("u)");
                Comma(output, i, MerkabaSphereFlowerAuthority.Lines.Length);
            }
            output.AppendLine("};");
        }

        private static void AppendDirections(StringBuilder output)
        {
            output.AppendLine("static const int4 M8FlowerDirection[26] = {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.Directions.Length; i++)
            {
                var value = MerkabaSphereFlowerAuthority.Directions[i];
                output.Append("    int4(").Append(value.Direction.x).Append(", ")
                    .Append(value.Direction.y).Append(", ")
                    .Append(value.Direction.z).Append(", ")
                    .Append(value.LineClass).Append(")");
                Comma(output, i, MerkabaSphereFlowerAuthority.Directions.Length);
            }
            output.AppendLine("};");
            output.AppendLine("static const int2 M8FlowerDirectionMeta[26] = {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.Directions.Length; i++)
            {
                var value = MerkabaSphereFlowerAuthority.Directions[i];
                output.Append("    int2(").Append(value.Orientation).Append(", ")
                    .Append((int)value.Shell).Append(")");
                Comma(output, i, MerkabaSphereFlowerAuthority.Directions.Length);
            }
            output.AppendLine("};");
        }

        private static void AppendNodes(StringBuilder output)
        {
            output.AppendLine("static const int4 M8FlowerNode[26] = {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.Nodes.Length; i++)
            {
                var value = MerkabaSphereFlowerAuthority.Nodes[i];
                output.Append("    int4(").Append(value.Direction.x).Append(", ")
                    .Append(value.Direction.y).Append(", ")
                    .Append(value.Direction.z).Append(", ")
                    .Append(value.LineClass).Append(")");
                Comma(output, i, MerkabaSphereFlowerAuthority.Nodes.Length);
            }
            output.AppendLine("};");
        }

        private static void AppendStrands(StringBuilder output)
        {
            output.AppendLine("static const uint4 M8FlowerStrand[72] = {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.Strands.Length; i++)
            {
                var value = MerkabaSphereFlowerAuthority.Strands[i];
                uint petals = (uint)(value.Petal0 | (value.Petal1 << 8));
                output.Append("    uint4(").Append(value.Node0).Append("u, ")
                    .Append(value.Node1).Append("u, ")
                    .Append(value.IncidenceKind).Append("u, ")
                    .Append(petals).Append("u)");
                Comma(output, i, MerkabaSphereFlowerAuthority.Strands.Length);
            }
            output.AppendLine("};");
        }

        private static void AppendPetals(StringBuilder output)
        {
            output.AppendLine("static const uint4 M8FlowerPetalNodes[48] = {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.Petals.Length; i++)
            {
                var p = MerkabaSphereFlowerAuthority.Petals[i];
                output.Append("    uint4(").Append(p.FaceNode).Append("u, ")
                    .Append(p.EdgeNode).Append("u, ")
                    .Append(p.CornerNode).Append("u, ")
                    .Append(p.Orientation > 0 ? "1u" : "0u").Append(")");
                Comma(output, i, MerkabaSphereFlowerAuthority.Petals.Length);
            }
            output.AppendLine("};");
            output.AppendLine("static const uint3 M8FlowerPetalStrands[48] = {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.Petals.Length; i++)
            {
                var p = MerkabaSphereFlowerAuthority.Petals[i];
                output.Append("    uint3(").Append(p.Strand0).Append("u, ")
                    .Append(p.Strand1).Append("u, ")
                    .Append(p.Strand2).Append("u)");
                Comma(output, i, MerkabaSphereFlowerAuthority.Petals.Length);
            }
            output.AppendLine("};");
            output.AppendLine("static const int3 M8FlowerPetalStrandSign[48] = {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.Petals.Length; i++)
            {
                var p = MerkabaSphereFlowerAuthority.Petals[i];
                output.Append("    int3(").Append(p.StrandSign0).Append(", ")
                    .Append(p.StrandSign1).Append(", ")
                    .Append(p.StrandSign2).Append(")");
                Comma(output, i, MerkabaSphereFlowerAuthority.Petals.Length);
            }
            output.AppendLine("};");
        }

        private static void AppendChildren(StringBuilder output)
        {
            output.AppendLine("static const uint3 M8FlowerChildPetal[4] = {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.ChildPetals.Length; i++)
            {
                var c = MerkabaSphereFlowerAuthority.ChildPetals[i];
                output.Append("    uint3(").Append(c.Vertex0).Append("u, ")
                    .Append(c.Vertex1).Append("u, ")
                    .Append(c.Vertex2).Append("u)");
                Comma(output, i, MerkabaSphereFlowerAuthority.ChildPetals.Length);
            }
            output.AppendLine("};");
        }

        private static void AppendSectors(StringBuilder output)
        {
            int count = MerkabaSphereFlowerAuthority.SectorBoundaries.Length;
            output.Append("static const float4 M8FlowerSectorBounds[")
                .Append(count).AppendLine("] = {");
            for (int i = 0; i < count; i++)
            {
                var b = MerkabaSphereFlowerAuthority.SectorBoundaries[i];
                output.Append("    float4(")
                    .Append(Number(b.Enclosure.X.Lower)).Append(", ")
                    .Append(Number(b.Enclosure.X.Upper)).Append(", ")
                    .Append(Number(b.Enclosure.Y.Lower)).Append(", ")
                    .Append(Number(b.Enclosure.Y.Upper)).Append(")");
                Comma(output, i, count);
            }
            output.AppendLine("};");
            output.Append("static const float2 M8FlowerSectorUnit[")
                .Append(count).AppendLine("] = {");
            for (int i = 0; i < count; i++)
            {
                output.Append("    ").Append(Float2(
                    MerkabaSphereFlowerAuthority.SectorBoundaries[i].Unit));
                Comma(output, i, count);
            }
            output.AppendLine("};");
        }

        private static void AppendTetraFrames(StringBuilder output)
        {
            output.AppendLine("static const int4 M8FlowerTetraLine[8] = {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.TetraFrames.Length; i++)
            {
                output.Append("    ").Append(Int4(
                    MerkabaSphereFlowerAuthority.TetraFrames[i].LineClasses));
                Comma(output, i, MerkabaSphereFlowerAuthority.TetraFrames.Length);
            }
            output.AppendLine("};");
            output.AppendLine("static const int4 M8FlowerTetraEta[8] = {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.TetraFrames.Length; i++)
            {
                output.Append("    ").Append(Int4(
                    MerkabaSphereFlowerAuthority.TetraFrames[i].Eta));
                Comma(output, i, MerkabaSphereFlowerAuthority.TetraFrames.Length);
            }
            output.AppendLine("};");
            output.AppendLine("static const int M8FlowerTetraChirality[8] = {");
            for (int i = 0; i < MerkabaSphereFlowerAuthority.TetraFrames.Length; i++)
            {
                output.Append("    ")
                    .Append(MerkabaSphereFlowerAuthority.TetraFrames[i].Chirality);
                Comma(output, i, MerkabaSphereFlowerAuthority.TetraFrames.Length);
            }
            output.AppendLine("};");
            output.AppendLine("static const float3 M8FlowerTetraAxis[4] = {");
            output.AppendLine("    float3(0.5773502691896258, 0.5773502691896258, 0.5773502691896258),");
            output.AppendLine("    float3(0.5773502691896258, -0.5773502691896258, -0.5773502691896258),");
            output.AppendLine("    float3(-0.5773502691896258, 0.5773502691896258, -0.5773502691896258),");
            output.AppendLine("    float3(-0.5773502691896258, -0.5773502691896258, 0.5773502691896258)");
            output.AppendLine("};");
        }

        private static void AppendFunctions(StringBuilder o)
        {
            o.AppendLine(@"
struct M8FlowerInterval { float lo; float hi; };
struct M8FlowerInterval2 { M8FlowerInterval x; M8FlowerInterval y; };
struct M8FlowerInterval3 { M8FlowerInterval x; M8FlowerInterval y; M8FlowerInterval z; };

float M8FlowerNext(float v)
{
    uint b = asuint(v);
    if ((b & 0x7fffffffu) == 0u) return asfloat(1u);
    if (b == 0x7f800000u) return v;
    return asfloat((b & 0x80000000u) == 0u ? b + 1u : b - 1u);
}

float M8FlowerPrevious(float v)
{
    uint b = asuint(v);
    if ((b & 0x7fffffffu) == 0u) return asfloat(0x80000001u);
    if (b == 0xff800000u) return v;
    return asfloat((b & 0x80000000u) == 0u ? b - 1u : b + 1u);
}

M8FlowerInterval M8FlowerI(float lo, float hi)
{
    M8FlowerInterval r; r.lo = lo; r.hi = hi; return r;
}

M8FlowerInterval M8FlowerIAdd(M8FlowerInterval a, M8FlowerInterval b)
{
    precise float lo = a.lo+b.lo;
    precise float hi = a.hi+b.hi;
    return M8FlowerI(M8FlowerPrevious(lo),M8FlowerNext(hi));
}

M8FlowerInterval M8FlowerISub(M8FlowerInterval a, M8FlowerInterval b)
{
    precise float lo = a.lo-b.hi;
    precise float hi = a.hi-b.lo;
    return M8FlowerI(M8FlowerPrevious(lo),M8FlowerNext(hi));
}

M8FlowerInterval M8FlowerIMul(M8FlowerInterval a, M8FlowerInterval b)
{
    precise float4 p = float4(a.lo * b.lo, a.lo * b.hi,
        a.hi * b.lo, a.hi * b.hi);
    return M8FlowerI(M8FlowerPrevious(min(min(p.x,p.y),min(p.z,p.w))),
        M8FlowerNext(max(max(p.x,p.y),max(p.z,p.w))));
}

M8FlowerInterval M8FlowerISquare(M8FlowerInterval a)
{
    if (a.lo <= 0.0 && a.hi >= 0.0)
        return M8FlowerI(0.0,
            M8FlowerNext(max(a.lo*a.lo,a.hi*a.hi)));
    return M8FlowerIMul(a,a);
}

struct M8FlowerDyadicSquare
{
    uint2 coefficient;
    int exponent;
    uint nonzero;
};

uint2 M8FlowerMultiply24(uint a, uint b)
{
    uint a0 = a & 0xffffu;
    uint a1 = a >> 16;
    uint b0 = b & 0xffffu;
    uint b1 = b >> 16;
    uint p0 = a0*b0;
    uint p1 = a0*b1+a1*b0;
    uint lo = p0+(p1 << 16);
    uint carry = lo < p0 ? 1u : 0u;
    uint hi = (p1 >> 16)+a1*b1+carry;
    return uint2(lo,hi);
}

M8FlowerDyadicSquare M8FlowerSquareDyadic(float value)
{
    M8FlowerDyadicSquare result;
    uint bits = asuint(abs(value));
    uint exponentBits = (bits >> 23) & 0xffu;
    uint mantissa = bits & 0x7fffffu;
    result.nonzero = 0u;
    result.coefficient = 0u.xx;
    result.exponent = 0;
    if (exponentBits == 0xffu)
    {
        result.nonzero = 2u;
        return result;
    }
    if (exponentBits == 0u && mantissa == 0u)
        return result;
    int exponent = exponentBits == 0u ? -149 : (int)exponentBits-127-23;
    if (exponentBits != 0u) mantissa |= 0x800000u;
    int trailing = firstbitlow(mantissa);
    mantissa >>= trailing;
    exponent += trailing;
    result.coefficient = M8FlowerMultiply24(mantissa,mantissa);
    result.exponent = exponent*2;
    result.nonzero = 1u;
    return result;
}

uint M8FlowerBitLength(uint2 value)
{
    return value.y != 0u ? 33u+(uint)firstbithigh(value.y) :
        (value.x != 0u ? 1u+(uint)firstbithigh(value.x) : 0u);
}

bool M8FlowerEqual64(uint2 a, uint2 b)
{
    return all(a == b);
}

uint2 M8FlowerAdd64(uint2 a, uint2 b)
{
    uint lo = a.x+b.x;
    return uint2(lo,a.y+b.y+(lo < a.x ? 1u : 0u));
}

uint2 M8FlowerShiftLeft64(uint2 value, uint shift)
{
    if (shift == 0u) return value;
    if (shift < 32u)
        return uint2(value.x << shift,
            (value.y << shift) | (value.x >> (32u-shift)));
    if (shift < 64u) return uint2(0u,value.x << (shift-32u));
    return 0u.xx;
}

uint2 M8FlowerShiftRightOne64(uint2 value)
{
    return uint2((value.x >> 1) | (value.y << 31),value.y >> 1);
}

bool M8FlowerExactSquaredEquality(float a, float b, float c)
{
    M8FlowerDyadicSquare sa = M8FlowerSquareDyadic(a);
    M8FlowerDyadicSquare sb = M8FlowerSquareDyadic(b);
    M8FlowerDyadicSquare sc = M8FlowerSquareDyadic(c);
    if (sa.nonzero == 2u || sb.nonzero == 2u || sc.nonzero == 2u)
        return false;
    if (sb.nonzero == 0u && sc.nonzero == 0u)
        return sa.nonzero == 0u;
    if (sa.nonzero == 0u) return false;
    if (sb.nonzero == 0u)
        return sa.exponent == sc.exponent &&
            M8FlowerEqual64(sa.coefficient,sc.coefficient);
    if (sc.nonzero == 0u)
        return sa.exponent == sb.exponent &&
            M8FlowerEqual64(sa.coefficient,sb.coefficient);

    if (sb.exponent == sc.exponent)
    {
        uint2 sum = M8FlowerAdd64(sb.coefficient,sc.coefficient);
        return sa.exponent == sb.exponent+1 &&
            M8FlowerEqual64(sa.coefficient,M8FlowerShiftRightOne64(sum));
    }

    M8FlowerDyadicSquare low;
    M8FlowerDyadicSquare high;
    if (sb.exponent < sc.exponent)
    {
        low = sb;
        high = sc;
    }
    else
    {
        low = sc;
        high = sb;
    }
    int difference = high.exponent-low.exponent;
    if (sa.exponent != low.exponent || difference >= 64)
        return false;
    uint highBits = M8FlowerBitLength(high.coefficient);
    uint leftBits = M8FlowerBitLength(sa.coefficient);
    if (highBits+(uint)difference > leftBits)
        return false;
    uint2 sum = M8FlowerAdd64(low.coefficient,
        M8FlowerShiftLeft64(high.coefficient,(uint)difference));
    return M8FlowerEqual64(sa.coefficient,sum);
}

uint M8FlowerClassifyRoot(M8FlowerInterval3 abc)
{
    if (abc.x.lo == abc.x.hi && abc.y.lo == abc.y.hi &&
        abc.z.lo == abc.z.hi &&
        M8FlowerExactSquaredEquality(abc.x.lo,abc.y.lo,abc.z.lo))
        return abc.y.lo == 0.0 && abc.z.lo == 0.0 ?
            M8_FLOWER_ROOT_COPLANAR : M8_FLOWER_ROOT_CERTAIN_TANGENT;
    M8FlowerInterval q = M8FlowerIAdd(M8FlowerISquare(abc.y),
        M8FlowerISquare(abc.z));
    M8FlowerInterval aa = M8FlowerISquare(abc.x);
    if (q.lo == 0.0 && q.hi == 0.0)
    {
        if (abc.x.lo == abc.x.hi)
            return abc.x.lo == 0.0 ? M8_FLOWER_ROOT_COPLANAR :
                M8_FLOWER_ROOT_IMPOSSIBLE;
        return abc.x.lo <= 0.0 && abc.x.hi >= 0.0 ?
            M8_FLOWER_ROOT_AMBIGUOUS : M8_FLOWER_ROOT_IMPOSSIBLE;
    }
    if (aa.hi < q.lo) return M8_FLOWER_ROOT_CERTAIN_SECANT;
    if (aa.lo > q.hi) return M8_FLOWER_ROOT_IMPOSSIBLE;
    if (aa.lo == aa.hi && q.lo == q.hi && aa.lo == q.lo && q.lo > 0.0)
        return M8_FLOWER_ROOT_CERTAIN_TANGENT;
    return M8_FLOWER_ROOT_AMBIGUOUS;
}

int3 M8FlowerJunction(int3 kernel, int3 direction)
{
    return kernel * 2 + direction;
}

uint M8FlowerJunctionParity(int3 junction)
{
    uint3 u = asuint(junction);
    return (u.x & 1u) + (u.y & 1u) + (u.z & 1u);
}

bool M8FlowerEndpointPair(int3 junction, uint lineClass,
    out int3 first, out int3 second)
{
    int3 direction = M8FlowerLineDirection[lineClass];
    int3 doubled = junction-direction;
    if (any((asuint(doubled) & 1u) != 0u))
    {
        first = 0;
        second = 0;
        return false;
    }
    first = doubled >> 1;
    second = first+direction;
    return true;
}

float M8FlowerLevelStep(uint level)
{
    return M8_FLOWER_LATTICE_STEP / float(1u << level);
}

bool M8FlowerRoot(float3 abc, bool plusRoot, out float2 root)
{
    precise float q = abc.y*abc.y+abc.z*abc.z;
    precise float delta = q-abc.x*abc.x;
    if (!(q > 0.0) || delta < 0.0) { root = 0.0.xx; return false; }
    precise float d = sqrt(delta);
    precise float s = plusRoot ? 1.0 : -1.0;
    root = float2((-abc.x*abc.y + s*d*-abc.z)/q,
        (-abc.x*abc.z + s*d*abc.y)/q);
    return true;
}

bool M8FlowerTau(float2 from, float2 to, out float turn)
{
    precise float denominator = 1.0+dot(from,to);
    if (denominator == 0.0) { turn = 0.0; return false; }
    turn = (from.x*to.y-from.y*to.x)/denominator;
    return true;
}

float2 M8FlowerRotate(float2 root, float turn)
{
    precise float rr = turn*turn;
    precise float inverse = 1.0/(1.0+rr);
    precise float c = (1.0-rr)*inverse;
    precise float s = 2.0*turn*inverse;
    return float2(c*root.x-s*root.y,s*root.x+c*root.y);
}

float4 M8FlowerTetraForward(float4 q)
{
    precise float scalar = 0.25*(q.x+q.y+q.z+q.w);
    precise float3 tetraVector = 0.75*(q.x*M8FlowerTetraAxis[0]+
        q.y*M8FlowerTetraAxis[1]+q.z*M8FlowerTetraAxis[2]+
        q.w*M8FlowerTetraAxis[3]);
    return float4(scalar,tetraVector);
}

float4 M8FlowerTetraInverse(float scalar, float3 tetraVector)
{
    return float4(scalar+dot(M8FlowerTetraAxis[0],tetraVector),
        scalar+dot(M8FlowerTetraAxis[1],tetraVector),
        scalar+dot(M8FlowerTetraAxis[2],tetraVector),
        scalar+dot(M8FlowerTetraAxis[3],tetraVector));
}

float M8FlowerEndpointBasis(float s)
{
    precise float t=1.0-s; return 16.0*s*s*t*t;
}

float M8FlowerEndpointBasisDerivative(float s)
{
    return 32.0*s*(1.0-s)*(1.0-2.0*s);
}

void M8FlowerDeformedLoopUnit(float3 center, float sphereRadius,
    float3 direction, float3 e1, float3 e2, float2 loopUnit,
    float v, float vPrime, out float3 position, out float3 tangent)
{
    precise float rho=sqrt(0.75*sphereRadius*sphereRadius-3.0*v*v);
    precise float3 radial=e1*loopUnit.x+e2*loopUnit.y;
    precise float3 perpendicular=-e1*loopUnit.y+e2*loopUnit.x;
    precise float rhoPrime=-3.0*v*vPrime/rho;
    position=center+2.0*v*direction+rho*radial;
    tangent=2.0*vPrime*direction+rhoPrime*radial+rho*perpendicular;
}
");
        }

        private static void Define(StringBuilder output, string name,
            string value) => output.Append("#define ").Append(name).Append(' ')
            .AppendLine(value);

        private static void Comma(StringBuilder output, int index, int count) =>
            output.AppendLine(index + 1 == count ? string.Empty : ",");

        private static string Int3(int3 value) =>
            $"int3({value.x}, {value.y}, {value.z})";

        private static string Int4(int4 value) =>
            $"int4({value.x}, {value.y}, {value.z}, {value.w})";

        private static string Float2(float2 value) =>
            $"float2({Number(value.x)}, {Number(value.y)})";

        private static string Float3(float3 value) =>
            $"float3({Number(value.x)}, {Number(value.y)}, {Number(value.z)})";

        private static string CsInt3(int3 value) =>
            $"new int3({value.x}, {value.y}, {value.z})";

        private static string CsInt4(int4 value) =>
            $"new int4({value.x}, {value.y}, {value.z}, {value.w})";

        private static string CsFloat2(float2 value) =>
            $"new float2({CsNumber(value.x)}, {CsNumber(value.y)})";

        private static string CsFloat3(float3 value) =>
            $"new float3({CsNumber(value.x)}, {CsNumber(value.y)}, " +
            $"{CsNumber(value.z)})";

        private static string CsInterval(
            MerkabaSphereFlowerAuthority.FloatInterval value) =>
            $"new FloatInterval({CsNumber(value.Lower)}, " +
            $"{CsNumber(value.Upper)})";

        private static string CsNumber(float value) =>
            Number(value) + "f";

        private static string Number(float value) =>
            value.ToString("R", CultureInfo.InvariantCulture);
    }
}
