// GENERATED by MerkabaSphereFlowerCodegen. DO NOT EDIT.
#ifndef M8_DEPTH_CERTIFICATE_INCLUDED
#define M8_DEPTH_CERTIFICATE_INCLUDED
#include "MerkabaSphereFlower.generated.hlsl"
#define M8_DEPTH_CERTIFICATE_SIDE 512u
#define M8_DEPTH_CERTIFICATE_LEVELS 10u
#define M8_DEPTH_CERTIFICATE_EYE_STRIDE 349525u
#define M8_DEPTH_CERTIFICATE_STACK 64u

M8FlowerInterval M8DepthIntervalRow(float4 row, M8FlowerInterval3 positionInterval)
{
    M8FlowerInterval result=M8FlowerI(0.0,0.0);
    [loop] for(uint axis=0u;axis<3u;++axis)
    {
        M8FlowerInterval component;
        if(axis==0u)component=positionInterval.x;
        else if(axis==1u)component=positionInterval.y;
        else component=positionInterval.z;
        M8FlowerInterval product=M8FlowerIMul(M8FlowerI(row[axis],row[axis]),component);
        if(axis==0u)result=product;
        else result=M8FlowerIAdd(result,product);
    }
    return M8FlowerIAdd(result,M8FlowerI(row.w,row.w));
}

M8FlowerInterval M8FlowerObservedDot(M8FlowerInterval3 a, M8FlowerInterval3 b)
{
    M8FlowerInterval result=M8FlowerI(0.0,0.0);
    [loop] for(uint axis=0u;axis<3u;++axis)
    {
        M8FlowerInterval left,right;
        if(axis==0u){left=a.x;right=b.x;}
        else if(axis==1u){left=a.y;right=b.y;}
        else{left=a.z;right=b.z;}
        M8FlowerInterval product=M8FlowerIMul(left,right);
        if(axis==0u)result=product;
        else result=M8FlowerIAdd(result,product);
    }
    return result;
}

struct M8FlowerObservedLoopFrame
{
    M8FlowerInterval3 centre;
    M8FlowerInterval3 axis1;
    M8FlowerInterval3 axis2;
};

M8FlowerInterval3 M8FlowerObservedLoopAxis(float3 basis, M8FlowerInterval radius,
    float4x4 gridToWorld)
{
    M8FlowerInterval3 grid,world;
    grid.x = M8FlowerIMul(M8FlowerI(basis.x,basis.x),radius);
    grid.y = M8FlowerIMul(M8FlowerI(basis.y,basis.y),radius);
    grid.z = M8FlowerIMul(M8FlowerI(basis.z,basis.z),radius);
    world.x = M8DepthIntervalRow(float4(gridToWorld[0].xyz,0.0),grid);
    world.y = M8DepthIntervalRow(float4(gridToWorld[1].xyz,0.0),grid);
    world.z = M8DepthIntervalRow(float4(gridToWorld[2].xyz,0.0),grid);
    return world;
}

// The centre depends on the owner; the two axes only on the observation's
// rigid frame and line class. Callers may share axes across a whole WG.
M8FlowerInterval3 M8FlowerObservedLoopCentre(int3 owner, int3 direction,
    float4x4 gridToWorld)
{
    float3 j = (float3)M8FlowerJunction(owner,direction);
    M8FlowerInterval halfStep = M8FlowerI(M8_FLOWER_LATTICE_STEP*0.5,M8_FLOWER_LATTICE_STEP*0.5);
    M8FlowerInterval3 grid;
    grid.x = M8FlowerIMul(M8FlowerI(M8FlowerPrevious(j.x),M8FlowerNext(j.x)),halfStep);
    grid.y = M8FlowerIMul(M8FlowerI(M8FlowerPrevious(j.y),M8FlowerNext(j.y)),halfStep);
    grid.z = M8FlowerIMul(M8FlowerI(M8FlowerPrevious(j.z),M8FlowerNext(j.z)),halfStep);
    M8FlowerInterval3 centre;
    centre.x = M8DepthIntervalRow(gridToWorld[0],grid);
    centre.y = M8DepthIntervalRow(gridToWorld[1],grid);
    centre.z = M8DepthIntervalRow(gridToWorld[2],grid);
    return centre;
}

bool M8FlowerObservedLoop(int3 owner, uint direction, float4x4 gridToWorld,
    out M8FlowerObservedLoopFrame result)
{
    int4 node = M8FlowerDirectionAt(direction);
    result.centre = M8FlowerObservedLoopCentre(owner,node.xyz,gridToWorld);
    float2 bounds = M8FlowerObservedRadiusAt(node.w);
    M8FlowerInterval radius = M8FlowerI(bounds.x,bounds.y);
    result.axis1 = M8FlowerObservedLoopAxis(M8FlowerLineE1At(node.w),radius,gridToWorld);
    result.axis2 = M8FlowerObservedLoopAxis(M8FlowerLineE2At(node.w),radius,gridToWorld);
    return true;
}

M8FlowerInterval3 M8FlowerRestrictObservedPlane(M8FlowerInterval3 normal,
    M8FlowerInterval3 positionInterval, M8FlowerObservedLoopFrame frame)
{
    M8FlowerInterval3 relative,abc;
    relative.x = M8FlowerISub(frame.centre.x,positionInterval.x);
    relative.y = M8FlowerISub(frame.centre.y,positionInterval.y);
    relative.z = M8FlowerISub(frame.centre.z,positionInterval.z);
    abc.x = M8FlowerObservedDot(normal,relative);
    abc.y = M8FlowerObservedDot(normal,frame.axis1);
    abc.z = M8FlowerObservedDot(normal,frame.axis2);
    return abc;
}

// Bounds already contain the complete represented support and its metric
// uncertainty. A projective transform of a convex cube with positive w has
// its screen extrema at corners. Each corner calculation is itself enclosed.
bool M8DepthProjectSupport(float3 minimum, float3 maximum, float4x4 view,
    float4x4 projection, int2 imageSize, float reprojectionError,
    out int2 pixelMin, out int2 pixelMax,
    out float supportUpperDepth)
{
    pixelMin = imageSize;
    pixelMax = -1;
    supportUpperDepth = 0.0;
    if (!all(M8FlowerIsFinite(minimum)) || !all(M8FlowerIsFinite(maximum)) || any(maximum < minimum) ||
        any(imageSize <= 0) || any(imageSize > (int)M8_DEPTH_CERTIFICATE_SIDE) ||
        !M8FlowerIsFinite(reprojectionError) || reprojectionError < 0.0 ||
        !all(M8FlowerIsFinite(view[0])) || !all(M8FlowerIsFinite(view[1])) || !all(M8FlowerIsFinite(view[2])) ||
        !all(M8FlowerIsFinite(projection[0])) || !all(M8FlowerIsFinite(projection[1])) ||
        !all(M8FlowerIsFinite(projection[2])) || !all(M8FlowerIsFinite(projection[3])) ||
        any(view[3] != float4(0.0, 0.0, 0.0, 1.0))) return false;
    [loop]
    for (uint corner = 0u; corner < 8u; corner++)
    {
        float3 p = float3((corner & 1u) == 0u ? minimum.x : maximum.x,
            (corner & 2u) == 0u ? minimum.y : maximum.y,
            (corner & 4u) == 0u ? minimum.z : maximum.z);
        M8FlowerInterval3 world;
        world.x = M8FlowerI(p.x, p.x);
        world.y = M8FlowerI(p.y, p.y);
        world.z = M8FlowerI(p.z, p.z);
        M8FlowerInterval3 eye;
        M8FlowerInterval error = M8FlowerI(-reprojectionError, reprojectionError);
        eye.x = M8FlowerIAdd(M8DepthIntervalRow(view[0], world), error);
        eye.y = M8FlowerIAdd(M8DepthIntervalRow(view[1], world), error);
        eye.z = M8FlowerIAdd(M8DepthIntervalRow(view[2], world), error);
        if (!(eye.z.hi < 0.0)) return false;
        supportUpperDepth = max(supportUpperDepth, -eye.z.lo);
        M8FlowerInterval w = M8DepthIntervalRow(projection[3], eye);
        M8FlowerInterval projected[3];
        [loop]for(uint axis=0u;axis<3u;axis++)
            if(!M8FlowerIDivPositive(M8DepthIntervalRow(projection[axis],eye),w,
                projected[axis]))return false;
        M8FlowerInterval x=projected[0],y=projected[1],z=projected[2];
        if (z.lo < -1.0 || z.hi > 1.0) return false;
        x = M8FlowerIMul(M8FlowerIAdd(x, M8FlowerI(1.0, 1.0)),
            M8FlowerI((float)imageSize.x * 0.5, (float)imageSize.x * 0.5));
        y = M8FlowerIMul(M8FlowerIAdd(y, M8FlowerI(1.0, 1.0)),
            M8FlowerI((float)imageSize.y * 0.5, (float)imageSize.y * 0.5));
        if (!all(M8FlowerIsFinite(float4(x.lo, x.hi, y.lo, y.hi))) ||
            x.lo < 0.0 || y.lo < 0.0 || x.hi >= imageSize.x || y.hi >= imageSize.y) return false;
        pixelMin = min(pixelMin, int2(floor(x.lo), floor(y.lo)));
        pixelMax = max(pixelMax, int2(floor(x.hi), floor(y.hi)));
    }
    return M8FlowerIsFinite(supportUpperDepth);
}

uint M8DepthCertificateOffset(uint level)
{
    uint side = M8_DEPTH_CERTIFICATE_SIDE >> level;
    return (4u * M8_DEPTH_CERTIFICATE_SIDE * M8_DEPTH_CERTIFICATE_SIDE -
        4u * side * side) / 3u;
}

uint M8DepthCertificateAddress(uint eye, uint level, uint2 xy)
{
    return eye * M8_DEPTH_CERTIFICATE_EYE_STRIDE + M8DepthCertificateOffset(level) +
        xy.y * (M8_DEPTH_CERTIFICATE_SIDE >> level) + xy.x;
}

uint2 M8DepthCertificateNode(float lower, bool valid)
{
    bool accepted = valid && M8FlowerIsFinite(lower) && lower > 0.0;
    return accepted ? uint2(asuint(lower), 1u) : 0u.xx;
}

uint2 M8DepthCertificateReduce(uint2 a, uint2 b, uint2 c, uint2 d)
{
    return M8DepthCertificateNode(min(min(asfloat(a.x), asfloat(b.x)),
        min(asfloat(c.x), asfloat(d.x))), (a.y & b.y & c.y & d.y) == 1u);
}

bool M8DepthCertificateProves(uint2 node, float upper)
{
    return node.y == 1u && upper >= 0.0 && upper < asfloat(node.x);
}

uint M8DepthCertificateEnvelopeLevel(uint2 minimum, uint2 maximum)
{
    uint difference = (minimum.x ^ maximum.x) | (minimum.y ^ maximum.y);
    return difference == 0u ? 0u : (uint)firstbithigh(difference) + 1u;
}

#ifndef M8_DEPTH_CERTIFICATE_BUILD
StructuredBuffer<uint2> _M8DepthCertificate;
float4 _M8DepthErrorBounds[2];

// ---------------------------------------------------------------------------
// One dyadic cover, two entry adapters. The rules below - the admission test,
// the common-prefix query and what a node means - exist exactly once. A scalar
// caller walks them on its own stack; a cooperative caller walks the same rules
// breadth-first across its workgroup. Neither is a second geometric authority
// and neither may drift, because both call M8DepthCertificateBegin and
// M8DepthCertificateVisit and nothing else decides coverage.
// ---------------------------------------------------------------------------

// 0 = REFUSED outright, 1 = PROVED by the common prefix, 2 = descend from root.
uint M8DepthCertificateBegin(uint eye, int2 imageSize, int2 minimum,
    int2 maximum, float supportUpperDepth, out uint3 root)
{
    root = uint3(0u, 0u, 0u);
    if (eye >= 2u || any(imageSize <= 0) || any(imageSize > (int)M8_DEPTH_CERTIFICATE_SIDE) ||
        any(minimum < 0) || any(maximum < minimum) || any(maximum >= imageSize) ||
        !M8FlowerIsFinite(supportUpperDepth) || supportUpperDepth < 0.0) return 0u;
    uint level = M8DepthCertificateEnvelopeLevel((uint2)minimum, (uint2)maximum);
    root = uint3(((uint2)minimum >> level) << level, level);
    if (M8DepthCertificateProves(_M8DepthCertificate[
        M8DepthCertificateAddress(eye, level, (uint2)minimum >> level)],
        supportUpperDepth)) return 1u;
    return 2u;
}

// 0 = node proved, 1 = node refutes the whole support, 2 = split into 4,
// 3 = node lies outside the support and contributes nothing.
uint M8DepthCertificateVisit(uint eye, uint3 node, int2 minimum, int2 maximum,
    float supportUpperDepth)
{
    uint2 lo = node.xy;
    uint2 hi = lo + (1u << node.z) - 1u;
    if (any(hi < (uint2)minimum) || any(lo > (uint2)maximum)) return 3u;
    if (node.z == 0u || (all(lo >= (uint2)minimum) && all(hi <= (uint2)maximum)))
        return M8DepthCertificateProves(_M8DepthCertificate[
            M8DepthCertificateAddress(eye, node.z, lo >> node.z)],
            supportUpperDepth) ? 0u : 1u;
    return 2u;
}

// The four children of a split node that still meet the support. Shared so the
// two adapters enumerate children in one order and one containment rule.
uint M8DepthCertificateChildren(uint3 node, int2 minimum, int2 maximum,
    out uint3 children[4])
{
    uint childLevel = node.z - 1u;
    uint childSide = 1u << childLevel;
    uint produced = 0u;
    [unroll]
    for (int child = 3; child >= 0; child--)
    {
        uint2 childLo = node.xy + uint2((uint)child & 1u, (uint)child >> 1u) * childSide;
        uint2 childHi = childLo + childSide - 1u;
        if (any(childHi < (uint2)minimum) || any(childLo > (uint2)maximum)) continue;
        children[produced++] = uint3(childLo, childLevel);
    }
    [unroll]
    for (uint pad = produced; pad < 4u; pad++) children[pad] = uint3(0u, 0u, 0u);
    return produced;
}

// False means AMBIGUOUS, never NOT_THROUGH. Direct endpoint intersection
// is a separate predicate and takes precedence over this negative evidence.
bool M8DepthCertificateThrough(uint eye, int2 imageSize, int2 minimum,
    int2 maximum, float supportUpperDepth)
{
    uint3 root;
    uint begin = M8DepthCertificateBegin(eye, imageSize, minimum, maximum,
        supportUpperDepth, root);
    if (begin != 2u) return begin == 1u;

    uint3 stack[M8_DEPTH_CERTIFICATE_STACK];
    uint count = 1u;
    stack[0] = root;
    [loop]
    while (count != 0u)
    {
        uint3 node = stack[--count];
        uint verdict = M8DepthCertificateVisit(eye, node, minimum, maximum,
            supportUpperDepth);
        if (verdict == 1u) return false;
        if (verdict != 2u) continue;
        uint3 children[4];
        uint produced = M8DepthCertificateChildren(node, minimum, maximum, children);
        [loop]
        for (uint child = 0u; child < produced; child++)
        {
            if (count == M8_DEPTH_CERTIFICATE_STACK) return false;
            stack[count++] = children[child];
        }
    }
    return true;
}

#ifdef M8_DEPTH_CERTIFICATE_COOPERATIVE
// The cooperative adapter. Same Begin, same Visit, same Children as the scalar
// walk above; only the traversal order differs - breadth-first across the
// workgroup instead of depth-first on one lane's private stack. A dyadic cover
// is a conjunction over the nodes it selects, and conjunction does not care in
// which order its terms are evaluated, so this returns what the scalar adapter
// returns for the same support.
//
// Overflow stays conservative on both sides: the scalar walk refuses when its
// stack is full, this refuses when the level frontier is, and refusing means
// AMBIGUOUS, never THROUGH. The two limits are reached on different supports,
// so overflow is the one case where the adapters may disagree - and they
// disagree only by both being safe.
//
// EVERY lane of the workgroup must reach this call. It carries workgroup
// barriers, so it may not be entered from a lane-divergent branch.
#define M8_DEPTH_CERTIFICATE_FRONTIER 128u
groupshared uint3 gM8CertFrontier[2][M8_DEPTH_CERTIFICATE_FRONTIER];
groupshared uint gM8CertFrontierCount[2];
groupshared uint gM8CertBegin;
groupshared uint gM8CertRefuted;

bool M8DepthCertificateThroughShared(uint eye, int2 imageSize, int2 minimum,
    int2 maximum, float supportUpperDepth, uint lane, uint laneCount)
{
    if (lane == 0u)
    {
        uint3 root;
        gM8CertBegin = M8DepthCertificateBegin(eye, imageSize, minimum, maximum,
            supportUpperDepth, root);
        gM8CertRefuted = 0u;
        gM8CertFrontierCount[0] = (gM8CertBegin == 2u) ? 1u : 0u;
        gM8CertFrontierCount[1] = 0u;
        gM8CertFrontier[0][0] = root;
    }
    GroupMemoryBarrierWithGroupSync();
    if (gM8CertBegin != 2u) return gM8CertBegin == 1u;

    uint source = 0u;
    // The frontier descends one certificate level per iteration and the root
    // level is bounded by the pyramid, so this cannot spin.
    [loop]
    for (uint level = 0u; level <= M8_DEPTH_CERTIFICATE_LEVELS; level++)
    {
        // Uniform across the workgroup: every lane reads the same groupshared
        // count behind the same barrier, so this break is not divergent.
        uint count = gM8CertFrontierCount[source];
        if (count == 0u) break;
        uint target = 1u - source;
        [loop]
        for (uint index = lane; index < count; index += laneCount)
        {
            uint3 node = gM8CertFrontier[source][index];
            uint verdict = M8DepthCertificateVisit(eye, node, minimum, maximum,
                supportUpperDepth);
            if (verdict == 1u) { InterlockedOr(gM8CertRefuted, 1u); continue; }
            if (verdict != 2u) continue;
            uint3 children[4];
            uint produced = M8DepthCertificateChildren(node, minimum, maximum,
                children);
            if (produced == 0u) continue;
            uint base;
            InterlockedAdd(gM8CertFrontierCount[target], produced, base);
            if (base + produced > M8_DEPTH_CERTIFICATE_FRONTIER)
            {
                InterlockedOr(gM8CertRefuted, 1u);
                continue;
            }
            [loop]
            for (uint child = 0u; child < produced; child++)
                gM8CertFrontier[target][base + child] = children[child];
        }
        GroupMemoryBarrierWithGroupSync();
        if (gM8CertRefuted != 0u) return false;
        if (lane == 0u) gM8CertFrontierCount[source] = 0u;
        source = target;
        GroupMemoryBarrierWithGroupSync();
    }
    return true;
}
#endif

bool M8DepthCertificateEyeSupport(float3 minimum, float3 maximum,
    float4x4 view, float4x4 projection, int2 imageSize, uint eye)
{
    if (eye >= 2u) return false;
    float4 errors = _M8DepthErrorBounds[eye];
    if (errors.w != 1.0 || !all(M8FlowerIsFinite(errors.xyz)) || any(errors.xyz < 0.0)) return false;
    int2 lo, hi;
    float upper;
    return M8DepthProjectSupport(minimum, maximum, view, projection,
            imageSize, errors.y, lo, hi, upper) &&
        M8DepthCertificateThrough(eye, imageSize, lo, hi, upper);
}

#ifdef M8_DEPTH_CERTIFICATE_COOPERATIVE
// The cooperative twin of the call above. The admission test and the interval
// projection are the same text executed by every lane on the same inputs, so
// every lane derives the same lo/hi/upper; only the cover is shared out. It
// carries the barriers of M8DepthCertificateThroughShared and therefore has
// the same rule: the whole workgroup enters, or none of it does.
bool M8DepthCertificateEyeSupportShared(float3 minimum, float3 maximum,
    float4x4 view, float4x4 projection, int2 imageSize, uint eye,
    uint lane, uint laneCount)
{
    float4 errors = _M8DepthErrorBounds[eye];
    int2 lo, hi;
    float upper;
    bool projected = eye < 2u && errors.w == 1.0 &&
        all(M8FlowerIsFinite(errors.xyz)) && !any(errors.xyz < 0.0) &&
        M8DepthProjectSupport(minimum, maximum, view, projection,
            imageSize, errors.y, lo, hi, upper);
    // Uniform: the guard above reads no lane-varying state, so either every
    // lane reaches the shared cover or none does.
    if (!projected) return false;
    return M8DepthCertificateThroughShared(eye, imageSize, lo, hi, upper,
        lane, laneCount);
}
#endif

// 0 = NOT_THROUGH (direct endpoint), 1 = THROUGH_CERTAIN, 2 = AMBIGUOUS.
// The endpoint predicate is evaluated for the SAME frozen observation before
// either eye's free-space certificate can be applied to this support.
uint M8DepthCertificateStereoSupport(float3 minimum, float3 maximum,
    float4x4 views[2], float4x4 projections[2], int2 imageSize,
    bool strictEndpointIntersects)
{
    if (strictEndpointIntersects) return 0u;
    [unroll]
    for (uint eye = 0u; eye < 2u; eye++)
    {
        if (M8DepthCertificateEyeSupport(minimum, maximum, views[eye],
                projections[eye], imageSize, eye)) return 1u;
    }
    return 2u;
}
#endif
#endif
