// GENERATED by MerkabaSphereFlowerCodegen. DO NOT EDIT.
// Exact finite tables from MerkabaSphereFlowerAuthority.
#ifndef GENESIS_MERKABA_SPHERE_FLOWER_INCLUDED
#define GENESIS_MERKABA_SPHERE_FLOWER_INCLUDED
#define M8_FLOWER_LATTICE_STEP 0.025
#define M8_FLOWER_LEVEL_COUNT 6u
#define M8_FLOWER_DIRECTION_COUNT 26u
#define M8_FLOWER_LINE_CLASS_COUNT 13u
#define M8_FLOWER_NODE_CLASS_COUNT 26u
#define M8_FLOWER_STRAND_CLASS_COUNT 72u
#define M8_FLOWER_PETAL_CLASS_COUNT 48u
#define M8_FLOWER_SECTOR_BOUNDARY_COUNT 132u
#define M8_FLOWER_TABLE_HASH 0xbd5650e9u
#define M8_FLOWER_ROOT_IMPOSSIBLE 0u
#define M8_FLOWER_ROOT_CERTAIN_TANGENT 1u
#define M8_FLOWER_ROOT_CERTAIN_SECANT 2u
#define M8_FLOWER_ROOT_COPLANAR 3u
#define M8_FLOWER_ROOT_AMBIGUOUS 4u

static const int3 M8FlowerLineDirection[13] = {
    int3(1, 0, 0),
    int3(0, 1, 0),
    int3(0, 0, 1),
    int3(1, 1, 0),
    int3(1, -1, 0),
    int3(1, 0, 1),
    int3(1, 0, -1),
    int3(0, 1, 1),
    int3(0, 1, -1),
    int3(1, 1, 1),
    int3(1, 1, -1),
    int3(1, -1, 1),
    int3(1, -1, -1)
};
static const float3 M8FlowerLineUnit[13] = {
    float3(1, 0, 0),
    float3(0, 1, 0),
    float3(0, 0, 1),
    float3(0.707106769, 0.707106769, 0),
    float3(0.707106769, -0.707106769, 0),
    float3(0.707106769, 0, 0.707106769),
    float3(0.707106769, 0, -0.707106769),
    float3(0, 0.707106769, 0.707106769),
    float3(0, 0.707106769, -0.707106769),
    float3(0.577350259, 0.577350259, 0.577350259),
    float3(0.577350259, 0.577350259, -0.577350259),
    float3(0.577350259, -0.577350259, 0.577350259),
    float3(0.577350259, -0.577350259, -0.577350259)
};
static const float3 M8FlowerLineE1[13] = {
    float3(0, 1, 0),
    float3(1, 0, 0),
    float3(1, 0, 0),
    float3(0, 0, 1),
    float3(0, 0, 1),
    float3(0, 1, 0),
    float3(0, 1, 0),
    float3(1, 0, 0),
    float3(1, 0, 0),
    float3(0.816496551, -0.408248246, -0.408248246),
    float3(0.816496551, -0.408248246, 0.408248246),
    float3(0.816496551, 0.408248246, -0.408248246),
    float3(0.816496551, 0.408248246, 0.408248246)
};
static const float3 M8FlowerLineE2[13] = {
    float3(0, 0, 1),
    float3(0, 0, -1),
    float3(0, 1, 0),
    float3(0.707106769, -0.707106769, 0),
    float3(-0.707106769, -0.707106769, 0),
    float3(-0.707106769, 0, 0.707106769),
    float3(0.707106769, 0, 0.707106769),
    float3(0, 0.707106769, -0.707106769),
    float3(0, -0.707106769, -0.707106769),
    float3(0, 0.7071067, -0.7071067),
    float3(0, -0.7071067, -0.7071067),
    float3(0, 0.7071067, 0.7071067),
    float3(0, -0.7071067, 0.7071067)
};
static const uint3 M8FlowerLineMeta[13] = {
    uint3(1u, 0u, 16u),
    uint3(1u, 16u, 16u),
    uint3(1u, 32u, 16u),
    uint3(2u, 48u, 6u),
    uint3(2u, 54u, 6u),
    uint3(2u, 60u, 6u),
    uint3(2u, 66u, 6u),
    uint3(2u, 72u, 6u),
    uint3(2u, 78u, 6u),
    uint3(3u, 84u, 12u),
    uint3(3u, 96u, 12u),
    uint3(3u, 108u, 12u),
    uint3(3u, 120u, 12u)
};
static const int4 M8FlowerDirection[26] = {
    int4(1, 0, 0, 0),
    int4(-1, 0, 0, 0),
    int4(0, 1, 0, 1),
    int4(0, -1, 0, 1),
    int4(0, 0, 1, 2),
    int4(0, 0, -1, 2),
    int4(1, 1, 0, 3),
    int4(-1, -1, 0, 3),
    int4(1, -1, 0, 4),
    int4(-1, 1, 0, 4),
    int4(1, 0, 1, 5),
    int4(-1, 0, -1, 5),
    int4(1, 0, -1, 6),
    int4(-1, 0, 1, 6),
    int4(0, 1, 1, 7),
    int4(0, -1, -1, 7),
    int4(0, 1, -1, 8),
    int4(0, -1, 1, 8),
    int4(1, 1, 1, 9),
    int4(-1, -1, -1, 9),
    int4(1, 1, -1, 10),
    int4(-1, -1, 1, 10),
    int4(1, -1, 1, 11),
    int4(-1, 1, -1, 11),
    int4(1, -1, -1, 12),
    int4(-1, 1, 1, 12)
};
static const int2 M8FlowerDirectionMeta[26] = {
    int2(1, 1),
    int2(-1, 1),
    int2(1, 1),
    int2(-1, 1),
    int2(1, 1),
    int2(-1, 1),
    int2(1, 2),
    int2(-1, 2),
    int2(1, 2),
    int2(-1, 2),
    int2(1, 2),
    int2(-1, 2),
    int2(1, 2),
    int2(-1, 2),
    int2(1, 2),
    int2(-1, 2),
    int2(1, 2),
    int2(-1, 2),
    int2(1, 3),
    int2(-1, 3),
    int2(1, 3),
    int2(-1, 3),
    int2(1, 3),
    int2(-1, 3),
    int2(1, 3),
    int2(-1, 3)
};
static const int4 M8FlowerNode[26] = {
    int4(1, 0, 0, 0),
    int4(-1, 0, 0, 0),
    int4(0, 1, 0, 1),
    int4(0, -1, 0, 1),
    int4(0, 0, 1, 2),
    int4(0, 0, -1, 2),
    int4(1, 1, 0, 3),
    int4(-1, -1, 0, 3),
    int4(1, -1, 0, 4),
    int4(-1, 1, 0, 4),
    int4(1, 0, 1, 5),
    int4(-1, 0, -1, 5),
    int4(1, 0, -1, 6),
    int4(-1, 0, 1, 6),
    int4(0, 1, 1, 7),
    int4(0, -1, -1, 7),
    int4(0, 1, -1, 8),
    int4(0, -1, 1, 8),
    int4(1, 1, 1, 9),
    int4(-1, -1, -1, 9),
    int4(1, 1, -1, 10),
    int4(-1, -1, 1, 10),
    int4(1, -1, 1, 11),
    int4(-1, 1, -1, 11),
    int4(1, -1, -1, 12),
    int4(-1, 1, 1, 12)
};
static const uint4 M8FlowerStrand[72] = {
    uint4(1u, 7u, 0u, 256u),
    uint4(7u, 19u, 1u, 4096u),
    uint4(1u, 19u, 2u, 1024u),
    uint4(7u, 21u, 1u, 4353u),
    uint4(1u, 21u, 2u, 1537u),
    uint4(1u, 9u, 0u, 770u),
    uint4(9u, 23u, 1u, 6146u),
    uint4(1u, 23u, 2u, 1282u),
    uint4(9u, 25u, 1u, 6403u),
    uint4(1u, 25u, 2u, 1795u),
    uint4(1u, 11u, 0u, 1284u),
    uint4(11u, 19u, 1u, 8196u),
    uint4(11u, 23u, 1u, 8453u),
    uint4(1u, 13u, 0u, 1798u),
    uint4(13u, 21u, 1u, 10246u),
    uint4(13u, 25u, 1u, 10503u),
    uint4(0u, 8u, 0u, 2312u),
    uint4(8u, 24u, 1u, 4616u),
    uint4(0u, 24u, 2u, 3080u),
    uint4(8u, 22u, 1u, 4873u),
    uint4(0u, 22u, 2u, 3593u),
    uint4(0u, 6u, 0u, 2826u),
    uint4(6u, 20u, 1u, 6666u),
    uint4(0u, 20u, 2u, 3338u),
    uint4(6u, 18u, 1u, 6923u),
    uint4(0u, 18u, 2u, 3851u),
    uint4(0u, 12u, 0u, 3340u),
    uint4(12u, 24u, 1u, 8716u),
    uint4(12u, 20u, 1u, 8973u),
    uint4(0u, 10u, 0u, 3854u),
    uint4(10u, 22u, 1u, 10766u),
    uint4(10u, 18u, 1u, 11023u),
    uint4(3u, 7u, 0u, 4368u),
    uint4(3u, 19u, 2u, 5136u),
    uint4(3u, 21u, 2u, 5649u),
    uint4(3u, 8u, 0u, 4882u),
    uint4(3u, 24u, 2u, 5394u),
    uint4(3u, 22u, 2u, 5907u),
    uint4(3u, 15u, 0u, 5396u),
    uint4(15u, 19u, 1u, 9236u),
    uint4(15u, 24u, 1u, 9493u),
    uint4(3u, 17u, 0u, 5910u),
    uint4(17u, 21u, 1u, 11286u),
    uint4(17u, 22u, 1u, 11543u),
    uint4(2u, 9u, 0u, 6424u),
    uint4(2u, 23u, 2u, 7192u),
    uint4(2u, 25u, 2u, 7705u),
    uint4(2u, 6u, 0u, 6938u),
    uint4(2u, 20u, 2u, 7450u),
    uint4(2u, 18u, 2u, 7963u),
    uint4(2u, 16u, 0u, 7452u),
    uint4(16u, 23u, 1u, 9756u),
    uint4(16u, 20u, 1u, 10013u),
    uint4(2u, 14u, 0u, 7966u),
    uint4(14u, 25u, 1u, 11806u),
    uint4(14u, 18u, 1u, 12063u),
    uint4(5u, 11u, 0u, 8480u),
    uint4(5u, 19u, 2u, 9248u),
    uint4(5u, 23u, 2u, 9761u),
    uint4(5u, 12u, 0u, 8994u),
    uint4(5u, 24u, 2u, 9506u),
    uint4(5u, 20u, 2u, 10019u),
    uint4(5u, 15u, 0u, 9508u),
    uint4(5u, 16u, 0u, 10022u),
    uint4(4u, 13u, 0u, 10536u),
    uint4(4u, 21u, 2u, 11304u),
    uint4(4u, 25u, 2u, 11817u),
    uint4(4u, 10u, 0u, 11050u),
    uint4(4u, 22u, 2u, 11562u),
    uint4(4u, 18u, 2u, 12075u),
    uint4(4u, 17u, 0u, 11564u),
    uint4(4u, 14u, 0u, 12078u)
};
static const uint4 M8FlowerPetalNodes[48] = {
    uint4(1u, 7u, 19u, 0u),
    uint4(1u, 7u, 21u, 1u),
    uint4(1u, 9u, 23u, 1u),
    uint4(1u, 9u, 25u, 0u),
    uint4(1u, 11u, 19u, 1u),
    uint4(1u, 11u, 23u, 0u),
    uint4(1u, 13u, 21u, 0u),
    uint4(1u, 13u, 25u, 1u),
    uint4(0u, 8u, 24u, 1u),
    uint4(0u, 8u, 22u, 0u),
    uint4(0u, 6u, 20u, 0u),
    uint4(0u, 6u, 18u, 1u),
    uint4(0u, 12u, 24u, 0u),
    uint4(0u, 12u, 20u, 1u),
    uint4(0u, 10u, 22u, 1u),
    uint4(0u, 10u, 18u, 0u),
    uint4(3u, 7u, 19u, 1u),
    uint4(3u, 7u, 21u, 0u),
    uint4(3u, 8u, 24u, 0u),
    uint4(3u, 8u, 22u, 1u),
    uint4(3u, 15u, 19u, 0u),
    uint4(3u, 15u, 24u, 1u),
    uint4(3u, 17u, 21u, 1u),
    uint4(3u, 17u, 22u, 0u),
    uint4(2u, 9u, 23u, 0u),
    uint4(2u, 9u, 25u, 1u),
    uint4(2u, 6u, 20u, 1u),
    uint4(2u, 6u, 18u, 0u),
    uint4(2u, 16u, 23u, 1u),
    uint4(2u, 16u, 20u, 0u),
    uint4(2u, 14u, 25u, 0u),
    uint4(2u, 14u, 18u, 1u),
    uint4(5u, 11u, 19u, 0u),
    uint4(5u, 11u, 23u, 1u),
    uint4(5u, 12u, 24u, 1u),
    uint4(5u, 12u, 20u, 0u),
    uint4(5u, 15u, 19u, 1u),
    uint4(5u, 15u, 24u, 0u),
    uint4(5u, 16u, 23u, 0u),
    uint4(5u, 16u, 20u, 1u),
    uint4(4u, 13u, 21u, 1u),
    uint4(4u, 13u, 25u, 0u),
    uint4(4u, 10u, 22u, 0u),
    uint4(4u, 10u, 18u, 1u),
    uint4(4u, 17u, 21u, 0u),
    uint4(4u, 17u, 22u, 1u),
    uint4(4u, 14u, 25u, 1u),
    uint4(4u, 14u, 18u, 0u)
};
static const uint3 M8FlowerPetalStrands[48] = {
    uint3(0u, 1u, 2u),
    uint3(0u, 3u, 4u),
    uint3(5u, 6u, 7u),
    uint3(5u, 8u, 9u),
    uint3(10u, 11u, 2u),
    uint3(10u, 12u, 7u),
    uint3(13u, 14u, 4u),
    uint3(13u, 15u, 9u),
    uint3(16u, 17u, 18u),
    uint3(16u, 19u, 20u),
    uint3(21u, 22u, 23u),
    uint3(21u, 24u, 25u),
    uint3(26u, 27u, 18u),
    uint3(26u, 28u, 23u),
    uint3(29u, 30u, 20u),
    uint3(29u, 31u, 25u),
    uint3(32u, 1u, 33u),
    uint3(32u, 3u, 34u),
    uint3(35u, 17u, 36u),
    uint3(35u, 19u, 37u),
    uint3(38u, 39u, 33u),
    uint3(38u, 40u, 36u),
    uint3(41u, 42u, 34u),
    uint3(41u, 43u, 37u),
    uint3(44u, 6u, 45u),
    uint3(44u, 8u, 46u),
    uint3(47u, 22u, 48u),
    uint3(47u, 24u, 49u),
    uint3(50u, 51u, 45u),
    uint3(50u, 52u, 48u),
    uint3(53u, 54u, 46u),
    uint3(53u, 55u, 49u),
    uint3(56u, 11u, 57u),
    uint3(56u, 12u, 58u),
    uint3(59u, 27u, 60u),
    uint3(59u, 28u, 61u),
    uint3(62u, 39u, 57u),
    uint3(62u, 40u, 60u),
    uint3(63u, 51u, 58u),
    uint3(63u, 52u, 61u),
    uint3(64u, 14u, 65u),
    uint3(64u, 15u, 66u),
    uint3(67u, 30u, 68u),
    uint3(67u, 31u, 69u),
    uint3(70u, 42u, 65u),
    uint3(70u, 43u, 68u),
    uint3(71u, 54u, 66u),
    uint3(71u, 55u, 69u)
};
static const int3 M8FlowerPetalStrandSign[48] = {
    int3(-1, -1, 1),
    int3(1, 1, -1),
    int3(1, 1, -1),
    int3(-1, -1, 1),
    int3(1, 1, -1),
    int3(-1, -1, 1),
    int3(-1, -1, 1),
    int3(1, 1, -1),
    int3(1, 1, -1),
    int3(-1, -1, 1),
    int3(-1, -1, 1),
    int3(1, 1, -1),
    int3(-1, -1, 1),
    int3(1, 1, -1),
    int3(1, 1, -1),
    int3(-1, -1, 1),
    int3(1, 1, -1),
    int3(-1, -1, 1),
    int3(-1, -1, 1),
    int3(1, 1, -1),
    int3(-1, -1, 1),
    int3(1, 1, -1),
    int3(1, 1, -1),
    int3(-1, -1, 1),
    int3(-1, -1, 1),
    int3(1, 1, -1),
    int3(1, 1, -1),
    int3(-1, -1, 1),
    int3(1, 1, -1),
    int3(-1, -1, 1),
    int3(-1, -1, 1),
    int3(1, 1, -1),
    int3(-1, -1, 1),
    int3(1, 1, -1),
    int3(1, 1, -1),
    int3(-1, -1, 1),
    int3(1, 1, -1),
    int3(-1, -1, 1),
    int3(-1, -1, 1),
    int3(1, 1, -1),
    int3(1, 1, -1),
    int3(-1, -1, 1),
    int3(-1, -1, 1),
    int3(1, 1, -1),
    int3(-1, -1, 1),
    int3(1, 1, -1),
    int3(1, 1, -1),
    int3(-1, -1, 1)
};
static const uint3 M8FlowerChildPetal[4] = {
    uint3(2u, 5u, 17u),
    uint3(5u, 8u, 20u),
    uint3(17u, 20u, 32u),
    uint3(5u, 20u, 17u)
};
static const float4 M8FlowerSectorBounds[132] = {
    float4(0.9855985, 0.985598564, 0.169101968, 0.169101983),
    float4(0.816496551, 0.8164966, 0.577350259, 0.5773503),
    float4(0.577350259, 0.5773503, 0.816496551, 0.8164966),
    float4(0.169101968, 0.169101983, 0.9855985, 0.985598564),
    float4(-0.169101983, -0.169101968, 0.9855985, 0.985598564),
    float4(-0.5773503, -0.577350259, 0.816496551, 0.8164966),
    float4(-0.8164966, -0.816496551, 0.577350259, 0.5773503),
    float4(-0.985598564, -0.9855985, 0.169101968, 0.169101983),
    float4(-0.985598564, -0.9855985, -0.169101983, -0.169101968),
    float4(-0.8164966, -0.816496551, -0.5773503, -0.577350259),
    float4(-0.5773503, -0.577350259, -0.8164966, -0.816496551),
    float4(-0.169101983, -0.169101968, -0.985598564, -0.9855985),
    float4(0.169101968, 0.169101983, -0.985598564, -0.9855985),
    float4(0.577350259, 0.5773503, -0.8164966, -0.816496551),
    float4(0.816496551, 0.8164966, -0.5773503, -0.577350259),
    float4(0.9855985, 0.985598564, -0.169101983, -0.169101968),
    float4(0.9855985, 0.985598564, 0.169101968, 0.169101983),
    float4(0.816496551, 0.8164966, 0.577350259, 0.5773503),
    float4(0.577350259, 0.5773503, 0.816496551, 0.8164966),
    float4(0.169101968, 0.169101983, 0.9855985, 0.985598564),
    float4(-0.169101983, -0.169101968, 0.9855985, 0.985598564),
    float4(-0.5773503, -0.577350259, 0.816496551, 0.8164966),
    float4(-0.8164966, -0.816496551, 0.577350259, 0.5773503),
    float4(-0.985598564, -0.9855985, 0.169101968, 0.169101983),
    float4(-0.985598564, -0.9855985, -0.169101983, -0.169101968),
    float4(-0.8164966, -0.816496551, -0.5773503, -0.577350259),
    float4(-0.5773503, -0.577350259, -0.8164966, -0.816496551),
    float4(-0.169101983, -0.169101968, -0.985598564, -0.9855985),
    float4(0.169101968, 0.169101983, -0.985598564, -0.9855985),
    float4(0.577350259, 0.5773503, -0.8164966, -0.816496551),
    float4(0.816496551, 0.8164966, -0.5773503, -0.577350259),
    float4(0.9855985, 0.985598564, -0.169101983, -0.169101968),
    float4(0.9855985, 0.985598564, 0.169101968, 0.169101983),
    float4(0.816496551, 0.8164966, 0.577350259, 0.5773503),
    float4(0.577350259, 0.5773503, 0.816496551, 0.8164966),
    float4(0.169101968, 0.169101983, 0.9855985, 0.985598564),
    float4(-0.169101983, -0.169101968, 0.9855985, 0.985598564),
    float4(-0.5773503, -0.577350259, 0.816496551, 0.8164966),
    float4(-0.8164966, -0.816496551, 0.577350259, 0.5773503),
    float4(-0.985598564, -0.9855985, 0.169101968, 0.169101983),
    float4(-0.985598564, -0.9855985, -0.169101983, -0.169101968),
    float4(-0.8164966, -0.816496551, -0.5773503, -0.577350259),
    float4(-0.5773503, -0.577350259, -0.8164966, -0.816496551),
    float4(-0.169101983, -0.169101968, -0.985598564, -0.9855985),
    float4(0.169101968, 0.169101983, -0.985598564, -0.9855985),
    float4(0.577350259, 0.5773503, -0.8164966, -0.816496551),
    float4(0.816496551, 0.8164966, -0.5773503, -0.577350259),
    float4(0.9855985, 0.985598564, -0.169101983, -0.169101968),
    float4(0.99999994, 1, 0, 0),
    float4(0.408248276, 0.4082483, 0.9128709, 0.912870944),
    float4(-0.4082483, -0.408248276, 0.9128709, 0.912870944),
    float4(-1, -0.99999994, 0, 0),
    float4(-0.4082483, -0.408248276, -0.912870944, -0.9128709),
    float4(0.408248276, 0.4082483, -0.912870944, -0.9128709),
    float4(0.99999994, 1, 0, 0),
    float4(0.408248276, 0.4082483, 0.9128709, 0.912870944),
    float4(-0.4082483, -0.408248276, 0.9128709, 0.912870944),
    float4(-1, -0.99999994, 0, 0),
    float4(-0.4082483, -0.408248276, -0.912870944, -0.9128709),
    float4(0.408248276, 0.4082483, -0.912870944, -0.9128709),
    float4(0.99999994, 1, 0, 0),
    float4(0.408248276, 0.4082483, 0.9128709, 0.912870944),
    float4(-0.4082483, -0.408248276, 0.9128709, 0.912870944),
    float4(-1, -0.99999994, 0, 0),
    float4(-0.4082483, -0.408248276, -0.912870944, -0.9128709),
    float4(0.408248276, 0.4082483, -0.912870944, -0.9128709),
    float4(0.99999994, 1, 0, 0),
    float4(0.408248276, 0.4082483, 0.9128709, 0.912870944),
    float4(-0.4082483, -0.408248276, 0.9128709, 0.912870944),
    float4(-1, -0.99999994, 0, 0),
    float4(-0.4082483, -0.408248276, -0.912870944, -0.9128709),
    float4(0.408248276, 0.4082483, -0.912870944, -0.9128709),
    float4(0.99999994, 1, 0, 0),
    float4(0.408248276, 0.4082483, 0.9128709, 0.912870944),
    float4(-0.4082483, -0.408248276, 0.9128709, 0.912870944),
    float4(-1, -0.99999994, 0, 0),
    float4(-0.4082483, -0.408248276, -0.912870944, -0.9128709),
    float4(0.408248276, 0.4082483, -0.912870944, -0.9128709),
    float4(0.99999994, 1, 0, 0),
    float4(0.408248276, 0.4082483, 0.9128709, 0.912870944),
    float4(-0.4082483, -0.408248276, 0.9128709, 0.912870944),
    float4(-1, -0.99999994, 0, 0),
    float4(-0.4082483, -0.408248276, -0.912870944, -0.9128709),
    float4(0.408248276, 0.4082483, -0.912870944, -0.9128709),
    float4(0.9082482, 0.908248246, 0.41843158, 0.4184316),
    float4(0.8660253, 0.8660254, 0.49999994, 0.49999997),
    float4(0, 0, 0.9999999, 0.99999994),
    float4(-0.09175171, -0.0917517, 0.9957818, 0.995781839),
    float4(-0.816496551, -0.8164965, 0.5773502, 0.577350259),
    float4(-0.8660254, -0.8660253, 0.49999994, 0.49999997),
    float4(-0.8660254, -0.8660253, -0.49999997, -0.49999994),
    float4(-0.816496551, -0.8164965, -0.577350259, -0.5773502),
    float4(-0.09175171, -0.0917517, -0.995781839, -0.9957818),
    float4(0, 0, -0.99999994, -0.9999999),
    float4(0.8660253, 0.8660254, -0.49999997, -0.49999994),
    float4(0.9082482, 0.908248246, -0.4184316, -0.41843158),
    float4(0.9082482, 0.908248246, 0.41843158, 0.4184316),
    float4(0.8660253, 0.8660254, 0.49999994, 0.49999997),
    float4(0, 0, 0.9999999, 0.99999994),
    float4(-0.09175171, -0.0917517, 0.9957818, 0.995781839),
    float4(-0.816496551, -0.8164965, 0.5773502, 0.577350259),
    float4(-0.8660254, -0.8660253, 0.49999994, 0.49999997),
    float4(-0.8660254, -0.8660253, -0.49999997, -0.49999994),
    float4(-0.816496551, -0.8164965, -0.577350259, -0.5773502),
    float4(-0.09175171, -0.0917517, -0.995781839, -0.9957818),
    float4(0, 0, -0.99999994, -0.9999999),
    float4(0.8660253, 0.8660254, -0.49999997, -0.49999994),
    float4(0.9082482, 0.908248246, -0.4184316, -0.41843158),
    float4(0.9082482, 0.908248246, 0.41843158, 0.4184316),
    float4(0.8660253, 0.8660254, 0.49999994, 0.49999997),
    float4(0, 0, 0.9999999, 0.99999994),
    float4(-0.09175171, -0.0917517, 0.9957818, 0.995781839),
    float4(-0.816496551, -0.8164965, 0.5773502, 0.577350259),
    float4(-0.8660254, -0.8660253, 0.49999994, 0.49999997),
    float4(-0.8660254, -0.8660253, -0.49999997, -0.49999994),
    float4(-0.816496551, -0.8164965, -0.577350259, -0.5773502),
    float4(-0.09175171, -0.0917517, -0.995781839, -0.9957818),
    float4(0, 0, -0.99999994, -0.9999999),
    float4(0.8660253, 0.8660254, -0.49999997, -0.49999994),
    float4(0.9082482, 0.908248246, -0.4184316, -0.41843158),
    float4(0.9082482, 0.908248246, 0.41843158, 0.4184316),
    float4(0.8660253, 0.8660254, 0.49999994, 0.49999997),
    float4(0, 0, 0.9999999, 0.99999994),
    float4(-0.09175171, -0.0917517, 0.9957818, 0.995781839),
    float4(-0.816496551, -0.8164965, 0.5773502, 0.577350259),
    float4(-0.8660254, -0.8660253, 0.49999994, 0.49999997),
    float4(-0.8660254, -0.8660253, -0.49999997, -0.49999994),
    float4(-0.816496551, -0.8164965, -0.577350259, -0.5773502),
    float4(-0.09175171, -0.0917517, -0.995781839, -0.9957818),
    float4(0, 0, -0.99999994, -0.9999999),
    float4(0.8660253, 0.8660254, -0.49999997, -0.49999994),
    float4(0.9082482, 0.908248246, -0.4184316, -0.41843158)
};
static const float2 M8FlowerSectorUnit[132] = {
    float2(0.985598564, 0.169101983),
    float2(0.8164966, 0.577350259),
    float2(0.577350259, 0.8164966),
    float2(0.169101983, 0.985598564),
    float2(-0.169101983, 0.985598564),
    float2(-0.577350259, 0.8164966),
    float2(-0.8164966, 0.577350259),
    float2(-0.985598564, 0.169101983),
    float2(-0.985598564, -0.169101983),
    float2(-0.8164966, -0.577350259),
    float2(-0.577350259, -0.8164966),
    float2(-0.169101983, -0.985598564),
    float2(0.169101983, -0.985598564),
    float2(0.577350259, -0.8164966),
    float2(0.8164966, -0.577350259),
    float2(0.985598564, -0.169101983),
    float2(0.985598564, 0.169101983),
    float2(0.8164966, 0.577350259),
    float2(0.577350259, 0.8164966),
    float2(0.169101983, 0.985598564),
    float2(-0.169101983, 0.985598564),
    float2(-0.577350259, 0.8164966),
    float2(-0.8164966, 0.577350259),
    float2(-0.985598564, 0.169101983),
    float2(-0.985598564, -0.169101983),
    float2(-0.8164966, -0.577350259),
    float2(-0.577350259, -0.8164966),
    float2(-0.169101983, -0.985598564),
    float2(0.169101983, -0.985598564),
    float2(0.577350259, -0.8164966),
    float2(0.8164966, -0.577350259),
    float2(0.985598564, -0.169101983),
    float2(0.985598564, 0.169101983),
    float2(0.8164966, 0.577350259),
    float2(0.577350259, 0.8164966),
    float2(0.169101983, 0.985598564),
    float2(-0.169101983, 0.985598564),
    float2(-0.577350259, 0.8164966),
    float2(-0.8164966, 0.577350259),
    float2(-0.985598564, 0.169101983),
    float2(-0.985598564, -0.169101983),
    float2(-0.8164966, -0.577350259),
    float2(-0.577350259, -0.8164966),
    float2(-0.169101983, -0.985598564),
    float2(0.169101983, -0.985598564),
    float2(0.577350259, -0.8164966),
    float2(0.8164966, -0.577350259),
    float2(0.985598564, -0.169101983),
    float2(1, 0),
    float2(0.4082483, 0.9128709),
    float2(-0.4082483, 0.9128709),
    float2(-1, 0),
    float2(-0.4082483, -0.9128709),
    float2(0.4082483, -0.9128709),
    float2(1, 0),
    float2(0.4082483, 0.9128709),
    float2(-0.4082483, 0.9128709),
    float2(-1, 0),
    float2(-0.4082483, -0.9128709),
    float2(0.4082483, -0.9128709),
    float2(1, 0),
    float2(0.4082483, 0.9128709),
    float2(-0.4082483, 0.9128709),
    float2(-1, 0),
    float2(-0.4082483, -0.9128709),
    float2(0.4082483, -0.9128709),
    float2(1, 0),
    float2(0.4082483, 0.9128709),
    float2(-0.4082483, 0.9128709),
    float2(-1, 0),
    float2(-0.4082483, -0.9128709),
    float2(0.4082483, -0.9128709),
    float2(1, 0),
    float2(0.4082483, 0.9128709),
    float2(-0.4082483, 0.9128709),
    float2(-1, 0),
    float2(-0.4082483, -0.9128709),
    float2(0.4082483, -0.9128709),
    float2(1, 0),
    float2(0.4082483, 0.9128709),
    float2(-0.4082483, 0.9128709),
    float2(-1, 0),
    float2(-0.4082483, -0.9128709),
    float2(0.4082483, -0.9128709),
    float2(0.908248246, 0.4184316),
    float2(0.8660253, 0.49999994),
    float2(0, 0.9999999),
    float2(-0.0917517, 0.995781839),
    float2(-0.816496551, 0.5773502),
    float2(-0.8660253, 0.49999994),
    float2(-0.8660253, -0.49999994),
    float2(-0.816496551, -0.5773502),
    float2(-0.0917517, -0.995781839),
    float2(0, -0.9999999),
    float2(0.8660253, -0.49999994),
    float2(0.908248246, -0.4184316),
    float2(0.908248246, 0.4184316),
    float2(0.8660253, 0.49999994),
    float2(0, 0.9999999),
    float2(-0.0917517, 0.995781839),
    float2(-0.816496551, 0.5773502),
    float2(-0.8660253, 0.49999994),
    float2(-0.8660253, -0.49999994),
    float2(-0.816496551, -0.5773502),
    float2(-0.0917517, -0.995781839),
    float2(0, -0.9999999),
    float2(0.8660253, -0.49999994),
    float2(0.908248246, -0.4184316),
    float2(0.908248246, 0.4184316),
    float2(0.8660253, 0.49999994),
    float2(0, 0.9999999),
    float2(-0.0917517, 0.995781839),
    float2(-0.816496551, 0.5773502),
    float2(-0.8660253, 0.49999994),
    float2(-0.8660253, -0.49999994),
    float2(-0.816496551, -0.5773502),
    float2(-0.0917517, -0.995781839),
    float2(0, -0.9999999),
    float2(0.8660253, -0.49999994),
    float2(0.908248246, -0.4184316),
    float2(0.908248246, 0.4184316),
    float2(0.8660253, 0.49999994),
    float2(0, 0.9999999),
    float2(-0.0917517, 0.995781839),
    float2(-0.816496551, 0.5773502),
    float2(-0.8660253, 0.49999994),
    float2(-0.8660253, -0.49999994),
    float2(-0.816496551, -0.5773502),
    float2(-0.0917517, -0.995781839),
    float2(0, -0.9999999),
    float2(0.8660253, -0.49999994),
    float2(0.908248246, -0.4184316)
};
static const int4 M8FlowerTetraLine[8] = {
    int4(9, 12, 11, 10),
    int4(12, 9, 10, 11),
    int4(11, 10, 9, 12),
    int4(10, 11, 12, 9),
    int4(10, 11, 12, 9),
    int4(11, 10, 9, 12),
    int4(12, 9, 10, 11),
    int4(9, 12, 11, 10)
};
static const int4 M8FlowerTetraEta[8] = {
    int4(1, 1, -1, -1),
    int4(-1, -1, 1, 1),
    int4(1, 1, -1, -1),
    int4(-1, -1, 1, 1),
    int4(1, 1, -1, -1),
    int4(-1, -1, 1, 1),
    int4(1, 1, -1, -1),
    int4(-1, -1, 1, 1)
};
static const int M8FlowerTetraChirality[8] = {
    -1,
    1,
    1,
    -1,
    1,
    -1,
    -1,
    1
};
static const float3 M8FlowerTetraAxis[4] = {
    float3(0.5773502691896258, 0.5773502691896258, 0.5773502691896258),
    float3(0.5773502691896258, -0.5773502691896258, -0.5773502691896258),
    float3(-0.5773502691896258, 0.5773502691896258, -0.5773502691896258),
    float3(-0.5773502691896258, -0.5773502691896258, 0.5773502691896258)
};

struct M8FlowerInterval { float lo; float hi; };
struct M8FlowerInterval2 { M8FlowerInterval x; M8FlowerInterval y; };
struct M8FlowerInterval3 { M8FlowerInterval x; M8FlowerInterval y; M8FlowerInterval z; };

float M8FlowerNext(float v)
{
    uint b = asuint(v);
    if ((b & 0x7fffffffu) == 0u) return asfloat(1u);
    if (b == 0x7f800000u) return v;
    return asfloat((b & 0x80000000u) == 0u ? b + 1u : b - 1u);
}

float M8FlowerPrevious(float v)
{
    uint b = asuint(v);
    if ((b & 0x7fffffffu) == 0u) return asfloat(0x80000001u);
    if (b == 0xff800000u) return v;
    return asfloat((b & 0x80000000u) == 0u ? b - 1u : b + 1u);
}

M8FlowerInterval M8FlowerI(float lo, float hi)
{
    M8FlowerInterval r; r.lo = lo; r.hi = hi; return r;
}

M8FlowerInterval M8FlowerIAdd(M8FlowerInterval a, M8FlowerInterval b)
{
    precise float lo = a.lo+b.lo;
    precise float hi = a.hi+b.hi;
    return M8FlowerI(M8FlowerPrevious(lo),M8FlowerNext(hi));
}

M8FlowerInterval M8FlowerISub(M8FlowerInterval a, M8FlowerInterval b)
{
    precise float lo = a.lo-b.hi;
    precise float hi = a.hi-b.lo;
    return M8FlowerI(M8FlowerPrevious(lo),M8FlowerNext(hi));
}

M8FlowerInterval M8FlowerIMul(M8FlowerInterval a, M8FlowerInterval b)
{
    precise float4 p = float4(a.lo * b.lo, a.lo * b.hi,
        a.hi * b.lo, a.hi * b.hi);
    return M8FlowerI(M8FlowerPrevious(min(min(p.x,p.y),min(p.z,p.w))),
        M8FlowerNext(max(max(p.x,p.y),max(p.z,p.w))));
}

M8FlowerInterval M8FlowerISquare(M8FlowerInterval a)
{
    if (a.lo <= 0.0 && a.hi >= 0.0)
        return M8FlowerI(0.0,
            M8FlowerNext(max(a.lo*a.lo,a.hi*a.hi)));
    return M8FlowerIMul(a,a);
}

struct M8FlowerDyadicSquare
{
    uint2 coefficient;
    int exponent;
    uint nonzero;
};

uint2 M8FlowerMultiply24(uint a, uint b)
{
    uint a0 = a & 0xffffu;
    uint a1 = a >> 16;
    uint b0 = b & 0xffffu;
    uint b1 = b >> 16;
    uint p0 = a0*b0;
    uint p1 = a0*b1+a1*b0;
    uint lo = p0+(p1 << 16);
    uint carry = lo < p0 ? 1u : 0u;
    uint hi = (p1 >> 16)+a1*b1+carry;
    return uint2(lo,hi);
}

M8FlowerDyadicSquare M8FlowerSquareDyadic(float value)
{
    M8FlowerDyadicSquare result;
    uint bits = asuint(abs(value));
    uint exponentBits = (bits >> 23) & 0xffu;
    uint mantissa = bits & 0x7fffffu;
    result.nonzero = 0u;
    result.coefficient = 0u.xx;
    result.exponent = 0;
    if (exponentBits == 0xffu)
    {
        result.nonzero = 2u;
        return result;
    }
    if (exponentBits == 0u && mantissa == 0u)
        return result;
    int exponent = exponentBits == 0u ? -149 : (int)exponentBits-127-23;
    if (exponentBits != 0u) mantissa |= 0x800000u;
    int trailing = firstbitlow(mantissa);
    mantissa >>= trailing;
    exponent += trailing;
    result.coefficient = M8FlowerMultiply24(mantissa,mantissa);
    result.exponent = exponent*2;
    result.nonzero = 1u;
    return result;
}

uint M8FlowerBitLength(uint2 value)
{
    return value.y != 0u ? 33u+(uint)firstbithigh(value.y) :
        (value.x != 0u ? 1u+(uint)firstbithigh(value.x) : 0u);
}

bool M8FlowerEqual64(uint2 a, uint2 b)
{
    return all(a == b);
}

uint2 M8FlowerAdd64(uint2 a, uint2 b)
{
    uint lo = a.x+b.x;
    return uint2(lo,a.y+b.y+(lo < a.x ? 1u : 0u));
}

uint2 M8FlowerShiftLeft64(uint2 value, uint shift)
{
    if (shift == 0u) return value;
    if (shift < 32u)
        return uint2(value.x << shift,
            (value.y << shift) | (value.x >> (32u-shift)));
    if (shift < 64u) return uint2(0u,value.x << (shift-32u));
    return 0u.xx;
}

uint2 M8FlowerShiftRightOne64(uint2 value)
{
    return uint2((value.x >> 1) | (value.y << 31),value.y >> 1);
}

bool M8FlowerExactSquaredEquality(float a, float b, float c)
{
    M8FlowerDyadicSquare sa = M8FlowerSquareDyadic(a);
    M8FlowerDyadicSquare sb = M8FlowerSquareDyadic(b);
    M8FlowerDyadicSquare sc = M8FlowerSquareDyadic(c);
    if (sa.nonzero == 2u || sb.nonzero == 2u || sc.nonzero == 2u)
        return false;
    if (sb.nonzero == 0u && sc.nonzero == 0u)
        return sa.nonzero == 0u;
    if (sa.nonzero == 0u) return false;
    if (sb.nonzero == 0u)
        return sa.exponent == sc.exponent &&
            M8FlowerEqual64(sa.coefficient,sc.coefficient);
    if (sc.nonzero == 0u)
        return sa.exponent == sb.exponent &&
            M8FlowerEqual64(sa.coefficient,sb.coefficient);

    if (sb.exponent == sc.exponent)
    {
        uint2 sum = M8FlowerAdd64(sb.coefficient,sc.coefficient);
        return sa.exponent == sb.exponent+1 &&
            M8FlowerEqual64(sa.coefficient,M8FlowerShiftRightOne64(sum));
    }

    M8FlowerDyadicSquare low;
    M8FlowerDyadicSquare high;
    if (sb.exponent < sc.exponent)
    {
        low = sb;
        high = sc;
    }
    else
    {
        low = sc;
        high = sb;
    }
    int difference = high.exponent-low.exponent;
    if (sa.exponent != low.exponent || difference >= 64)
        return false;
    uint highBits = M8FlowerBitLength(high.coefficient);
    uint leftBits = M8FlowerBitLength(sa.coefficient);
    if (highBits+(uint)difference > leftBits)
        return false;
    uint2 sum = M8FlowerAdd64(low.coefficient,
        M8FlowerShiftLeft64(high.coefficient,(uint)difference));
    return M8FlowerEqual64(sa.coefficient,sum);
}

uint M8FlowerClassifyRoot(M8FlowerInterval3 abc)
{
    if (abc.x.lo == abc.x.hi && abc.y.lo == abc.y.hi &&
        abc.z.lo == abc.z.hi &&
        M8FlowerExactSquaredEquality(abc.x.lo,abc.y.lo,abc.z.lo))
        return abc.y.lo == 0.0 && abc.z.lo == 0.0 ?
            M8_FLOWER_ROOT_COPLANAR : M8_FLOWER_ROOT_CERTAIN_TANGENT;
    M8FlowerInterval q = M8FlowerIAdd(M8FlowerISquare(abc.y),
        M8FlowerISquare(abc.z));
    M8FlowerInterval aa = M8FlowerISquare(abc.x);
    if (q.lo == 0.0 && q.hi == 0.0)
    {
        if (abc.x.lo == abc.x.hi)
            return abc.x.lo == 0.0 ? M8_FLOWER_ROOT_COPLANAR :
                M8_FLOWER_ROOT_IMPOSSIBLE;
        return abc.x.lo <= 0.0 && abc.x.hi >= 0.0 ?
            M8_FLOWER_ROOT_AMBIGUOUS : M8_FLOWER_ROOT_IMPOSSIBLE;
    }
    if (aa.hi < q.lo) return M8_FLOWER_ROOT_CERTAIN_SECANT;
    if (aa.lo > q.hi) return M8_FLOWER_ROOT_IMPOSSIBLE;
    if (aa.lo == aa.hi && q.lo == q.hi && aa.lo == q.lo && q.lo > 0.0)
        return M8_FLOWER_ROOT_CERTAIN_TANGENT;
    return M8_FLOWER_ROOT_AMBIGUOUS;
}

int3 M8FlowerJunction(int3 kernel, int3 direction)
{
    return kernel * 2 + direction;
}

uint M8FlowerJunctionParity(int3 junction)
{
    uint3 u = asuint(junction);
    return (u.x & 1u) + (u.y & 1u) + (u.z & 1u);
}

bool M8FlowerEndpointPair(int3 junction, uint lineClass,
    out int3 first, out int3 second)
{
    int3 direction = M8FlowerLineDirection[lineClass];
    int3 doubled = junction-direction;
    if (any((asuint(doubled) & 1u) != 0u))
    {
        first = 0;
        second = 0;
        return false;
    }
    first = doubled >> 1;
    second = first+direction;
    return true;
}

float M8FlowerLevelStep(uint level)
{
    return M8_FLOWER_LATTICE_STEP / float(1u << level);
}

bool M8FlowerRoot(float3 abc, bool plusRoot, out float2 root)
{
    precise float q = abc.y*abc.y+abc.z*abc.z;
    precise float delta = q-abc.x*abc.x;
    if (!(q > 0.0) || delta < 0.0) { root = 0.0.xx; return false; }
    precise float d = sqrt(delta);
    precise float s = plusRoot ? 1.0 : -1.0;
    root = float2((-abc.x*abc.y + s*d*-abc.z)/q,
        (-abc.x*abc.z + s*d*abc.y)/q);
    return true;
}

bool M8FlowerTau(float2 from, float2 to, out float turn)
{
    precise float denominator = 1.0+dot(from,to);
    if (denominator == 0.0) { turn = 0.0; return false; }
    turn = (from.x*to.y-from.y*to.x)/denominator;
    return true;
}

float2 M8FlowerRotate(float2 root, float turn)
{
    precise float rr = turn*turn;
    precise float inverse = 1.0/(1.0+rr);
    precise float c = (1.0-rr)*inverse;
    precise float s = 2.0*turn*inverse;
    return float2(c*root.x-s*root.y,s*root.x+c*root.y);
}

float4 M8FlowerTetraForward(float4 q)
{
    precise float scalar = 0.25*(q.x+q.y+q.z+q.w);
    precise float3 tetraVector = 0.75*(q.x*M8FlowerTetraAxis[0]+
        q.y*M8FlowerTetraAxis[1]+q.z*M8FlowerTetraAxis[2]+
        q.w*M8FlowerTetraAxis[3]);
    return float4(scalar,tetraVector);
}

float4 M8FlowerTetraInverse(float scalar, float3 tetraVector)
{
    return float4(scalar+dot(M8FlowerTetraAxis[0],tetraVector),
        scalar+dot(M8FlowerTetraAxis[1],tetraVector),
        scalar+dot(M8FlowerTetraAxis[2],tetraVector),
        scalar+dot(M8FlowerTetraAxis[3],tetraVector));
}

float M8FlowerEndpointBasis(float s)
{
    precise float t=1.0-s; return 16.0*s*s*t*t;
}

float M8FlowerEndpointBasisDerivative(float s)
{
    return 32.0*s*(1.0-s)*(1.0-2.0*s);
}

void M8FlowerDeformedLoopUnit(float3 center, float sphereRadius,
    float3 direction, float3 e1, float3 e2, float2 loopUnit,
    float v, float vPrime, out float3 position, out float3 tangent)
{
    precise float rho=sqrt(0.75*sphereRadius*sphereRadius-3.0*v*v);
    precise float3 radial=e1*loopUnit.x+e2*loopUnit.y;
    precise float3 perpendicular=-e1*loopUnit.y+e2*loopUnit.x;
    precise float rhoPrime=-3.0*v*vPrime/rho;
    position=center+2.0*v*direction+rho*radial;
    tangent=2.0*vPrime*direction+rhoPrime*radial+rho*perpendicular;
}

#endif
