// GENERATED by MerkabaSphereFlowerCodegen. DO NOT EDIT.
#ifndef M8_DEPTH_CERTIFICATE_INCLUDED
#define M8_DEPTH_CERTIFICATE_INCLUDED
#include "MerkabaSphereFlower.generated.hlsl"
#define M8_DEPTH_CERTIFICATE_SIDE 512u
#define M8_DEPTH_CERTIFICATE_LEVELS 10u
#define M8_DEPTH_CERTIFICATE_EYE_STRIDE 349525u
#define M8_DEPTH_CERTIFICATE_STACK 64u

M8FlowerInterval M8DepthIntervalRow(float4 row, M8FlowerInterval3 positionInterval)
{
    return M8FlowerIAdd(M8FlowerIAdd(M8FlowerIAdd(
        M8FlowerIMul(M8FlowerI(row.x, row.x), positionInterval.x),
        M8FlowerIMul(M8FlowerI(row.y, row.y), positionInterval.y)),
        M8FlowerIMul(M8FlowerI(row.z, row.z), positionInterval.z)), M8FlowerI(row.w, row.w));
}

M8FlowerInterval M8FlowerObservedDot(M8FlowerInterval3 a, M8FlowerInterval3 b)
{
    return M8FlowerIAdd(M8FlowerIAdd(M8FlowerIMul(a.x,b.x),M8FlowerIMul(a.y,b.y)),
        M8FlowerIMul(a.z,b.z));
}

struct M8FlowerObservedLoopFrame
{
    M8FlowerInterval3 centre;
    M8FlowerInterval3 axis1;
    M8FlowerInterval3 axis2;
};

M8FlowerInterval3 M8FlowerObservedLoopAxis(float3 basis, M8FlowerInterval radius,
    float4x4 gridToWorld)
{
    M8FlowerInterval3 grid,world;
    grid.x = M8FlowerIMul(M8FlowerI(basis.x,basis.x),radius);
    grid.y = M8FlowerIMul(M8FlowerI(basis.y,basis.y),radius);
    grid.z = M8FlowerIMul(M8FlowerI(basis.z,basis.z),radius);
    world.x = M8DepthIntervalRow(float4(gridToWorld[0].xyz,0.0),grid);
    world.y = M8DepthIntervalRow(float4(gridToWorld[1].xyz,0.0),grid);
    world.z = M8DepthIntervalRow(float4(gridToWorld[2].xyz,0.0),grid);
    return world;
}

// Same generated loop in the held observation's world frame. Integer
// conversion, radius and matrix operations are enclosed before ABC, so large
// translated/negative coordinates cannot silently lose a root bound.
bool M8FlowerObservedLoop(int3 owner, uint direction, float4x4 gridToWorld,
    out M8FlowerObservedLoopFrame result)
{
    result = (M8FlowerObservedLoopFrame)0;
    int4 node = M8FlowerDirection[direction];
    float3 j = (float3)M8FlowerJunction(owner,node.xyz);
    M8FlowerInterval halfStep = M8FlowerI(M8_FLOWER_LATTICE_STEP*0.5,M8_FLOWER_LATTICE_STEP*0.5);
    M8FlowerInterval3 grid;
    grid.x = M8FlowerIMul(M8FlowerI(M8FlowerPrevious(j.x),M8FlowerNext(j.x)),halfStep);
    grid.y = M8FlowerIMul(M8FlowerI(M8FlowerPrevious(j.y),M8FlowerNext(j.y)),halfStep);
    grid.z = M8FlowerIMul(M8FlowerI(M8FlowerPrevious(j.z),M8FlowerNext(j.z)),halfStep);
    result.centre.x = M8DepthIntervalRow(gridToWorld[0],grid);
    result.centre.y = M8DepthIntervalRow(gridToWorld[1],grid);
    result.centre.z = M8DepthIntervalRow(gridToWorld[2],grid);
    M8FlowerInterval step = M8FlowerI(M8_FLOWER_LATTICE_STEP,M8_FLOWER_LATTICE_STEP);
    float shellFactor = 0.75*(float)M8FlowerLineMeta[node.w].x;
    M8FlowerInterval radius;
    if (!M8FlowerISqrt(M8FlowerIMul(M8FlowerIMul(step,step),
            M8FlowerI(shellFactor,shellFactor)),radius)) return false;
    result.axis1 = M8FlowerObservedLoopAxis(M8FlowerLineE1[node.w],radius,gridToWorld);
    result.axis2 = M8FlowerObservedLoopAxis(M8FlowerLineE2[node.w],radius,gridToWorld);
    return true;
}

M8FlowerInterval3 M8FlowerRestrictObservedPlane(M8FlowerInterval3 normal,
    M8FlowerInterval3 positionInterval, M8FlowerObservedLoopFrame frame)
{
    M8FlowerInterval3 relative,abc;
    relative.x = M8FlowerISub(frame.centre.x,positionInterval.x);
    relative.y = M8FlowerISub(frame.centre.y,positionInterval.y);
    relative.z = M8FlowerISub(frame.centre.z,positionInterval.z);
    abc.x = M8FlowerObservedDot(normal,relative);
    abc.y = M8FlowerObservedDot(normal,frame.axis1);
    abc.z = M8FlowerObservedDot(normal,frame.axis2);
    return abc;
}

// Bounds already contain the complete represented support and its metric
// uncertainty. A projective transform of a convex cube with positive w has
// its screen extrema at corners. Each corner calculation is itself enclosed.
bool M8DepthProjectSupport(float3 minimum, float3 maximum, float4x4 view,
    float4x4 projection, int2 imageSize, float reprojectionError,
    out int2 pixelMin, out int2 pixelMax,
    out float supportUpperDepth)
{
    pixelMin = imageSize;
    pixelMax = -1;
    supportUpperDepth = 0.0;
    if (!all(isfinite(minimum)) || !all(isfinite(maximum)) || any(maximum < minimum) ||
        any(imageSize <= 0) || any(imageSize > (int)M8_DEPTH_CERTIFICATE_SIDE) ||
        !isfinite(reprojectionError) || reprojectionError < 0.0 ||
        !all(isfinite(view[0])) || !all(isfinite(view[1])) || !all(isfinite(view[2])) ||
        !all(isfinite(projection[0])) || !all(isfinite(projection[1])) ||
        !all(isfinite(projection[2])) || !all(isfinite(projection[3])) ||
        any(view[3] != float4(0.0, 0.0, 0.0, 1.0))) return false;
    [unroll]
    for (uint corner = 0u; corner < 8u; corner++)
    {
        float3 p = float3((corner & 1u) == 0u ? minimum.x : maximum.x,
            (corner & 2u) == 0u ? minimum.y : maximum.y,
            (corner & 4u) == 0u ? minimum.z : maximum.z);
        M8FlowerInterval3 world;
        world.x = M8FlowerI(p.x, p.x);
        world.y = M8FlowerI(p.y, p.y);
        world.z = M8FlowerI(p.z, p.z);
        M8FlowerInterval3 eye;
        M8FlowerInterval error = M8FlowerI(-reprojectionError, reprojectionError);
        eye.x = M8FlowerIAdd(M8DepthIntervalRow(view[0], world), error);
        eye.y = M8FlowerIAdd(M8DepthIntervalRow(view[1], world), error);
        eye.z = M8FlowerIAdd(M8DepthIntervalRow(view[2], world), error);
        if (!(eye.z.hi < 0.0)) return false;
        supportUpperDepth = max(supportUpperDepth, -eye.z.lo);
        M8FlowerInterval w = M8DepthIntervalRow(projection[3], eye);
        M8FlowerInterval x, y, z;
        if (!M8FlowerIDivPositive(M8DepthIntervalRow(projection[0], eye), w, x) ||
            !M8FlowerIDivPositive(M8DepthIntervalRow(projection[1], eye), w, y) ||
            !M8FlowerIDivPositive(M8DepthIntervalRow(projection[2], eye), w, z)) return false;
        if (z.lo < -1.0 || z.hi > 1.0) return false;
        x = M8FlowerIMul(M8FlowerIAdd(x, M8FlowerI(1.0, 1.0)),
            M8FlowerI((float)imageSize.x * 0.5, (float)imageSize.x * 0.5));
        y = M8FlowerIMul(M8FlowerIAdd(y, M8FlowerI(1.0, 1.0)),
            M8FlowerI((float)imageSize.y * 0.5, (float)imageSize.y * 0.5));
        if (!all(isfinite(float4(x.lo, x.hi, y.lo, y.hi))) ||
            x.lo < 0.0 || y.lo < 0.0 || x.hi >= imageSize.x || y.hi >= imageSize.y) return false;
        pixelMin = min(pixelMin, int2(floor(x.lo), floor(y.lo)));
        pixelMax = max(pixelMax, int2(floor(x.hi), floor(y.hi)));
    }
    return isfinite(supportUpperDepth);
}

uint M8DepthCertificateOffset(uint level)
{
    uint side = M8_DEPTH_CERTIFICATE_SIDE >> level;
    return (4u * M8_DEPTH_CERTIFICATE_SIDE * M8_DEPTH_CERTIFICATE_SIDE -
        4u * side * side) / 3u;
}

uint M8DepthCertificateAddress(uint eye, uint level, uint2 xy)
{
    return eye * M8_DEPTH_CERTIFICATE_EYE_STRIDE + M8DepthCertificateOffset(level) +
        xy.y * (M8_DEPTH_CERTIFICATE_SIDE >> level) + xy.x;
}

uint2 M8DepthCertificateNode(float lower, bool valid)
{
    bool accepted = valid && isfinite(lower) && lower > 0.0;
    return accepted ? uint2(asuint(lower), 1u) : 0u.xx;
}

uint2 M8DepthCertificateReduce(uint2 a, uint2 b, uint2 c, uint2 d)
{
    return M8DepthCertificateNode(min(min(asfloat(a.x), asfloat(b.x)),
        min(asfloat(c.x), asfloat(d.x))), (a.y & b.y & c.y & d.y) == 1u);
}

bool M8DepthCertificateProves(uint2 node, float upper)
{
    return node.y == 1u && upper >= 0.0 && upper < asfloat(node.x);
}

uint M8DepthCertificateEnvelopeLevel(uint2 minimum, uint2 maximum)
{
    uint difference = (minimum.x ^ maximum.x) | (minimum.y ^ maximum.y);
    return difference == 0u ? 0u : (uint)firstbithigh(difference) + 1u;
}

#ifndef M8_DEPTH_CERTIFICATE_BUILD
StructuredBuffer<uint2> _M8DepthCertificate;
float4 _M8DepthErrorBounds[2];

// False means AMBIGUOUS, never NOT_THROUGH. Direct endpoint intersection
// is a separate predicate and takes precedence over this negative evidence.
bool M8DepthCertificateThrough(uint eye, int2 imageSize, int2 minimum,
    int2 maximum, float supportUpperDepth)
{
    if (eye >= 2u || any(imageSize <= 0) || any(imageSize > (int)M8_DEPTH_CERTIFICATE_SIDE) ||
        any(minimum < 0) || any(maximum < minimum) || any(maximum >= imageSize) ||
        !isfinite(supportUpperDepth) || supportUpperDepth < 0.0) return false;
    uint level = M8DepthCertificateEnvelopeLevel((uint2)minimum, (uint2)maximum);
    uint2 origin = ((uint2)minimum >> level) << level;
    if (M8DepthCertificateProves(_M8DepthCertificate[
        M8DepthCertificateAddress(eye, level, (uint2)minimum >> level)],
        supportUpperDepth)) return true;

    uint3 stack[M8_DEPTH_CERTIFICATE_STACK];
    uint count = 1u;
    stack[0] = uint3(origin, level);
    [loop]
    while (count != 0u)
    {
        uint3 node = stack[--count];
        uint2 lo = node.xy;
        uint2 hi = lo + (1u << node.z) - 1u;
        if (any(hi < (uint2)minimum) || any(lo > (uint2)maximum)) continue;
        if (node.z == 0u || (all(lo >= (uint2)minimum) && all(hi <= (uint2)maximum)))
        {
            if (!M8DepthCertificateProves(_M8DepthCertificate[
                M8DepthCertificateAddress(eye, node.z, lo >> node.z)],
                supportUpperDepth)) return false;
            continue;
        }
        uint childLevel = node.z - 1u;
        uint childSide = 1u << childLevel;
        [unroll]
        for (int child = 3; child >= 0; child--)
        {
            uint2 childLo = lo + uint2((uint)child & 1u, (uint)child >> 1u) * childSide;
            uint2 childHi = childLo + childSide - 1u;
            if (any(childHi < (uint2)minimum) || any(childLo > (uint2)maximum)) continue;
            if (count == M8_DEPTH_CERTIFICATE_STACK) return false;
            stack[count++] = uint3(childLo, childLevel);
        }
    }
    return true;
}

bool M8DepthCertificateEyeSupport(float3 minimum, float3 maximum,
    float4x4 view, float4x4 projection, int2 imageSize, uint eye)
{
    if (eye >= 2u) return false;
    float4 errors = _M8DepthErrorBounds[eye];
    if (errors.w != 1.0 || !all(isfinite(errors.xyz)) || any(errors.xyz < 0.0)) return false;
    int2 lo, hi;
    float upper;
    return M8DepthProjectSupport(minimum, maximum, view, projection,
            imageSize, errors.y, lo, hi, upper) &&
        M8DepthCertificateThrough(eye, imageSize, lo, hi, upper);
}

// 0 = NOT_THROUGH (direct endpoint), 1 = THROUGH_CERTAIN, 2 = AMBIGUOUS.
// The endpoint predicate is evaluated for the SAME frozen observation before
// either eye's free-space certificate can be applied to this support.
uint M8DepthCertificateStereoSupport(float3 minimum, float3 maximum,
    float4x4 views[2], float4x4 projections[2], int2 imageSize,
    bool strictEndpointIntersects)
{
    if (strictEndpointIntersects) return 0u;
    [unroll]
    for (uint eye = 0u; eye < 2u; eye++)
    {
        if (M8DepthCertificateEyeSupport(minimum, maximum, views[eye],
                projections[eye], imageSize, eye)) return 1u;
    }
    return 2u;
}
#endif
#endif
