// GENERATED by MerkabaSphereFlowerCodegen. DO NOT EDIT.
#ifndef M8_OBSERVATION_PROJECTION_INCLUDED
#define M8_OBSERVATION_PROJECTION_INCLUDED
#include "MerkabaSphereFlower.generated.hlsl"
#define M8_OBSERVATION_IMAGE_SIDE 512u
float4 _M8DepthErrorBounds[2];

M8FlowerInterval M8DepthIntervalRow(float4 row, M8FlowerInterval3 positionInterval)
{
    M8FlowerInterval result=M8FlowerI(0.0,0.0);
    [loop] for(uint axis=0u;axis<3u;++axis)
    {
        M8FlowerInterval component;
        if(axis==0u)component=positionInterval.x;
        else if(axis==1u)component=positionInterval.y;
        else component=positionInterval.z;
        M8FlowerInterval product=M8FlowerIMul(M8FlowerI(row[axis],row[axis]),component);
        if(axis==0u)result=product;
        else result=M8FlowerIAdd(result,product);
    }
    return M8FlowerIAdd(result,M8FlowerI(row.w,row.w));
}

M8FlowerInterval M8FlowerObservedDot(M8FlowerInterval3 a, M8FlowerInterval3 b)
{
    M8FlowerInterval result=M8FlowerI(0.0,0.0);
    [loop] for(uint axis=0u;axis<3u;++axis)
    {
        M8FlowerInterval left,right;
        if(axis==0u){left=a.x;right=b.x;}
        else if(axis==1u){left=a.y;right=b.y;}
        else{left=a.z;right=b.z;}
        M8FlowerInterval product=M8FlowerIMul(left,right);
        if(axis==0u)result=product;
        else result=M8FlowerIAdd(result,product);
    }
    return result;
}

struct M8FlowerObservedLoopFrame
{
    M8FlowerInterval3 centre;
    M8FlowerInterval3 axis1;
    M8FlowerInterval3 axis2;
};

M8FlowerInterval3 M8FlowerObservedLoopAxis(float3 basis, M8FlowerInterval radius,
    float4x4 gridToWorld)
{
    M8FlowerInterval3 grid,world;
    grid.x = M8FlowerIMul(M8FlowerI(basis.x,basis.x),radius);
    grid.y = M8FlowerIMul(M8FlowerI(basis.y,basis.y),radius);
    grid.z = M8FlowerIMul(M8FlowerI(basis.z,basis.z),radius);
    world.x = M8DepthIntervalRow(float4(gridToWorld[0].xyz,0.0),grid);
    world.y = M8DepthIntervalRow(float4(gridToWorld[1].xyz,0.0),grid);
    world.z = M8DepthIntervalRow(float4(gridToWorld[2].xyz,0.0),grid);
    return world;
}

// The centre depends on the owner; the two axes only on the observation's
// rigid frame and line class. Callers may share axes across a whole WG.
M8FlowerInterval3 M8FlowerObservedLoopCentre(int3 owner, int3 direction,
    float4x4 gridToWorld)
{
    float3 j = (float3)M8FlowerJunction(owner,direction);
    M8FlowerInterval halfStep = M8FlowerI(M8_FLOWER_LATTICE_STEP*0.5,M8_FLOWER_LATTICE_STEP*0.5);
    M8FlowerInterval3 grid;
    grid.x = M8FlowerIMul(M8FlowerI(M8FlowerPrevious(j.x),M8FlowerNext(j.x)),halfStep);
    grid.y = M8FlowerIMul(M8FlowerI(M8FlowerPrevious(j.y),M8FlowerNext(j.y)),halfStep);
    grid.z = M8FlowerIMul(M8FlowerI(M8FlowerPrevious(j.z),M8FlowerNext(j.z)),halfStep);
    M8FlowerInterval3 centre;
    centre.x = M8DepthIntervalRow(gridToWorld[0],grid);
    centre.y = M8DepthIntervalRow(gridToWorld[1],grid);
    centre.z = M8DepthIntervalRow(gridToWorld[2],grid);
    return centre;
}

bool M8FlowerObservedLoop(int3 owner, uint direction, float4x4 gridToWorld,
    out M8FlowerObservedLoopFrame result)
{
    int4 node = M8FlowerDirectionAt(direction);
    result.centre = M8FlowerObservedLoopCentre(owner,node.xyz,gridToWorld);
    float2 bounds = M8FlowerObservedRadiusAt(node.w);
    M8FlowerInterval radius = M8FlowerI(bounds.x,bounds.y);
    result.axis1 = M8FlowerObservedLoopAxis(M8FlowerLineE1At(node.w),radius,gridToWorld);
    result.axis2 = M8FlowerObservedLoopAxis(M8FlowerLineE2At(node.w),radius,gridToWorld);
    return true;
}

M8FlowerInterval3 M8FlowerRestrictObservedPlane(M8FlowerInterval3 normal,
    M8FlowerInterval3 positionInterval, M8FlowerObservedLoopFrame frame)
{
    M8FlowerInterval3 relative,abc;
    relative.x = M8FlowerISub(frame.centre.x,positionInterval.x);
    relative.y = M8FlowerISub(frame.centre.y,positionInterval.y);
    relative.z = M8FlowerISub(frame.centre.z,positionInterval.z);
    abc.x = M8FlowerObservedDot(normal,relative);
    abc.y = M8FlowerObservedDot(normal,frame.axis1);
    abc.z = M8FlowerObservedDot(normal,frame.axis2);
    return abc;
}

// Bounds already contain the complete represented support and its metric
// uncertainty. A projective transform of a convex cube with positive w has
// its screen extrema at corners. Each corner calculation is itself enclosed.
bool M8DepthProjectSupport(float3 minimum, float3 maximum, float4x4 view,
    float4x4 projection, int2 imageSize, float reprojectionError,
    out int2 pixelMin, out int2 pixelMax,
    out float supportUpperDepth)
{
    pixelMin = imageSize;
    pixelMax = -1;
    supportUpperDepth = 0.0;
    if (!all(M8FlowerIsFinite(minimum)) || !all(M8FlowerIsFinite(maximum)) || any(maximum < minimum) ||
        any(imageSize <= 0) || any(imageSize > (int)M8_OBSERVATION_IMAGE_SIDE) ||
        !M8FlowerIsFinite(reprojectionError) || reprojectionError < 0.0 ||
        !all(M8FlowerIsFinite(view[0])) || !all(M8FlowerIsFinite(view[1])) || !all(M8FlowerIsFinite(view[2])) ||
        !all(M8FlowerIsFinite(projection[0])) || !all(M8FlowerIsFinite(projection[1])) ||
        !all(M8FlowerIsFinite(projection[2])) || !all(M8FlowerIsFinite(projection[3])) ||
        any(view[3] != float4(0.0, 0.0, 0.0, 1.0))) return false;
    [loop]
    for (uint corner = 0u; corner < 8u; corner++)
    {
        float3 p = float3((corner & 1u) == 0u ? minimum.x : maximum.x,
            (corner & 2u) == 0u ? minimum.y : maximum.y,
            (corner & 4u) == 0u ? minimum.z : maximum.z);
        M8FlowerInterval3 world;
        world.x = M8FlowerI(p.x, p.x);
        world.y = M8FlowerI(p.y, p.y);
        world.z = M8FlowerI(p.z, p.z);
        M8FlowerInterval3 eye;
        M8FlowerInterval error = M8FlowerI(-reprojectionError, reprojectionError);
        eye.x = M8FlowerIAdd(M8DepthIntervalRow(view[0], world), error);
        eye.y = M8FlowerIAdd(M8DepthIntervalRow(view[1], world), error);
        eye.z = M8FlowerIAdd(M8DepthIntervalRow(view[2], world), error);
        if (!(eye.z.hi < 0.0)) return false;
        supportUpperDepth = max(supportUpperDepth, -eye.z.lo);
        M8FlowerInterval w = M8DepthIntervalRow(projection[3], eye);
        M8FlowerInterval projected[3];
        [loop]for(uint axis=0u;axis<3u;axis++)
            if(!M8FlowerIDivPositive(M8DepthIntervalRow(projection[axis],eye),w,
                projected[axis]))return false;
        M8FlowerInterval x=projected[0],y=projected[1],z=projected[2];
        if (z.lo < -1.0 || z.hi > 1.0) return false;
        x = M8FlowerIMul(M8FlowerIAdd(x, M8FlowerI(1.0, 1.0)),
            M8FlowerI((float)imageSize.x * 0.5, (float)imageSize.x * 0.5));
        y = M8FlowerIMul(M8FlowerIAdd(y, M8FlowerI(1.0, 1.0)),
            M8FlowerI((float)imageSize.y * 0.5, (float)imageSize.y * 0.5));
        if (!all(M8FlowerIsFinite(float4(x.lo, x.hi, y.lo, y.hi))) ||
            x.lo < 0.0 || y.lo < 0.0 || x.hi >= imageSize.x || y.hi >= imageSize.y) return false;
        pixelMin = min(pixelMin, int2(floor(x.lo), floor(y.lo)));
        pixelMax = max(pixelMax, int2(floor(x.hi), floor(y.hi)));
    }
    return M8FlowerIsFinite(supportUpperDepth);
}
#endif
