// GENERATED by MerkabaSphereFlowerCodegen. DO NOT EDIT.
// Packed REV-C subordinate data ABI; no resources are declared here.
#ifndef GENESIS_MERKABA_SPHERE_FLOWER_DATA_ABI_INCLUDED
#define GENESIS_MERKABA_SPHERE_FLOWER_DATA_ABI_INCLUDED
#define M8_FLOWER_DATA_ABI_VERSION 2u
#define M8_FLOWER_R1_SEED_FLAG 0x00000002u
#define M8_FLOWER_DETAIL_LEVEL_SHIFT 0u
#define M8_FLOWER_DETAIL_CHILD_PATH_SHIFT 3u
#define M8_FLOWER_DETAIL_PETAL_SHIFT 13u
#define M8_FLOWER_DETAIL_CHANNEL_SHIFT 19u
#define M8_FLOWER_DETAIL_KIND_SHIFT 23u
#define M8_FLOWER_DETAIL_ROOT_SHIFT 26u
#define M8_FLOWER_DETAIL_SECTOR_SHIFT 27u
#define M8_FLOWER_SYMBOL_LINE_SHIFT 3u
#define M8_FLOWER_SYMBOL_ROOT_SHIFT 7u
#define M8_FLOWER_SYMBOL_SECTOR_SHIFT 8u
#define M8_FLOWER_SYMBOL_ENDPOINT_SHIFT 13u
#define M8_FLOWER_SYMBOL_SHELL_SHIFT 14u
#define M8_FLOWER_SYMBOL_STATUS_SHIFT 17u
#define M8_FLOWER_SYMBOL_SCRATCH_SHIFT 20u

struct M8DualBlockMeta { uint StateAndGeneration; uint PayloadIndex; };
struct M8DualBlockChildren { uint Word00; uint Word01; uint Word02; uint Word03; uint Word04; uint Word05; uint Word06; uint Word07; uint Word08; uint Word09; uint Word10; uint Word11; uint Word12; uint Word13; uint Word14; uint Word15; uint Word16; uint Word17; uint Word18; uint Word19; uint Word20; uint Word21; uint Word22; uint Word23; uint Word24; uint Word25; uint Word26; uint Word27; uint Word28; uint Word29; uint Word30; uint Word31; };
struct M8DualChunkPayload { uint NonFullMaskLo; uint NonFullMaskHi; uint MixedMaskLo; uint MixedMaskHi; uint LeafRefBase; uint Generation; uint Reserved0; uint Reserved1; };
struct M8DualLeaf { uint Word00; uint Word01; uint Word02; uint Word03; uint Word04; uint Word05; uint Word06; uint Word07; uint Word08; uint Word09; uint Word10; uint Word11; uint Word12; uint Word13; uint Word14; uint Word15; };
struct M8FlowerOwnerEpoch { uint KernelLocal; uint Epoch; };
struct M8FlowerDetailRecord { uint Key; int Lower; int Upper; uint ParentEpoch; };
struct M8ThreadRun { uint FlowerKey; uint ProgramRef; uint ResidualBase; uint ParentEpoch; };
struct M8ThreadResidual { uint SegmentKey; uint ParentEpoch; uint2 LowerLinearRgba; uint2 UpperLinearRgba; uint Flags; uint Reserved; };
struct M8ThreadProgramRecord { uint EndpointColorRule; uint RgbResidualBasis; uint FibonacciRouteOrigin; uint Flags; uint2 OpticalLower; uint2 OpticalUpper; uint2 CaptureViewLower; uint2 CaptureViewUpper; };
struct M8FlowerSymbolKey { int3 Junction; uint Tag; };
struct M8ObservationRecord { uint TileAndKernel; uint SourcePixel; uint SymbolTag; uint PrecisionKey; };

uint M8FlowerPackDetailKey(uint level, uint childPath,
    uint petalClass, uint channel, uint kind, bool rootSign, uint sector)
{
    return level | (childPath << M8_FLOWER_DETAIL_CHILD_PATH_SHIFT) |
        (petalClass << M8_FLOWER_DETAIL_PETAL_SHIFT) |
        (channel << M8_FLOWER_DETAIL_CHANNEL_SHIFT) |
        (kind << M8_FLOWER_DETAIL_KIND_SHIFT) |
        (rootSign ? (1u << M8_FLOWER_DETAIL_ROOT_SHIFT) : 0u) |
        (sector << M8_FLOWER_DETAIL_SECTOR_SHIFT);
}

uint M8FlowerPackSymbolTag(uint level, uint lineClass, bool rootSign,
    uint sector, bool endpointOrientation, uint shellValidity,
    uint status, uint scratch)
{
    return level | (lineClass << M8_FLOWER_SYMBOL_LINE_SHIFT) |
        (rootSign ? (1u << M8_FLOWER_SYMBOL_ROOT_SHIFT) : 0u) |
        (sector << M8_FLOWER_SYMBOL_SECTOR_SHIFT) |
        (endpointOrientation ? (1u << M8_FLOWER_SYMBOL_ENDPOINT_SHIFT) : 0u) |
        (shellValidity << M8_FLOWER_SYMBOL_SHELL_SHIFT) |
        (status << M8_FLOWER_SYMBOL_STATUS_SHIFT) |
        (scratch << M8_FLOWER_SYMBOL_SCRATCH_SHIFT);
}
#endif
