// Generated by Tools~/native/gen_abi.py from Native~/include/finalscan_world_abi.h. Do not edit.
// 16-bit C fields are packed pairwise into uint words (low field first, little endian) so the
// std430 layout matches the C layout byte for byte. Use the fsGet_/fsSet_ accessors.
#ifndef FS_ABI_GLSL
#define FS_ABI_GLSL

#define FS_WORLD_ABI_VERSION 1
#define FS_SURFEL_POS_UNIT_M 0.00025
#define FS_PAGE_EXTENT_M 4.0
#define FS_CELL_EXTENT_M 0.125
#define FS_CELLS_PER_AXIS 32
#define FS_CELLS_PER_PAGE 32768
#define FS_INDEX_NONE 4294967295u
#define FS_CLUSTER_LEAF_MAX_SURFELS 64
#define FS_CLUSTER_MAX_NODES_PER_PAGE 4096
#define FS_CLUSTER_ERROR_INF 1e+30
#define FS_DRAW_FLAG_AGGREGATE 8
#define FS_DRAW_FLAG_TRANSIENT 16

#define FS_CTR_PCA_FRAMES_L 0
#define FS_CTR_PCA_FRAMES_R 1
#define FS_CTR_STEREO_PAIRS 2
#define FS_CTR_PAIRS_REJECTED_SKEW 3
#define FS_CTR_MEASUREMENTS 4
#define FS_CTR_MEASUREMENTS_DROPPED 5
#define FS_CTR_PAGE_LOOKUPS 6
#define FS_CTR_PAGE_MISSES 7
#define FS_CTR_CELL_LOOKUPS 8
#define FS_CTR_SURFEL_CREATE 9
#define FS_CTR_SURFEL_UPDATE 10
#define FS_CTR_SURFEL_DELETE 11
#define FS_CTR_SURFEL_SPLIT 12
#define FS_CTR_SURFEL_MERGE 13
#define FS_CTR_PUBLISH 14
#define FS_CTR_RESIDENT_DRAWN 15
#define FS_CTR_VISIBLE_SURFELS 16
#define FS_CTR_SCAN_TICK 17
#define FS_CTR_SCAN_TICK_SKIPPED 18
#define FS_CTR_ORIENTATION_RESIDENCY_REQUESTS 19
#define FS_CTR_PAGE_HASH_OVERFLOW 20
#define FS_CTR_INDEX_OVERFLOW 21
#define FS_CTR_DEFERRED_PUBLISH 22
#define FS_CTR_DEFERRED_SCAN 23
#define FS_CTR_DEFERRED_RESIDENCY 24
#define FS_CTR_DEFERRED_APPEARANCE 25
#define FS_CTR_DEFERRED_COLD 26
#define FS_CTR_TIMESTAMP_NONMONO 27
#define FS_CTR_DUPLICATE_OBSERVATIONS 28
#define FS_CTR_COUNT 29

struct FsSurfel {
    uint px_py;
    uint pz_normalOct;
    uint normalOctHi_tangentAngle;
    uint radiusMajor_radiusMinor;
    uint sigmaN_sigmaTMajor;
    uint sigmaTMinor_evidenceFlags;
    uint surfaceId;
    uint appearanceHandle;
};  // 32 B
#define FS_ABI_FSSURFEL_BYTES 32
int fsGet_FsSurfel_px(FsSurfel s) { return bitfieldExtract(int(s.px_py), 0, 16); }
void fsSet_FsSurfel_px(inout FsSurfel s, int v) { s.px_py = bitfieldInsert(s.px_py, uint(v), 0, 16); }
int fsGet_FsSurfel_py(FsSurfel s) { return bitfieldExtract(int(s.px_py), 16, 16); }
void fsSet_FsSurfel_py(inout FsSurfel s, int v) { s.px_py = bitfieldInsert(s.px_py, uint(v), 16, 16); }
int fsGet_FsSurfel_pz(FsSurfel s) { return bitfieldExtract(int(s.pz_normalOct), 0, 16); }
void fsSet_FsSurfel_pz(inout FsSurfel s, int v) { s.pz_normalOct = bitfieldInsert(s.pz_normalOct, uint(v), 0, 16); }
uint fsGet_FsSurfel_normalOct(FsSurfel s) { return bitfieldExtract(s.pz_normalOct, 16, 16); }
void fsSet_FsSurfel_normalOct(inout FsSurfel s, uint v) { s.pz_normalOct = bitfieldInsert(s.pz_normalOct, uint(v), 16, 16); }
uint fsGet_FsSurfel_normalOctHi(FsSurfel s) { return bitfieldExtract(s.normalOctHi_tangentAngle, 0, 16); }
void fsSet_FsSurfel_normalOctHi(inout FsSurfel s, uint v) { s.normalOctHi_tangentAngle = bitfieldInsert(s.normalOctHi_tangentAngle, uint(v), 0, 16); }
uint fsGet_FsSurfel_tangentAngle(FsSurfel s) { return bitfieldExtract(s.normalOctHi_tangentAngle, 16, 16); }
void fsSet_FsSurfel_tangentAngle(inout FsSurfel s, uint v) { s.normalOctHi_tangentAngle = bitfieldInsert(s.normalOctHi_tangentAngle, uint(v), 16, 16); }
uint fsGet_FsSurfel_radiusMajor(FsSurfel s) { return bitfieldExtract(s.radiusMajor_radiusMinor, 0, 16); }
void fsSet_FsSurfel_radiusMajor(inout FsSurfel s, uint v) { s.radiusMajor_radiusMinor = bitfieldInsert(s.radiusMajor_radiusMinor, uint(v), 0, 16); }
uint fsGet_FsSurfel_radiusMinor(FsSurfel s) { return bitfieldExtract(s.radiusMajor_radiusMinor, 16, 16); }
void fsSet_FsSurfel_radiusMinor(inout FsSurfel s, uint v) { s.radiusMajor_radiusMinor = bitfieldInsert(s.radiusMajor_radiusMinor, uint(v), 16, 16); }
uint fsGet_FsSurfel_sigmaN(FsSurfel s) { return bitfieldExtract(s.sigmaN_sigmaTMajor, 0, 16); }
void fsSet_FsSurfel_sigmaN(inout FsSurfel s, uint v) { s.sigmaN_sigmaTMajor = bitfieldInsert(s.sigmaN_sigmaTMajor, uint(v), 0, 16); }
uint fsGet_FsSurfel_sigmaTMajor(FsSurfel s) { return bitfieldExtract(s.sigmaN_sigmaTMajor, 16, 16); }
void fsSet_FsSurfel_sigmaTMajor(inout FsSurfel s, uint v) { s.sigmaN_sigmaTMajor = bitfieldInsert(s.sigmaN_sigmaTMajor, uint(v), 16, 16); }
uint fsGet_FsSurfel_sigmaTMinor(FsSurfel s) { return bitfieldExtract(s.sigmaTMinor_evidenceFlags, 0, 16); }
void fsSet_FsSurfel_sigmaTMinor(inout FsSurfel s, uint v) { s.sigmaTMinor_evidenceFlags = bitfieldInsert(s.sigmaTMinor_evidenceFlags, uint(v), 0, 16); }
uint fsGet_FsSurfel_evidenceFlags(FsSurfel s) { return bitfieldExtract(s.sigmaTMinor_evidenceFlags, 16, 16); }
void fsSet_FsSurfel_evidenceFlags(inout FsSurfel s, uint v) { s.sigmaTMinor_evidenceFlags = bitfieldInsert(s.sigmaTMinor_evidenceFlags, uint(v), 16, 16); }

struct FsPageKey {
    int anchorId;
    int x;
    int y;
    int z;
};  // 16 B
#define FS_ABI_FSPAGEKEY_BYTES 16

struct FsPageHeader {
    FsPageKey key;
    uint slot;
    uint generation;
    uint frontOffset;
    uint frontCount;
    uint backOffset;
    uint backCount;
    uint capacity;
    uint dirty;
    uint cellIndexOffset;
    uint freeSpaceOffset;
    uint lastTouchedFrame;
    uint nodeBase;
    uint nodeCount;
};  // 68 B
#define FS_ABI_FSPAGEHEADER_BYTES 68

struct FsSurfelLink {
    uint next;
};  // 4 B
#define FS_ABI_FSSURFELLINK_BYTES 4

struct FsPageHashEntry {
    FsPageKey key;
    uint slot;
    uint generation;
    uint probeDistance;
    uint reserved;
};  // 32 B
#define FS_ABI_FSPAGEHASHENTRY_BYTES 32

struct FsSurfaceMeasurement {
    float px;
    float py;
    float pz;
    float nx;
    float ny;
    float nz;
    float sigmaN;
    float sigmaT;
    float footprint;
    uint sourceFlags;
    uint observationId;
    uint reserved;
};  // 48 B
#define FS_ABI_FSSURFACEMEASUREMENT_BYTES 48

struct FsDrawRecord {
    float cx;
    float cy;
    float cz;
    uint normalOct32;
    uint tangentAndRadii;
    uint colorOrHandle;
    uint surfaceId;
    uint flags;
};  // 32 B
#define FS_ABI_FSDRAWRECORD_BYTES 32

struct FsIndirectDrawArgs {
    uint vertexCountPerInstance;
    uint instanceCount;
    uint startVertex;
    uint startInstance;
};  // 16 B
#define FS_ABI_FSINDIRECTDRAWARGS_BYTES 16

struct FsSurfelEvidence {
    uint staticEvidence_motionEvidence;
    uint varianceQ_lastSeenFrame;
};  // 8 B
#define FS_ABI_FSSURFELEVIDENCE_BYTES 8
uint fsGet_FsSurfelEvidence_staticEvidence(FsSurfelEvidence s) { return bitfieldExtract(s.staticEvidence_motionEvidence, 0, 16); }
void fsSet_FsSurfelEvidence_staticEvidence(inout FsSurfelEvidence s, uint v) { s.staticEvidence_motionEvidence = bitfieldInsert(s.staticEvidence_motionEvidence, uint(v), 0, 16); }
uint fsGet_FsSurfelEvidence_motionEvidence(FsSurfelEvidence s) { return bitfieldExtract(s.staticEvidence_motionEvidence, 16, 16); }
void fsSet_FsSurfelEvidence_motionEvidence(inout FsSurfelEvidence s, uint v) { s.staticEvidence_motionEvidence = bitfieldInsert(s.staticEvidence_motionEvidence, uint(v), 16, 16); }
uint fsGet_FsSurfelEvidence_varianceQ(FsSurfelEvidence s) { return bitfieldExtract(s.varianceQ_lastSeenFrame, 0, 16); }
void fsSet_FsSurfelEvidence_varianceQ(inout FsSurfelEvidence s, uint v) { s.varianceQ_lastSeenFrame = bitfieldInsert(s.varianceQ_lastSeenFrame, uint(v), 0, 16); }
uint fsGet_FsSurfelEvidence_lastSeenFrame(FsSurfelEvidence s) { return bitfieldExtract(s.varianceQ_lastSeenFrame, 16, 16); }
void fsSet_FsSurfelEvidence_lastSeenFrame(inout FsSurfelEvidence s, uint v) { s.varianceQ_lastSeenFrame = bitfieldInsert(s.varianceQ_lastSeenFrame, uint(v), 16, 16); }

struct FsClusterNode {
    float bmin[3];
    float bmax[3];
    float coneAxis[3];
    float coneCos;
    float repCenter[3];
    float repRadius;
    uint repNormalOct32;
    uint repColorOrHandle;
    uint coverage_surfelCount;
    uint firstChildOrSurfel;
    uint childCount_leafSurfelCount;
    uint footprint;
};  // 80 B
#define FS_ABI_FSCLUSTERNODE_BYTES 80
uint fsGet_FsClusterNode_coverage(FsClusterNode s) { return bitfieldExtract(s.coverage_surfelCount, 0, 16); }
void fsSet_FsClusterNode_coverage(inout FsClusterNode s, uint v) { s.coverage_surfelCount = bitfieldInsert(s.coverage_surfelCount, uint(v), 0, 16); }
uint fsGet_FsClusterNode_surfelCount(FsClusterNode s) { return bitfieldExtract(s.coverage_surfelCount, 16, 16); }
void fsSet_FsClusterNode_surfelCount(inout FsClusterNode s, uint v) { s.coverage_surfelCount = bitfieldInsert(s.coverage_surfelCount, uint(v), 16, 16); }
uint fsGet_FsClusterNode_childCount(FsClusterNode s) { return bitfieldExtract(s.childCount_leafSurfelCount, 0, 16); }
void fsSet_FsClusterNode_childCount(inout FsClusterNode s, uint v) { s.childCount_leafSurfelCount = bitfieldInsert(s.childCount_leafSurfelCount, uint(v), 0, 16); }
uint fsGet_FsClusterNode_leafSurfelCount(FsClusterNode s) { return bitfieldExtract(s.childCount_leafSurfelCount, 16, 16); }
void fsSet_FsClusterNode_leafSurfelCount(inout FsClusterNode s, uint v) { s.childCount_leafSurfelCount = bitfieldInsert(s.childCount_leafSurfelCount, uint(v), 16, 16); }

struct FsClusterError {
    float ownError;
    float parentError;
};  // 8 B
#define FS_ABI_FSCLUSTERERROR_BYTES 8

#endif // FS_ABI_GLSL
