// Generated by Tools~/native/gen_abi.py from Native~/include/finalscan_world_abi.h. Do not edit.
// Layouts are byte-identical to the C structs (Pack = 1, natural order); WorldAbi.AssertLayout() checks sizes.
using System;
using System.Runtime.InteropServices;

namespace FinalScan.World
{
    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct FsSurfel  // 32 B
    {
        public short px;
        public short py;
        public short pz;
        public ushort normalOct;
        public ushort normalOctHi;
        public ushort tangentAngle;
        public ushort radiusMajor;
        public ushort radiusMinor;
        public ushort sigmaN;
        public ushort sigmaTMajor;
        public ushort sigmaTMinor;
        public ushort evidenceFlags;
        public uint surfaceId;
        public uint appearanceHandle;
        public const int SizeBytes = 32;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct FsPageKey  // 16 B
    {
        public int anchorId;
        public int x;
        public int y;
        public int z;
        public const int SizeBytes = 16;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct FsPageHeader  // 68 B
    {
        public FsPageKey key;
        public uint slot;
        public uint generation;
        public uint frontOffset;
        public uint frontCount;
        public uint backOffset;
        public uint backCount;
        public uint capacity;
        public uint dirty;
        public uint cellIndexOffset;
        public uint freeSpaceOffset;
        public uint lastTouchedFrame;
        public uint nodeBase;
        public uint nodeCount;
        public const int SizeBytes = 68;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct FsSurfelLink  // 4 B
    {
        public uint next;
        public const int SizeBytes = 4;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct FsPageHashEntry  // 32 B
    {
        public FsPageKey key;
        public uint slot;
        public uint generation;
        public uint probeDistance;
        public uint reserved;
        public const int SizeBytes = 32;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct FsSurfaceMeasurement  // 48 B
    {
        public float px;
        public float py;
        public float pz;
        public float nx;
        public float ny;
        public float nz;
        public float sigmaN;
        public float sigmaT;
        public float footprint;
        public uint sourceFlags;
        public uint observationId;
        public uint reserved;
        public const int SizeBytes = 48;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct FsDrawRecord  // 32 B
    {
        public float cx;
        public float cy;
        public float cz;
        public uint normalOct32;
        public uint tangentAndRadii;
        public uint colorOrHandle;
        public uint surfaceId;
        public uint flags;
        public const int SizeBytes = 32;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct FsIndirectDrawArgs  // 16 B
    {
        public uint vertexCountPerInstance;
        public uint instanceCount;
        public uint startVertex;
        public uint startInstance;
        public const int SizeBytes = 16;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct FsSurfelEvidence  // 8 B
    {
        public ushort staticEvidence;
        public ushort motionEvidence;
        public ushort varianceQ;
        public ushort lastSeenFrame;
        public const int SizeBytes = 8;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public unsafe struct FsClusterNode  // 80 B
    {
        public fixed float bmin[3];
        public fixed float bmax[3];
        public fixed float coneAxis[3];
        public float coneCos;
        public fixed float repCenter[3];
        public float repRadius;
        public uint repNormalOct32;
        public uint repColorOrHandle;
        public ushort coverage;
        public ushort surfelCount;
        public uint firstChildOrSurfel;
        public ushort childCount;
        public ushort leafSurfelCount;
        public uint footprint;
        public const int SizeBytes = 80;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct FsClusterError  // 8 B
    {
        public float ownError;
        public float parentError;
        public const int SizeBytes = 8;
    }

    public enum FsCounter
    {
        PcaFramesL = 0,
        PcaFramesR = 1,
        StereoPairs = 2,
        PairsRejectedSkew = 3,
        Measurements = 4,
        MeasurementsDropped = 5,
        PageLookups = 6,
        PageMisses = 7,
        CellLookups = 8,
        SurfelCreate = 9,
        SurfelUpdate = 10,
        SurfelDelete = 11,
        SurfelSplit = 12,
        SurfelMerge = 13,
        Publish = 14,
        ResidentDrawn = 15,
        VisibleSurfels = 16,
        ScanTick = 17,
        ScanTickSkipped = 18,
        OrientationResidencyRequests = 19,
        PageHashOverflow = 20,
        IndexOverflow = 21,
        DeferredPublish = 22,
        DeferredScan = 23,
        DeferredResidency = 24,
        DeferredAppearance = 25,
        DeferredCold = 26,
        TimestampNonmono = 27,
        DuplicateObservations = 28,
        Count = 29,
    }

    public static class WorldAbi
    {
        public const int WorldAbiVersion = 1;
        public const float SurfelPosUnitM = 0.00025f;
        public const float PageExtentM = 4.0f;
        public const float CellExtentM = 0.125f;
        public const int CellsPerAxis = 32;
        public const int CellsPerPage = 32768;
        public const uint IndexNone = 4294967295u;
        public const int ClusterLeafMaxSurfels = 64;
        public const int ClusterMaxNodesPerPage = 4096;
        public const float ClusterErrorInf = 1e+30f;
        public const int DrawFlagAggregate = 8;
        public const int DrawFlagTransient = 16;

        /// <summary>Throws when the managed layouts drift from the native header (call once at startup).</summary>
        public static void AssertLayout()
        {
            Check(Marshal.SizeOf<FsSurfel>(), FsSurfel.SizeBytes, "FsSurfel");
            Check(Marshal.SizeOf<FsPageKey>(), FsPageKey.SizeBytes, "FsPageKey");
            Check(Marshal.SizeOf<FsPageHeader>(), FsPageHeader.SizeBytes, "FsPageHeader");
            Check(Marshal.SizeOf<FsSurfelLink>(), FsSurfelLink.SizeBytes, "FsSurfelLink");
            Check(Marshal.SizeOf<FsPageHashEntry>(), FsPageHashEntry.SizeBytes, "FsPageHashEntry");
            Check(Marshal.SizeOf<FsSurfaceMeasurement>(), FsSurfaceMeasurement.SizeBytes, "FsSurfaceMeasurement");
            Check(Marshal.SizeOf<FsDrawRecord>(), FsDrawRecord.SizeBytes, "FsDrawRecord");
            Check(Marshal.SizeOf<FsIndirectDrawArgs>(), FsIndirectDrawArgs.SizeBytes, "FsIndirectDrawArgs");
            Check(Marshal.SizeOf<FsSurfelEvidence>(), FsSurfelEvidence.SizeBytes, "FsSurfelEvidence");
            Check(Marshal.SizeOf<FsClusterNode>(), FsClusterNode.SizeBytes, "FsClusterNode");
            Check(Marshal.SizeOf<FsClusterError>(), FsClusterError.SizeBytes, "FsClusterError");
        }

        static void Check(int actual, int expected, string name)
        {
            if (actual != expected) throw new InvalidOperationException($"FinalScan ABI mismatch: {name} is {actual} B, native expects {expected} B");
        }
    }
}
