// Generated by Tools~/native/gen_abi.py from Native~/include/finalscan_world_abi.h. Do not edit.
// Layouts are byte-identical to the C structs (Pack = 1, natural order); WorldAbi.AssertLayout() checks sizes.
using System;
using System.Runtime.InteropServices;

namespace FinalScan.World
{
    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct FsSurfel  // 32 B
    {
        public short px;
        public short py;
        public short pz;
        public ushort normalOct;
        public ushort normalOctHi;
        public ushort tangentAngle;
        public ushort radiusMajor;
        public ushort radiusMinor;
        public ushort sigmaN;
        public ushort sigmaTMajor;
        public ushort sigmaTMinor;
        public ushort evidenceFlags;
        public uint surfaceId;
        public uint appearanceHandle;
        public const int SizeBytes = 32;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct FsPageKey  // 16 B
    {
        public int anchorId;
        public int x;
        public int y;
        public int z;
        public const int SizeBytes = 16;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct FsPageDesc  // 64 B
    {
        public FsPageKey key;
        public uint generation;
        public uint slabCount;
        public uint surfelCount;
        public uint shortfall;
        public uint cellDirBase;
        public uint freeSpaceBase;
        public uint renderRoot;
        public uint renderCount;
        public uint pendingRoot;
        public uint pendingCount;
        public uint flags;
        public uint lastTouchedTick;
        public const int SizeBytes = 64;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public unsafe struct FsIndexLeaf  // 64 B
    {
        public uint count;
        public uint next;
        public fixed uint handles[14];
        public const int SizeBytes = 64;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public unsafe struct FsIndexNode  // 32 B
    {
        public fixed uint child[8];
        public const int SizeBytes = 32;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct FsAssociation  // 16 B
    {
        public uint key;
        public uint meas;
        public float score;
        public uint pageSlot;
        public const int SizeBytes = 16;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct FsPendingPublish  // 16 B
    {
        public uint pageSlot;
        public uint root;
        public uint count;
        public uint generation;
        public const int SizeBytes = 16;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct FsPageHashEntry  // 32 B
    {
        public FsPageKey key;
        public uint slot;
        public uint generation;
        public uint probeDistance;
        public uint reserved;
        public const int SizeBytes = 32;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct FsSurfaceMeasurement  // 48 B
    {
        public float px;
        public float py;
        public float pz;
        public float nx;
        public float ny;
        public float nz;
        public float sigmaN;
        public float sigmaT;
        public float footprint;
        public uint sourceFlags;
        public uint observationId;
        public uint reserved;
        public const int SizeBytes = 48;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct FsDrawRecord  // 32 B
    {
        public float cx;
        public float cy;
        public float cz;
        public uint normalOct32;
        public uint tangentAndRadii;
        public uint colorOrHandle;
        public uint surfaceId;
        public uint flags;
        public const int SizeBytes = 32;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct FsIndirectDrawArgs  // 16 B
    {
        public uint vertexCountPerInstance;
        public uint instanceCount;
        public uint startVertex;
        public uint startInstance;
        public const int SizeBytes = 16;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct FsSurfelEvidence  // 32 B
    {
        public ushort positiveSupport;
        public ushort contradictionDebt;
        public ushort varianceQ;
        public ushort lastSeenFrame;
        public uint lastObservationId;
        public uint lastContradictionObs;
        public uint contradictionHits;
        public uint lastDebtObs;
        public ushort viewDiversity;
        public ushort contradictionViews;
        public ushort lifecycle;
        public ushort suspectSince;
        public const int SizeBytes = 32;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public unsafe struct FsClusterNode  // 80 B
    {
        public fixed float bmin[3];
        public fixed float bmax[3];
        public fixed float coneAxis[3];
        public float coneCos;
        public fixed float repCenter[3];
        public float repRadius;
        public uint repNormalOct32;
        public uint repColorOrHandle;
        public ushort coverage;
        public ushort surfelCount;
        public uint firstChildOrSurfel;
        public ushort childCount;
        public ushort leafSurfelCount;
        public uint footprint;
        public const int SizeBytes = 80;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct FsClusterError  // 8 B
    {
        public float ownError;
        public float parentError;
        public const int SizeBytes = 8;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public unsafe struct FsRenderNode  // 120 B
    {
        public FsClusterNode node;
        public FsClusterError err;
        public fixed uint child[8];
        public const int SizeBytes = 120;
    }

    public enum FsCounter
    {
        PcaFramesL = 0,
        PcaFramesR = 1,
        StereoPairs = 2,
        PairsRejectedSkew = 3,
        Measurements = 4,
        MeasurementsDropped = 5,
        PageLookups = 6,
        PageMisses = 7,
        CellLookups = 8,
        SurfelCreate = 9,
        SurfelUpdate = 10,
        SurfelDelete = 11,
        SurfelSplit = 12,
        SurfelMerge = 13,
        Publish = 14,
        ResidentDrawn = 15,
        VisibleSurfels = 16,
        ScanTick = 17,
        ScanTickSkipped = 18,
        OrientationResidencyRequests = 19,
        PageHashOverflow = 20,
        IndexOverflow = 21,
        DeferredPublish = 22,
        DeferredScan = 23,
        DeferredResidency = 24,
        DeferredAppearance = 25,
        DeferredCold = 26,
        TimestampNonmono = 27,
        DuplicateObservations = 28,
        Count = 29,
    }

    public static class WorldAbi
    {
        public const int WorldAbiVersion = 2;
        public const float SurfelPosUnitM = 0.00025f;
        public const float PageExtentM = 4.0f;
        public const float CellExtentM = 0.125f;
        public const int CellsPerAxis = 32;
        public const int CellsPerPage = 32768;
        public const uint IndexNone = 4294967295u;
        public const int SlabSurfels = 256;
        public const int PageMaxSlabs = 4096;
        public const uint PageFlagDirty = 1u;
        public const uint PageFlagErase = 2u;
        public const uint IndexEntryLeaf = 2147483648u;
        public const uint IndexEntryNode = 1073741824u;
        public const uint IndexEntryId = 1073741823u;
        public const int IndexLeafCap = 14;
        public const int IndexMaxDepth = 3;
        public const int IndexChainMax = 4;
        public const uint AssocKeyUnmatched = 2147483648u;
        public const uint AssocKeyNone = 4294967295u;
        public const uint MeasColorValid = 2147483648u;
        public const uint AppearanceMeasured = 2147483648u;
        public const int AppearanceObsShift = 24;
        public const uint AppearanceObsMask = 251658240u;
        public const int AppearanceConfirmObs = 3;
        public const int RenderBlockSurfels = 64;
        public const int RenderChildren = 8;
        public const float ClusterErrorInf = 1e+30f;
        public const int DrawFlagAggregate = 8;
        public const int DrawFlagTransient = 16;
        public const int DrawFlagNoAppearance = 32;

        /// <summary>Throws when the managed layouts drift from the native header (call once at startup).</summary>
        public static void AssertLayout()
        {
            Check(Marshal.SizeOf<FsSurfel>(), FsSurfel.SizeBytes, "FsSurfel");
            Check(Marshal.SizeOf<FsPageKey>(), FsPageKey.SizeBytes, "FsPageKey");
            Check(Marshal.SizeOf<FsPageDesc>(), FsPageDesc.SizeBytes, "FsPageDesc");
            Check(Marshal.SizeOf<FsIndexLeaf>(), FsIndexLeaf.SizeBytes, "FsIndexLeaf");
            Check(Marshal.SizeOf<FsIndexNode>(), FsIndexNode.SizeBytes, "FsIndexNode");
            Check(Marshal.SizeOf<FsAssociation>(), FsAssociation.SizeBytes, "FsAssociation");
            Check(Marshal.SizeOf<FsPendingPublish>(), FsPendingPublish.SizeBytes, "FsPendingPublish");
            Check(Marshal.SizeOf<FsPageHashEntry>(), FsPageHashEntry.SizeBytes, "FsPageHashEntry");
            Check(Marshal.SizeOf<FsSurfaceMeasurement>(), FsSurfaceMeasurement.SizeBytes, "FsSurfaceMeasurement");
            Check(Marshal.SizeOf<FsDrawRecord>(), FsDrawRecord.SizeBytes, "FsDrawRecord");
            Check(Marshal.SizeOf<FsIndirectDrawArgs>(), FsIndirectDrawArgs.SizeBytes, "FsIndirectDrawArgs");
            Check(Marshal.SizeOf<FsSurfelEvidence>(), FsSurfelEvidence.SizeBytes, "FsSurfelEvidence");
            Check(Marshal.SizeOf<FsClusterNode>(), FsClusterNode.SizeBytes, "FsClusterNode");
            Check(Marshal.SizeOf<FsClusterError>(), FsClusterError.SizeBytes, "FsClusterError");
            Check(Marshal.SizeOf<FsRenderNode>(), FsRenderNode.SizeBytes, "FsRenderNode");
        }

        static void Check(int actual, int expected, string name)
        {
            if (actual != expected) throw new InvalidOperationException($"FinalScan ABI mismatch: {name} is {actual} B, native expects {expected} B");
        }
    }
}
