#!/usr/bin/env bash

# Frozen local development environment for Quest Infinite Merkaba Scan.
# Callers may override a value explicitly, but every default is a path verified
# in .codex/MERKABA_ENV.md.

QIS_TARGET_ROOT="${QIS_TARGET_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd -P)}"
QIS_DEV_ROOT="${QIS_DEV_ROOT:-/mnt/kingston-unity}"
QIS_UNITY_VERSION="${QIS_UNITY_VERSION:-6000.5.9f1}"
QIS_UNITY_EXECUTABLE="${QIS_UNITY_EXECUTABLE:-${QIS_DEV_ROOT}/Unity/Hub/Editor/${QIS_UNITY_VERSION}/Editor/Unity}"
QIS_UNITY_PROJECT_ROOT="${QIS_UNITY_PROJECT_ROOT:-${QIS_DEV_ROOT}/Unity/Projects}"
QIS_UNITY_HOST_PROJECT="${QIS_UNITY_HOST_PROJECT:-${QIS_UNITY_PROJECT_ROOT}/QuestMerkabaScanHost}"
QIS_BUILD_ROOT="${QIS_BUILD_ROOT:-${QIS_DEV_ROOT}/Builds}"
QIS_MERKABA_BUILD_DIR="${QIS_MERKABA_BUILD_DIR:-${QIS_BUILD_ROOT}/QuestMerkabaScan}"
QIS_MERKABA_APK_PATH="${QIS_MERKABA_APK_PATH:-${QIS_MERKABA_BUILD_DIR}/QuestMerkabaScan-release.apk}"
QIS_GRADLE_USER_HOME="${QIS_GRADLE_USER_HOME:-${QIS_MERKABA_BUILD_DIR}/gradle-user-home}"
QIS_ANDROID_SDK_ROOT="${QIS_ANDROID_SDK_ROOT:-${QIS_UNITY_EXECUTABLE%/Editor/Unity}/Editor/Data/PlaybackEngines/AndroidPlayer/SDK}"
QIS_ADB_EXECUTABLE="${QIS_ADB_EXECUTABLE:-${QIS_ANDROID_SDK_ROOT}/platform-tools/adb}"

export QIS_TARGET_ROOT QIS_DEV_ROOT QIS_UNITY_VERSION QIS_UNITY_EXECUTABLE
export QIS_UNITY_PROJECT_ROOT QIS_UNITY_HOST_PROJECT QIS_BUILD_ROOT
export QIS_MERKABA_BUILD_DIR QIS_MERKABA_APK_PATH QIS_GRADLE_USER_HOME QIS_ANDROID_SDK_ROOT
export QIS_ADB_EXECUTABLE
