#!/usr/bin/env bash
# Builds libFinalScanNative.so (Android arm64, Unity NDK clang) into the host project's
# Assets/Plugins/Android, writes its .meta (Android/ARM64 plugin, 16 KiB aligned), compiles every
# compute kernel under Native~/shaders/**.comp to SPIR-V (glslangValidator/glslc), runs the kernel
# envelope gate (Tools~/native/spv_gate.py, contract §15.6: fail-closed), embeds the kernels as
# <stem>_spirv.inc (symbol k<Stem>Spirv), compiles Native~/src/*.cpp + Native~/src/host/**/*.cpp,
# strips with llvm-strip and prints sha256 sums.
#
# Kernel .inc files are generated into $FS_NATIVE_GEN_DIR/spirv (on the include path) and mirrored as
# committed fallbacks next to their owner: Native~/shaders/<sub>/x.comp -> Native~/src/host/<sub>/spirv/
# when that directory exists, else Native~/src/spirv/. A host without a shader compiler builds from the
# mirrored fallbacks (still gated).
set -euo pipefail
fs_script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
source "$fs_script_dir/../dev_environment.sh"
fs_native="$FS_PACKAGE_ROOT/Native~"
fs_toolchain="$FS_ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64"
fs_clang=""
for api in 32 29; do
    if [[ -x "$fs_toolchain/bin/aarch64-linux-android${api}-clang++" ]]; then fs_clang="$fs_toolchain/bin/aarch64-linux-android${api}-clang++"; fs_api=$api; break; fi
done
[[ -n "$fs_clang" ]] || { echo "NDK clang not found under $fs_toolchain/bin" >&2; exit 1; }
fs_strip="$fs_toolchain/bin/llvm-strip"
test -x "$fs_strip"
fs_project="${1:-$FS_HOST_PROJECT}"
fs_output_dir="$fs_project/Assets/Plugins/Android"
fs_output="$fs_output_dir/libFinalScanNative.so"
fs_gen="${FS_NATIVE_GEN_DIR:-$(mktemp -d -t finalscan-native.XXXXXX)}"
[[ -n "${FS_NATIVE_GEN_DIR:-}" ]] || trap 'rm -rf -- "$fs_gen"' EXIT
fs_gen_spv="$fs_gen/spirv"
mkdir -p "$fs_gen_spv" "$fs_output_dir"
fs_python="${FS_PYTHON:-python3}"

# ---- shader compiler -------------------------------------------------------------------
fs_compiler=""
if command -v glslangValidator >/dev/null 2>&1; then fs_compiler="glslangValidator";
elif command -v glslc >/dev/null 2>&1; then fs_compiler="glslc";
elif [[ -x "$FS_ANDROID_NDK_ROOT/shader-tools/linux-x86_64/glslc" ]]; then fs_compiler="$FS_ANDROID_NDK_ROOT/shader-tools/linux-x86_64/glslc";
else
    for cand in "$FS_UNITY_EDITOR_DIR/Data/Tools/glslangValidator" "$FS_UNITY_EDITOR_DIR/Data/Tools/glslc"; do
        [[ -x "$cand" ]] && { fs_compiler="$cand"; break; }
    done
fi
fs_spirv_val=""
if command -v spirv-val >/dev/null 2>&1; then fs_spirv_val="spirv-val";
elif [[ -x "$FS_ANDROID_NDK_ROOT/shader-tools/linux-x86_64/spirv-val" ]]; then fs_spirv_val="$FS_ANDROID_NDK_ROOT/shader-tools/linux-x86_64/spirv-val"; fi
fs_spirv_source="${fs_compiler:-fallback}"

# stem -> CamelCase symbol: overlap_job -> kOverlapJobSpirv
fs_symbol() { local s="$1"; local out=""; IFS='_-' read -ra parts <<< "$s"; for p in "${parts[@]}"; do out+="$(tr '[:lower:]' '[:upper:]' <<< "${p:0:1}")${p:1}"; done; printf 'k%sSpirv' "$out"; }
# Mirror location of a kernel's fallback .inc
fs_mirror_dir() {
    local comp="$1"; local rel="${comp#"$fs_native/shaders/"}"; local sub="$(dirname -- "$rel")"
    if [[ "$sub" != "." && -d "$fs_native/src/host/$sub/spirv" ]]; then printf '%s' "$fs_native/src/host/$sub/spirv";
    else printf '%s' "$fs_native/src/spirv"; fi
}
fs_emit_inc() {   # spv, inc, comp, symbol
    local spv="$1" inc="$2" comp="$3" sym="$4"
    {
        echo "// Generated by Tools~/native/build_native.sh from ${comp#"$FS_PACKAGE_ROOT/"} ($(basename -- "$fs_spirv_source")). Do not edit."
        echo "#pragma once"
        echo "#include <stdint.h>"
        echo "static const uint32_t ${sym}[] = {"
        od -An -v -tu4 -w16 "$spv" | sed -E 's/^ +//; s/ +/, /g; s/$/,/'
        echo "};"
    } > "$inc"
}
fs_inc_to_spv() {   # inc -> spv (for gating committed fallbacks)
    "$fs_python" - "$1" "$2" <<'PY'
import re, struct, sys
text = open(sys.argv[1]).read()
body = text[text.index("{") + 1:text.rindex("}")]
words = [int(x) for x in re.findall(r"\d+", body)]
open(sys.argv[2], "wb").write(struct.pack("<%dI" % len(words), *words))
PY
}

# ---- SPIR-V: every Native~/shaders/**.comp -----------------------------------------------
mapfile -t fs_kernels < <(find "$fs_native/shaders" -type f -name '*.comp' | sort)
[[ ${#fs_kernels[@]} -gt 0 ]] || { echo "no kernels under $fs_native/shaders" >&2; exit 1; }
fs_gate_files=()
fs_kernel_names=()
fs_include_dirs=("$fs_native/shaders" "$fs_native/shaders/world" "$fs_native/shaders/render")
fs_glsl_inc=(); for d in "${fs_include_dirs[@]}"; do [[ -d "$d" ]] && fs_glsl_inc+=("-I$d"); done
for comp in "${fs_kernels[@]}"; do
    stem="$(basename -- "$comp" .comp)"
    for prev in "${fs_kernel_names[@]:-}"; do [[ "$prev" == "$stem" ]] && { echo "duplicate kernel stem '$stem' (kernel names must be unique across Native~/shaders)" >&2; exit 1; }; done
    fs_kernel_names+=("$stem")
    spv="$fs_gen_spv/$stem.spv"; inc="$fs_gen_spv/${stem}_spirv.inc"; sym="$(fs_symbol "$stem")"
    mirror="$(fs_mirror_dir "$comp")/${stem}_spirv.inc"
    if [[ -n "$fs_compiler" ]]; then
        case "$(basename -- "$fs_compiler")" in
            glslangValidator*) "$fs_compiler" -V --target-env vulkan1.1 "${fs_glsl_inc[@]}" -o "$spv" "$comp" > "$fs_gen/glslang.log" || { cat "$fs_gen/glslang.log" >&2; echo "kernel $comp failed to compile" >&2; exit 1; } ;;
            *) "$fs_compiler" -fshader-stage=compute --target-env=vulkan1.1 -O "${fs_glsl_inc[@]}" -o "$spv" "$comp" ;;
        esac
        [[ -z "$fs_spirv_val" ]] || "$fs_spirv_val" --target-env vulkan1.1 "$spv"
        fs_emit_inc "$spv" "$inc" "$comp" "$sym"
        mkdir -p "$(dirname -- "$mirror")"
        install -m 0644 -- "$inc" "$mirror"   # refresh the committed fallback
    else
        test -f "$mirror" || { echo "no SPIR-V compiler and no fallback $mirror for $comp" >&2; exit 1; }
        install -m 0644 -- "$mirror" "$inc"
        fs_inc_to_spv "$inc" "$spv"
    fi
    fs_gate_files+=("$spv")
done
# Kernel envelope gate (contract §15.6): fail the build on any violation.
"$fs_python" "$fs_script_dir/spv_gate.py" --max-bytes 131072 --max-storage-bindings 8 --max-threads 256 --max-shared 16384 "${fs_gate_files[@]}"

# ---- compile ------------------------------------------------------------------------------
mapfile -t fs_sources < <({ ls "$fs_native"/src/*.cpp; find "$fs_native/src/host" -type f -name '*.cpp'; } | sort)
"$fs_clang" -std=c++17 -O2 -fPIC -fvisibility=hidden -shared -static-libstdc++ \
    -DVK_USE_PLATFORM_ANDROID_KHR=1 -DFS_NATIVE_BUILD=1 \
    -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers \
    -Wl,--no-undefined -Wl,-z,max-page-size=16384 -Wl,-z,noexecstack \
    -I"$FS_UNITY_EDITOR_DIR/Data/PluginAPI" -I"$fs_gen" -I"$fs_gen_spv" -I"$fs_native/src" -I"$fs_native/include" \
    "${fs_sources[@]}" \
    -lvulkan -llog -landroid -lcamera2ndk -lmediandk \
    -o "$fs_output.tmp"
"$fs_strip" --strip-unneeded "$fs_output.tmp"
mv -- "$fs_output.tmp" "$fs_output"
install -m 0644 -- "$fs_script_dir/FinalScanNative.pluginmeta" "$fs_output.meta"

printf 'FinalScan native plugin: %s (%s bytes, android%s, spirv=%s kernels=%s sources=%s)\n' "$fs_output" "$(stat -c %s "$fs_output")" "$fs_api" "$(basename -- "$fs_spirv_source")" "${#fs_kernels[@]}" "${#fs_sources[@]}"
sha256sum "$fs_output" "$fs_output.meta" "$fs_gen_spv"/*.inc
