#!/usr/bin/env bash
# Compiles the world/render compute kernels (Native~/shaders/{world,render}/*.comp) to SPIR-V with
# glslangValidator (vulkan1.1), validates with spirv-val, enforces the kernel envelope gate (contract
# §15.6: <= 128 KiB per pipeline, <= 8 storage bindings, <= 256 threads, <= 16 KiB shared) and embeds
# them as Native~/src/host/{world,render}/spirv/<name>_spirv.inc (kSpv_<name>[]). The .comp files stay
# the source of truth; build_native.sh may replace this with its own pipeline (same .inc contract).
set -euo pipefail
fs_script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
fs_root="$(cd -- "$fs_script_dir/../.." && pwd -P)"
fs_shaders="$fs_root/Native~/shaders"
fs_gen="${FS_WORLD_SPV_DIR:-$(mktemp -d -t finalscan-world-spv.XXXXXX)}"
[[ -n "${FS_WORLD_SPV_DIR:-}" ]] || trap 'rm -rf -- "$fs_gen"' EXIT
command -v glslangValidator >/dev/null || { echo "glslangValidator not found" >&2; exit 1; }
fail=0
for group in world render; do
    out_dir="$fs_root/Native~/src/host/$group/spirv"
    mkdir -p "$out_dir"
    for comp in "$fs_shaders/$group"/*.comp; do
        name="$(basename -- "${comp%.comp}")"
        spv="$fs_gen/$name.spv"
        glslangValidator -V --target-env vulkan1.1 -I"$fs_shaders/world" -I"$fs_shaders/render" -o "$spv" "$comp" >/dev/null
        if command -v spirv-val >/dev/null; then spirv-val --target-env vulkan1.1 "$spv"; fi
        bytes=$(stat -c %s "$spv")
        # gate: size, storage bindings (count distinct SSBO block declarations actually used = OpDecorate ... Binding), threads, shared
        bindings=$(set +o pipefail; spirv-dis "$spv" 2>/dev/null | grep -c "OpDecorate %[A-Za-z0-9_]* Binding")
        threads=$(set +o pipefail; spirv-dis "$spv" 2>/dev/null | grep -m1 "OpExecutionMode .* LocalSize " | awk '{print $(NF-2)*$(NF-1)*$NF}')
        if (( bytes > 131072 )); then echo "GATE FAIL $name: $bytes B > 128 KiB" >&2; fail=1; fi
        if [[ -n "$bindings" ]] && (( bindings > 9 )); then echo "GATE FAIL $name: $bindings bindings (max 8 storage + 1 sampler)" >&2; fail=1; fi
        if [[ -n "$threads" ]] && (( threads > 256 )); then echo "GATE FAIL $name: $threads threads" >&2; fail=1; fi
        {
            echo "// Generated by Tools~/native/build_world_spirv.sh from Native~/shaders/$group/$name.comp. Do not edit."
            echo "#pragma once"
            echo "#include <stdint.h>"
            echo "static const uint32_t kSpv_${name}[] = {"
            od -An -v -tu4 -w16 "$spv" | sed -E 's/^ +//; s/ +/, /g; s/$/,/'
            echo "};"
        } > "$out_dir/${name}_spirv.inc"
        printf '%-28s %7d B  bindings=%s threads=%s\n' "$name" "$bytes" "${bindings:-?}" "${threads:-?}"
    done
done
exit $fail
