#!/usr/bin/env bash
# Builds libFinalScanNative.so (Android arm64, Unity NDK clang) into the host project's
# Assets/Plugins/Android, writes its .meta (Android/ARM64 plugin, 16 KiB aligned), embeds the
# overlap kernel SPIR-V (compiled with glslangValidator/glslc when found, else the committed
# fallback .inc), strips with llvm-strip and prints sha256 sums.
set -euo pipefail
fs_script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
source "$fs_script_dir/../dev_environment.sh"
fs_native="$FS_PACKAGE_ROOT/Native~"
fs_toolchain="$FS_ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64"
fs_clang=""
for api in 32 29; do
    if [[ -x "$fs_toolchain/bin/aarch64-linux-android${api}-clang++" ]]; then fs_clang="$fs_toolchain/bin/aarch64-linux-android${api}-clang++"; fs_api=$api; break; fi
done
[[ -n "$fs_clang" ]] || { echo "NDK clang not found under $fs_toolchain/bin" >&2; exit 1; }
fs_strip="$fs_toolchain/bin/llvm-strip"
test -x "$fs_strip"
fs_project="${1:-$FS_HOST_PROJECT}"
fs_output_dir="$fs_project/Assets/Plugins/Android"
fs_output="$fs_output_dir/libFinalScanNative.so"
fs_gen="${FS_NATIVE_GEN_DIR:-$(mktemp -d -t finalscan-native.XXXXXX)}"
[[ -n "${FS_NATIVE_GEN_DIR:-}" ]] || trap 'rm -rf -- "$fs_gen"' EXIT
mkdir -p "$fs_gen" "$fs_output_dir"

# ---- SPIR-V ---------------------------------------------------------------------------
fs_comp="$fs_native/shaders/overlap_job.comp"
fs_spv="$fs_gen/overlap_job.spv"
fs_inc="$fs_gen/overlap_job_spirv.inc"
fs_compiler=""
if command -v glslangValidator >/dev/null 2>&1; then fs_compiler="glslangValidator";
elif command -v glslc >/dev/null 2>&1; then fs_compiler="glslc";
elif [[ -x "$FS_ANDROID_NDK_ROOT/shader-tools/linux-x86_64/glslc" ]]; then fs_compiler="$FS_ANDROID_NDK_ROOT/shader-tools/linux-x86_64/glslc";
else
    for cand in "$FS_UNITY_EDITOR_DIR/Data/Tools/glslangValidator" "$FS_UNITY_EDITOR_DIR/Data/Tools/glslc"; do
        [[ -x "$cand" ]] && { fs_compiler="$cand"; break; }
    done
fi
fs_spirv_source="fallback"
if [[ -n "$fs_compiler" ]]; then
    case "$(basename -- "$fs_compiler")" in
        glslangValidator*) "$fs_compiler" -V --target-env vulkan1.1 -o "$fs_spv" "$fs_comp" >/dev/null ;;
        *) "$fs_compiler" -fshader-stage=compute --target-env=vulkan1.1 -O -o "$fs_spv" "$fs_comp" ;;
    esac
    if command -v spirv-val >/dev/null 2>&1; then spirv-val --target-env vulkan1.1 "$fs_spv"; fi
    {
        echo "// Generated by Tools~/native/build_native.sh from Native~/shaders/overlap_job.comp ($(basename -- "$fs_compiler")). Do not edit."
        echo "#pragma once"
        echo "#include <stdint.h>"
        echo "static const uint32_t kOverlapJobSpirv[] = {"
        od -An -v -tu4 -w16 "$fs_spv" | sed -E 's/^ +//; s/ +/, /g; s/$/,/'
        echo "};"
    } > "$fs_inc"
    fs_spirv_source="$fs_compiler"
    # Refresh the committed fallback so a host without a compiler builds the same kernel.
    install -m 0644 -- "$fs_inc" "$fs_native/src/spirv/overlap_job_spirv.inc"
else
    test -f "$fs_native/src/spirv/overlap_job_spirv.inc" || { echo "no SPIR-V compiler and no fallback Native~/src/spirv/overlap_job_spirv.inc" >&2; exit 1; }
    install -m 0644 -- "$fs_native/src/spirv/overlap_job_spirv.inc" "$fs_inc"
fi
fs_spirv_bytes=$(grep -o '[0-9]\+' "$fs_inc" | tail -n +2 | wc -l)

# ---- compile ------------------------------------------------------------------------------
fs_sources=("$fs_native"/src/*.cpp)
"$fs_clang" -std=c++17 -O2 -fPIC -fvisibility=hidden -shared -static-libstdc++ \
    -DVK_USE_PLATFORM_ANDROID_KHR=1 -DFS_NATIVE_BUILD=1 \
    -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers \
    -Wl,--no-undefined -Wl,-z,max-page-size=16384 -Wl,-z,noexecstack \
    -I"$FS_UNITY_EDITOR_DIR/Data/PluginAPI" -I"$fs_gen" -I"$fs_native/src" \
    "${fs_sources[@]}" \
    -lvulkan -llog -landroid -lcamera2ndk -lmediandk \
    -o "$fs_output.tmp"
"$fs_strip" --strip-unneeded "$fs_output.tmp"
mv -- "$fs_output.tmp" "$fs_output"
install -m 0644 -- "$fs_script_dir/FinalScanNative.pluginmeta" "$fs_output.meta"

printf 'FinalScan native plugin: %s (%s bytes, android%s, spirv=%s words=%s)\n' "$fs_output" "$(stat -c %s "$fs_output")" "$fs_api" "$fs_spirv_source" "$fs_spirv_bytes"
sha256sum "$fs_output" "$fs_inc" "$fs_output.meta"
