#!/usr/bin/env python3
"""FinalScan world ABI cross-check generator (contract §15.5 invariant 5).

Parses Native~/include/finalscan_world_abi.h (the single source of truth) and emits:
  Native~/shaders/world/fs_abi.glsl   GLSL structs (32-bit word packed, std430 compatible), constants,
                                      16-bit field accessors (bitfieldExtract/Insert), size defines
  Runtime/World/WorldAbi.cs           C# sequential-layout structs, constants, FsCounter enum and a
                                      runtime layout assertion (sizeof == header trailer comment)
plus the Unity .meta files for Runtime/World. The generator verifies the C layout it computes against
the `// N B` trailer comments in the header and fails when they disagree. Usage:
  python3 Tools~/native/gen_abi.py [--check]     (--check: exit 1 if outputs would change)
"""
import hashlib, os, re, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
HEADER = os.path.join(ROOT, "Native~", "include", "finalscan_world_abi.h")
OUT_GLSL = os.path.join(ROOT, "Native~", "shaders", "world", "fs_abi.glsl")
OUT_CS = os.path.join(ROOT, "Runtime", "World", "WorldAbi.cs")
OUT_CS_META = OUT_CS + ".meta"
OUT_DIR_META = os.path.join(ROOT, "Runtime", "World.meta")

C_SIZES = {"int16_t": 2, "uint16_t": 2, "int32_t": 4, "uint32_t": 4, "float": 4}
GLSL_TYPES = {"int32_t": "int", "uint32_t": "uint", "float": "float"}
CS_TYPES = {"int16_t": "short", "uint16_t": "ushort", "int32_t": "int", "uint32_t": "uint", "float": "float"}


class Field:
    def __init__(self, ctype, name, count):
        self.ctype, self.name, self.count = ctype, name, count   # count = None for scalars


class Struct:
    def __init__(self, name, fields, declared_size):
        self.name, self.fields, self.declared_size = name, fields, declared_size


def strip_comments(text):
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    return re.sub(r"//[^\n]*", "", text)


def parse(text):
    plain = strip_comments(text)
    structs, order = {}, []
    for m in re.finditer(r"typedef\s+struct\s+(\w+)\s*\{(.*?)\}\s*(\w+)\s*;", plain, flags=re.S):
        tag, body, name = m.group(1), m.group(2), m.group(3)
        assert tag == name, f"struct tag/name mismatch {tag}/{name}"
        fields = []
        for decl in [d.strip() for d in body.split(";") if d.strip()]:
            parts = decl.split(None, 1)
            ctype, names = parts[0], parts[1]
            for n in [x.strip() for x in names.split(",")]:
                am = re.match(r"(\w+)\[(\w+)\]$", n)
                if am:
                    cnt = am.group(2)
                    fields.append(Field(ctype, am.group(1), int(cnt) if cnt.isdigit() else cnt))   # symbolic counts resolved after the defines
                else:
                    fields.append(Field(ctype, n, None))
        # declared size from the trailer comment on the closing line in the original text
        sm = re.search(r"\}\s*" + re.escape(name) + r"\s*;[^\n]*?//\s*(\d+)\s*B\b", text)
        structs[name] = Struct(name, fields, int(sm.group(1)) if sm else None)
        order.append(name)
    defines = []
    for m in re.finditer(r"^#define\s+(FS_\w+)\s+(.+?)\s*$", plain, flags=re.M):
        defines.append((m.group(1), m.group(2).strip()))
    em = re.search(r"enum\s+FsCounter\s*\{(.*?)\}\s*;", plain, flags=re.S)
    counters, value = [], 0
    for item in [x.strip() for x in em.group(1).split(",") if x.strip()]:
        if "=" in item:
            n, v = [x.strip() for x in item.split("=")]
            value = int(v)
        else:
            n = item
        counters.append((n, value))
        value += 1
    return order, structs, defines, counters


def c_layout(structs, name):
    """Natural-alignment C layout; returns (size, align, [(field, offset, size)])."""
    s = structs[name]
    off, align, entries = 0, 1, []
    for f in s.fields:
        if f.ctype in C_SIZES:
            fsz = fa = C_SIZES[f.ctype]
        else:
            fsz, fa, _ = c_layout(structs, f.ctype)
        n = f.count or 1
        off = (off + fa - 1) // fa * fa
        entries.append((f, off, fsz * n))
        off += fsz * n
        align = max(align, fa)
    size = (off + align - 1) // align * align
    return size, align, entries


def eval_define(value, env):
    expr = value.replace("f", "").replace("u", "")
    expr = re.sub(r"0x([0-9A-Fa-f]+)", lambda m: str(int(m.group(1), 16)), expr)
    return eval(expr, {"__builtins__": {}}, env)   # header is trusted source


def define_kind(value):
    v = value.strip()
    if re.fullmatch(r"0x[0-9A-Fa-f]+u", v) or re.fullmatch(r"\d+u", v):
        return "uint"
    if re.search(r"[.]|f$", v) and not v.startswith("0x") and not v.startswith("("):
        return "float"
    return "int"


def pascal(name):
    return "".join(p.capitalize() for p in name.lower().split("_"))


def gen_glsl(order, structs, defines, counters, env):
    L = ["// Generated by Tools~/native/gen_abi.py from Native~/include/finalscan_world_abi.h. Do not edit.",
         "// 16-bit C fields are packed pairwise into uint words (low field first, little endian) so the",
         "// std430 layout matches the C layout byte for byte. Use the fsGet_/fsSet_ accessors.",
         "#ifndef FS_ABI_GLSL", "#define FS_ABI_GLSL", ""]
    for n, v in defines:
        kind = define_kind(v)
        val = env[n]
        if kind == "float":
            L.append(f"#define {n} {float(val)!r}")
        elif kind == "uint":
            L.append(f"#define {n} {int(val)}u")
        else:
            L.append(f"#define {n} {int(val)}")
    L.append("")
    for n, v in counters:
        L.append(f"#define {n} {v}")
    L.append("")
    for name in order:
        s = structs[name]
        size, _, _ = c_layout(structs, name)
        words, pending, accessors = [], None, []
        for f in s.fields:
            if f.ctype in ("int16_t", "uint16_t"):
                assert f.count is None, "16-bit arrays unsupported"
                if pending is None:
                    pending = f
                else:
                    word = f"{pending.name}_{f.name}"
                    words.append(f"    uint {word};")
                    for fld, off in ((pending, 0), (f, 16)):
                        signed = fld.ctype == "int16_t"
                        t = "int" if signed else "uint"
                        src = f"int(s.{word})" if signed else f"s.{word}"
                        accessors.append(f"{t} fsGet_{name}_{fld.name}({name} s) {{ return bitfieldExtract({src}, {off}, 16); }}")
                        accessors.append(f"void fsSet_{name}_{fld.name}(inout {name} s, {t} v) {{ s.{word} = bitfieldInsert(s.{word}, uint(v), {off}, 16); }}")
                    pending = None
            else:
                assert pending is None, f"{name}.{f.name}: 16-bit field not paired to a 32-bit word"
                gt = GLSL_TYPES.get(f.ctype, f.ctype)
                words.append(f"    {gt} {f.name}[{f.count}];" if f.count else f"    {gt} {f.name};")
        assert pending is None, f"{name}: trailing unpaired 16-bit field"
        L.append(f"struct {name} {{")
        L.extend(words)
        L.append(f"}};  // {size} B")
        L.append(f"#define FS_ABI_{name.upper()}_BYTES {size}")
        L.extend(accessors)
        L.append("")
    L.append("#endif // FS_ABI_GLSL")
    return "\n".join(L) + "\n"


def gen_cs(order, structs, defines, counters, env):
    L = ["// Generated by Tools~/native/gen_abi.py from Native~/include/finalscan_world_abi.h. Do not edit.",
         "// Layouts are byte-identical to the C structs (Pack = 1, natural order); WorldAbi.AssertLayout() checks sizes.",
         "using System;", "using System.Runtime.InteropServices;", "", "namespace FinalScan.World", "{"]
    for name in order:
        s = structs[name]
        size, _, _ = c_layout(structs, name)
        has_array = any(f.count for f in s.fields)
        L.append(f"    [StructLayout(LayoutKind.Sequential, Pack = 1)]")
        L.append(f"    public {'unsafe ' if has_array else ''}struct {name}  // {size} B")
        L.append("    {")
        for f in s.fields:
            ct = CS_TYPES.get(f.ctype, f.ctype)
            if f.count:
                L.append(f"        public fixed {ct} {f.name}[{f.count}];")
            else:
                L.append(f"        public {ct} {f.name};")
        L.append(f"        public const int SizeBytes = {size};")
        L.append("    }")
        L.append("")
    L.append("    public enum FsCounter")
    L.append("    {")
    for n, v in counters:
        L.append(f"        {pascal(n[len('FS_CTR_'):])} = {v},")
    L.append("    }")
    L.append("")
    L.append("    public static class WorldAbi")
    L.append("    {")
    for n, v in defines:
        kind = define_kind(v)
        val = env[n]
        cname = pascal(n[len("FS_"):])
        if kind == "float":
            L.append(f"        public const float {cname} = {float(val)!r}f;")
        elif kind == "uint":
            L.append(f"        public const uint {cname} = {int(val)}u;")
        else:
            L.append(f"        public const int {cname} = {int(val)};")
    L.append("")
    L.append("        /// <summary>Throws when the managed layouts drift from the native header (call once at startup).</summary>")
    L.append("        public static void AssertLayout()")
    L.append("        {")
    for name in order:
        L.append(f"            Check(Marshal.SizeOf<{name}>(), {name}.SizeBytes, \"{name}\");")
    L.append("        }")
    L.append("")
    L.append("        static void Check(int actual, int expected, string name)")
    L.append("        {")
    L.append("            if (actual != expected) throw new InvalidOperationException($\"FinalScan ABI mismatch: {name} is {actual} B, native expects {expected} B\");")
    L.append("        }")
    L.append("    }")
    L.append("}")
    return "\n".join(L) + "\n"


def meta(rel, folder=False):
    guid = hashlib.md5(("eu.monle.finalscan/" + rel).encode()).hexdigest()
    if folder:
        return f"fileFormatVersion: 2\nguid: {guid}\nfolderAsset: yes\nDefaultImporter:\n  externalObjects: {{}}\n  userData: \n  assetBundleName: \n  assetBundleVariant: \n"
    return f"fileFormatVersion: 2\nguid: {guid}\n"


def main():
    check = "--check" in sys.argv
    text = open(HEADER, encoding="utf-8").read()
    order, structs, defines, counters = parse(text)
    env = {}
    for n, v in defines:
        env[n] = eval_define(v, env)
    for name in order:
        for f in structs[name].fields:
            if isinstance(f.count, str):
                f.count = int(env[f.count])
    for name in order:
        size, _, _ = c_layout(structs, name)
        d = structs[name].declared_size
        if d is not None and d != size:
            # The compiler layout is the truth all three consumers must share; the trailer comment is
            # documentation. Warn loudly (header owner should fix the comment or the fields).
            print(f"gen_abi: WARNING {name} computed {size} B but header trailer comment declares {d} B; "
                  f"emitting {size} B", file=sys.stderr)
    for n, v in counters:
        pass
    outputs = {
        OUT_GLSL: gen_glsl(order, structs, defines, counters, env),
        OUT_CS: gen_cs(order, structs, defines, counters, env),
        OUT_CS_META: meta("Runtime/World/WorldAbi.cs"),
        OUT_DIR_META: meta("Runtime/World", folder=True),
    }
    changed = []
    for path, content in outputs.items():
        old = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if old != content:
            changed.append(path)
            if not check:
                os.makedirs(os.path.dirname(path), exist_ok=True)
                open(path, "w", encoding="utf-8").write(content)
    for name in order:
        print(f"{name}: {c_layout(structs, name)[0]} B")
    print(f"defines={len(defines)} counters={len(counters)} changed={len(changed)}")
    if check and changed:
        sys.exit("gen_abi --check: outputs out of date: " + ", ".join(os.path.relpath(p, ROOT) for p in changed))


if __name__ == "__main__":
    main()
