#!/usr/bin/env bash
# FinalScan frozen local development environment (kingston-unity host, aidisk package).
FS_PACKAGE_ROOT="${FS_PACKAGE_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)}"
FS_DEV_ROOT="${FS_DEV_ROOT:-/mnt/kingston-unity}"
FS_UNITY_VERSION="${FS_UNITY_VERSION:-6000.5.9f1}"
FS_UNITY_EXECUTABLE="${FS_UNITY_EXECUTABLE:-${FS_DEV_ROOT}/Unity/Hub/Editor/${FS_UNITY_VERSION}/Editor/Unity}"
FS_UNITY_EDITOR_DIR="$(dirname -- "$FS_UNITY_EXECUTABLE")"
FS_TEMPLATE_HOST="${FS_TEMPLATE_HOST:-${FS_DEV_ROOT}/Unity/Projects/QuestInfiniteScanHost}"
FS_HOST_PROJECT="${FS_HOST_PROJECT:-${FS_DEV_ROOT}/Unity/Projects/FinalScanHost}"
FS_PACKAGE_NAME="eu.monle.finalscan"
FS_BUILD_DIR="${FS_BUILD_DIR:-${FS_DEV_ROOT}/Builds/FinalScan}"
FS_APK_PATH="${FS_APK_PATH:-${FS_BUILD_DIR}/FinalScan-release.apk}"
FS_GRADLE_USER_HOME="${FS_GRADLE_USER_HOME:-${FS_BUILD_DIR}/gradle-user-home}"
FS_ANDROID_SDK_ROOT="${FS_ANDROID_SDK_ROOT:-${FS_UNITY_EDITOR_DIR}/Data/PlaybackEngines/AndroidPlayer/SDK}"
FS_ANDROID_NDK_ROOT="${FS_ANDROID_NDK_ROOT:-${FS_UNITY_EDITOR_DIR}/Data/PlaybackEngines/AndroidPlayer/NDK}"
FS_ADB="${FS_ADB:-${FS_ANDROID_SDK_ROOT}/platform-tools/adb}"
FS_DEVICE_SERIAL="${FS_DEVICE_SERIAL:-340YC20G7X0QZ4}"
FS_APP_ID="eu.monle.finalscan"
FS_KEYS_DIR="${FS_KEYS_DIR:-${FS_DEV_ROOT}/Server/keys}"
FS_RELEASE_KEYSTORE="${FS_RELEASE_KEYSTORE:-${FS_KEYS_DIR}/finalscan-release.jks}"
FS_RELEASE_KEY_ALIAS="${FS_RELEASE_KEY_ALIAS:-finalscan}"
FS_EVIDENCE_DIR="${FS_EVIDENCE_DIR:-${FS_BUILD_DIR}/evidence}"
export FS_PACKAGE_ROOT FS_DEV_ROOT FS_UNITY_VERSION FS_UNITY_EXECUTABLE FS_UNITY_EDITOR_DIR
export FS_TEMPLATE_HOST FS_HOST_PROJECT FS_PACKAGE_NAME FS_BUILD_DIR FS_APK_PATH FS_GRADLE_USER_HOME
export FS_ANDROID_SDK_ROOT FS_ANDROID_NDK_ROOT FS_ADB FS_DEVICE_SERIAL FS_APP_ID
export FS_KEYS_DIR FS_RELEASE_KEYSTORE FS_RELEASE_KEY_ALIAS FS_EVIDENCE_DIR
